### ISSUE TITLE
Option to choose Icons for webapps

### ISSUE THREAD

**Issue by Garry3064** [filips123/PWAsForFirefox#100]
### Problem Description

Sometimes on some sites, a low-resolution icon is chosen as the application shortcut icon

### Proposed Solution

To allow to change the icon, or show the .desktop file location so that it can be modified.

### Additional Information

This is related to Linux. '.desktop' is a file used to show parameters of an application shortcut (what is executed, which icon to be shown, terminal?, etc.).

**Comment by filips123** [comment]
I may add support for changing icon from the extension in the future, but I'll first need to find what the best way to do this is. Another icon-related issue is #44.

In the meanwhile, you can manually edit `.desktop` files for PWAs. They are installed into `~/.local/share/applications/` and you can find PWA IDs by running `firefoxpwa profile list`.

(I also edited your issue message so Markdown renders correctly)

**Comment by Garry3064** [comment]
Thank you for providing the answer so quickly and editing the issue. I found the .desktop location and by changing the icon path to a better one, I could get a high-quality icon for two of my applications. I have been tampering with `.desktop` files before, in `/usr/share/applications` because for `.AppImages` and `.tar.gz` files, this may be the only way to get their icons on the Linux desktop. Since the way the icon is taken is different in different OSes, please take your time to figure out the best way to do this.

**Comment by AnthonyWharton** [comment]
Is there a similar short term workaround for users wanting to change icons on Windows/macOS, if so what location would you find icon files?

I have found icons in `%appdata%\FirefoxPWA\icons\<ID>\site.ico` on Windows, and no equivalent on macOS (other than finding the icns file inside the package contents of the generated .app files), but changing these does not seem to help. Thanks!

**Comment by filips123** [comment]
Well, since 2.4.0 (which was released yesterday), there is now proper support for setting custom icons.

Make sure that both the extension and the native program are updated to 2.4.0. Then, you will be able to provide a custom icon URL when editing the web app from the extension.

![screenshot](https://user-images.githubusercontent.com/16626308/212703843-2ca18c61-39e1-4724-bb0e-d3aa432bd5b4.png)

**Comment by filips123** [comment]
Yes, it needs to be from an URL.
