### ISSUE TITLE
Enable better touchscreen usage on linux

### ISSUE THREAD

**Issue by aarron-lee** [filips123/PWAsForFirefox#101]
### Problem Description

Currently, firefoxpwa apps cannot scroll via touch, instead touch events default to selecting text on linux.

### Proposed Solution

Enable an option (either via CLI or otherwise) for to set MOZ_USE_XINPUT2=1 on Linux

### Additional Information

This also enables [Pixel-perfect trackpad scrolling](https://wiki.archlinux.org/title/Firefox/Tweaks#Pixel-perfect_trackpad_scrolling)

### Workaround

if you're on Xorg:

```bash
echo export MOZ_USE_XINPUT2=1 | sudo tee /etc/profile.d/use-xinput2.sh
```
then restart computer.

Edit:

If you're on Wayland:

```bash
echo export MOZ_ENABLE_WAYLAND=1 | sudo tee /etc/profile.d/use-moz-enable-wayland.sh
```

then restart computer

**Comment by wdkevonfernando** [comment]
What does your FirefoxPWA say it uses as window protocol?
I thought the issue was that FirefoxPWA does not set `MOZ_ENABLE_WAYLAND=1` and therfore uses _xwayland_ as its window protocol. Because my regular Firefox installation in contrast has `MOZ_ENABLE_WAYLAND=1` set and instead uses _wayland_ as its window protocol.

**Comment by wdkevonfernando** [comment]
By the way, thanks for the workaround. I used `MOZ_ENABLE_WAYLAND=1` instead and it now works as expected.

**Comment by filips123** [comment]
Currently `firefoxpwa` directly launches Firefox binary so it just uses its defaults, while normally /usr/bin/firefox` is a shell script that sets `MOZ_ENABLE_WAYLAND` and some other environment variables.

I will add a way to specify environment variables that are set when launching Firefox via config (and probably also through extension).

**Comment by aarron-lee** [comment]
> What does your FirefoxPWA say it uses as window protocol?

I'm assuming it's xwayland, since the `MOZ_USE_XINPUT2=1` workaround fixed the issues. xeyes reacts properly to the firefoxPWA apps.

My regular Firefox installation uses wayland, xeyes doesn't move at all for my regular install.

>  I used MOZ_ENABLE_WAYLAND=1 instead and it now works as expected.

Ah, let me try that and see if that works instead.

**Comment by wdkevonfernando** [comment]
For some reason now my PWAs share the same app icon as my default Firefox installation when using the workaround. Just sharing this in case it might have any relevance for the proper implementation.

**Comment by filips123** [comment]
> I will add a way to specify environment variables that are set when launching Firefox via config (and probably also through extension).

I added an option in the extension settings to enable Wayland (and a few other things linke xinput2). Other environment variables can also be added as the `variables` key in the `config.json` file.

> For some reason now my PWAs share the same app icon as my default Firefox installation when using the workaround. Just sharing this in case it might have any relevance for the proper implementation.

This should also be fixed in the next release (#50).

**Comment by Hedronmx** [comment]
Sorry for reviving this. But should I still use the workaround? Or just by activating Use Wayland will make apps scroll with touch? Thanks

**Comment by filips123** [comment]
Activating Use Wayland should work file.
