### ISSUE TITLE
Disable Firefox context menu

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#113]
I want to disable the Firefox context menu completely.
![image](https://user-images.githubusercontent.com/23485114/147565292-ab45e084-156d-4c44-b7fe-c66ca15c33f3.png)
But I don't want to miss the web apps context menu.
![image](https://user-images.githubusercontent.com/23485114/147565357-cc2887cc-9b97-413a-86cb-ccff738cbcbb.png)
Please help me.

**Comment by filips123** [comment]
On the first image, it seems you are shift-right-clicking on the video. In this case, Firefox will always display its context menu, even if the web app creates custom context menus. Do you really need to disable all Firefox context menus (even when using shift + right-click), or is disabling them just on normal right-click enough?

If the latter is enough, you could use some userscript manager (like Greasemonkey or Tampermonkey) to create a userscript that registers an empty contextmenu handler on every website, which should prevent Firefox context menus from opening:

```js
// ==UserScript==
// @name     Disable Firefox Context Menu
// @version  1
// @match    https://*/*
// @match    http://*/*
// ==/UserScript==

document.addEventListener('contextmenu', event => event.preventDefault());
```

If you need to completely disable all Firefox context menus, you will have to use a custom and more advanced UserChromeJS script. I think it should be possible, but unfortunately, it would require more work and I currently don't have much time to investigate how to do it.

**Comment by xmha97** [comment]
Thanks for your explanation.
