### ISSUE TITLE
Launch the web app automatically

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#115]
Hi, I want to see YouTube videos on the web app instead of the browser (Firefox).
Please add an option to launch the web app automatically.
![image](https://user-images.githubusercontent.com/23485114/147678737-6532548c-690c-48f7-842b-e105bf0f87c9.png)
Thanks.

**Comment by markcellus** [comment]
This request confuses me. I thought web apps can only be viewed in a browser. 🤔

**Comment by xmha97** [comment]
> This request confuses me. I thought web apps can only be viewed in a browser. 🤔

In Android, web apps can be installed like a native app. (See [WebAPK](https://developers.google.com/web/fundamentals/integration/webapks))

![image](https://user-images.githubusercontent.com/23485114/147715297-488125e1-0c67-4ae6-83b0-49e724d7cd85.png)

I need this feature for Windows.

**Comment by markcellus** [comment]
Right but, in your Android example, that web app is still inside of the browser you used to "install" it. It just doesn't look like it, because it doesnt show the browser chrome (e.g. toolbar, header, footer etc).

**Comment by filips123** [comment]
I think he means to launch PWA automatically (so, probably close the current browser tab and launch PWA on the same URL) when you open a website that has been installed as PWA. This is similar as an option in mobile browsers to open website in a native app if it exists. I'll probably add some option to enable this in the future (but disabled by default).

But there are few things to consider:

* Just closing current tab might be annoying, as it would also close a previous website (in case link had a default target of opening in the same tab). Forcing all such URLs into a new tab would probably mostly solve this issue, but I'm not sure if this is possible with extensions.

* It may cause some issues in the same way as "Open out of scope URLs in a default browser" does, for example, with SSO. To solve this, we could have an option to disable this behavior for specific PWAs or domains.

* What if there are multiple PWAs installed for the same website. On Chrome, Edge and Android, this is not possible, so they can just open installed PWA, but I intentionally added support to install multiple websites as different PWAs in different profiles. How should opening behave in this case? Should it just do nothing, or should it display some popup to let user choose which PWA to open?

**Comment by xmha97** [comment]
Thank you for your explanation.

> * What if there are multiple PWAs installed for the same website. On Chrome, Edge and Android, this is not possible, so they can just open installed PWA, but I intentionally added support to install multiple websites as different PWAs in different profiles. How should opening behave in this case? Should it just do nothing, or should it display some popup to let user choose which PWA to open?

I don't install multiple PWAs for the same website but I think it should display some popup to let the user choose which PWA to open. Is it hard to implement?

**Comment by filips123** [comment]
I think it shouldn't be too hard.

**Comment by xmha97** [comment]
> I think it shouldn't be too hard.

@filips123 Do you have a plan to implement this feature?

**Comment by filips123** [comment]
Yes, but I was doing some other things and I didn't have time yet.

**Comment by filips123** [comment]
This will be available in 2.0.0. To use it, you first need to enable it from the extension settings ("Enable automatic web app launching") and separetly for each web app ("Auto launch this web app"):

![settings](https://user-images.githubusercontent.com/16626308/182027701-d11ff5f4-fdb1-4887-82b3-25a291fed30e.png)

However, please note that the feature is experimental and may not work with all websites. It will probably also impact the performance of loading *all* websites while enabled because it will need to run `firefoxpwa-connector` for every request in order to determine whether launching is enabled. I will try to improve this in the future, but I'm not sure yet how.
