### ISSUE TITLE
about:config

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#117]
How I can open `about:config` on PWAsForFirefox?
On Thunderbird, there is a button on the settings to open this page.
![image](https://user-images.githubusercontent.com/23485114/147879585-0650f681-c274-4167-9872-02b36c242d25.png)

**Comment by filips123** [comment]
You can press `F6` and then enter `about:config` (or any other URL).

**Comment by xmha97** [comment]
OK, Thanks.
