### ISSUE TITLE
PWA window is closed when out-of-scope URLs are opened in default browser

### ISSUE THREAD

**Issue by 1player** [filips123/PWAsForFirefox#120]
### Description

When the "Open out of scope URLs in a default browser" option is enabled, clicking out-of-scope links closes the PWA window.

### Steps to Reproduce

1. Enable "Open out of scope URLs in a default browser (can break some websites)" setting.
2. Click on an out of scope URL

### Additional Information

The link is opened correctly in the default browser, but the original PWA window should be preserved.

My use case is having a PWA for my webmail (Fastmail): I want any link to open to my regular Firefox window, while keeping the Fastmail app running. If I disable that option links are opened in the webmail app, which I do not want.

### Environment

* Operating system: Fedora Linux 35
* System architecture: x64_64
* Desktop environment: GNOME 41
* Installation method: rpm
* PWAsForFirefox extension version: 1.4.0
* PWAsForFirefox native version: 1.4.0
* Firefox version: 95.0.2

**Comment by filips123** [comment]
You can try enabling "Force links into a new window" (and then restarting the app). With this option enabled, every link with `target="_blank"` (which Fastmail probably sets for external URLs) will be opened in a new window, so the app won't close when opening out-of-scope URLs (it will basically open a new window with that URL and immediately close it).

**Comment by 1player** [comment]
That seems to work, thanks
