### ISSUE TITLE
Launch PWA with a URL argument

### ISSUE THREAD

**Issue by AlfredEVOL** [filips123/PWAsForFirefox#121]
### Problem Description

It is not currently possible to launch a PWA with a URL argument

```
firefoxpwa site launch <site-id> https://an.example.site/blog/1
```

Having this can allow the system to launch urls directly into the PWA instead of firefox

**Comment by filips123** [comment]
You can launch PWAs on custom URLs with

```
firefoxpwa site launch <site-id> --url https://an.example.site/blog/1
```

**Comment by AlfredEVOL** [comment]
great, thanks
