### ISSUE TITLE
Automatically make the default profile of the pwa the same as current browser's profile

### ISSUE THREAD

**Issue by arihant2math** [filips123/PWAsForFirefox#123]
### Problem Description

Settings do not sync automatically, and many users would like them to

### Proposed Solution

Make the default profile the same as the current browsers profile to eliminate confusion.

**Comment by filips123** [comment]
Unfortunately, this would be very hard to do and could break some things, so I cannot implement it. There are multiple problems, including potential instability (in case something broke with this project, it could also affect normal profile) and difficult handling of settings that need to be different in normal and PWA profile (for example, in PWA profile, widgets need to be placed in the title/tab bar, while in normal profile, they are in the address/tool bar).

If you want to sync data between your main and PWA profile, I recommend using Firefox Account or a third-party sync solution. Or you could try to symlink some files with settings from both profiles, but this may be unstable and I don't know if it will work.

I may revise this in the future if I find a good way of implementing it.

**Comment by markcellus** [comment]
@filips123 while i understand the good nature of OP's request, I think your decision is a good call. 👍 

I can appreciate not mixing profiles by default. Not doing that keeps funtionality in PWAs contained, which makes them more secure by default. I'd hate for this to be changed, even at the expense of losing the convenience to share settings between each of the browsers instances.
