### ISSUE TITLE
Can't install runtime

### ISSUE THREAD

**Issue by FayneAldan** [filips123/PWAsForFirefox#125]
### Description

Can't install runtime

### Additional Information

```
00:38:26 [INFO] Extracting the runtime archive
00:38:26 [ERROR] Failed to process request

Caused by:
    0: Failed to install runtime
    1: Failed to extract the runtime
    2: The system cannot find the file specified. (os error 2)
```

### Environment

* Operating system: Windows 11 Pro
* System architecture: x64
* Installation method: Tried both MSI and WinGet
* PWAsForFirefox extension version: 1.4.0
* PWAsForFirefox native version: 1.4.0
* Firefox version: 96.0.3

**Comment by filips123** [comment]
I think this happens because [7-Zip](https://7-zip.org/) is not correctly installed for some reason. Please try to manually install 7-Zip from its website (or using WinGet) and then again install runtime.

**Comment by FayneAldan** [comment]
> for some reason
Maybe because I don't use 7-Zip? 7-Zip isn't DPI aware so I use a fork (NanaZip) instead. Why not download 7-Zip automatically?

**Comment by filips123** [comment]
Well, 7-Zip should be downloaded automatically, but wasn't and I'm not sure why. PWAsForFirefox [checks](https://github.com/filips123/PWAsForFirefox/blob/main/native/src/components/_7zip.rs) if 7-Zip is installed and automatically install it if needed. Maybe it detected NanaZip and thought 7-Zip is installed, but when trying to launch it, it failed.

You can manually temporarily install 7-Zip to install the runtime and then delete it. And I will check if I can also support NanaZip if it's installed in the future.

**Comment by FayneAldan** [comment]
Actually, now that I think about it, NanaZip is packaged as an MSIX / Microsoft Store app. Any file operations in AppData are redirected to a Virtual File System. I did disable NanaZip's app aliases and installed 7zip and it worked.

![image](https://user-images.githubusercontent.com/1149870/152402681-027d2ff2-c607-4d9d-9fa3-ddd075f135c4.png)

Fun fact: It also doesn't work if 7-Zip is installed via [Scoop](https://scoop.sh/).
