### ISSUE TITLE
Option to choose your own icon for your web apps

### ISSUE THREAD

**Issue by snydox** [filips123/PWAsForFirefox#128]
### Problem Description

Most of my WebApps look fine but the WhatsApp Web icon looks blurry. Is there a way to change it?

### Proposed Solution

No idea.

### Additional Information

Screenshot below.
![Screenshot from 2022-02-05 13-53-13](https://user-images.githubusercontent.com/13590875/152655449-9adeaaa9-5253-4182-bd74-9280c5b6ce03.png)

**Comment by filips123** [comment]
Icons for web apps are stored inside `~/.local/share/icons/hicolor` (or `$XDG_DATA_HOME/icons/hicolor`, if `$XDG_DATA_HOME` is set). To change the icon, you need to get web app's ID using `firefoxpwa profile list`. Then, you can download your own icon and save it into `~/.local/share/icons/hicolor/ICON_SIZE/apps/FFPWA-SITE_ID.png`.

I will probably implement a way to change icons using extension in the future.

**Comment by snydox** [comment]
Thank you for your explanation @filips123 but life's too short so I did something simpler. Basically I edited the .desktop files with the address of some icons I downloaded :)

**Comment by mind-overflow** [comment]
I'm actually having an issue where there is a high-res icon in the 194x194 folder, and yet, in GNOME, the WhatsApp icon that's used is the 48x48 blurry one. Is this how it's supposed to work?

**Comment by snydox** [comment]
> I'm actually having an issue where there is a high-res icon in the 194x194 folder, and yet, in GNOME, the WhatsApp icon that's used is the 48x48 blurry one. Is this how it's supposed to work?

Hi @mind-overflow, unfortunately, the same thing happens to some of my PWAs. Luckily, there's a work around. Go to [https://www.flaticon.com](https://www.flaticon.com) and download the icon in 512px.

I personally created a folder called **~/.icons**

To change the app icon you need to find the .desktop file here: ~/.local/share/applications
The .desktop file won't have the name of the app but it will start with FFPWA*. You can open one by one until you find the correct one, or you could type this in the terminal (let's say you're looking for WhatsApp):

> $ grep WhatsApp ~/.local/share/applications/*

It should give you the filename.

Open the file and look for Icon=************** and change it with the full path of your icon.
> Icon=/home/username/.icons/whatsapp.png

That's it! This is a workaround, but I'm pretty sure that @filips123 will come with a better solution soon :)

![icons-folder](https://user-images.githubusercontent.com/13590875/169575061-80b5402c-20b8-4a75-a226-24fe819dad3e.png)

**Comment by filips123** [comment]
There is now a support for setting custom icon URLs when installing or updating PWAs. This will be available in 2.4.0.
