### ISSUE TITLE
Native connector doesn't connect with LibreWolf

### ISSUE THREAD

**Issue by Sid127** [filips123/PWAsForFirefox#134]
### Description

The firefoxpwa native connector doesn't connect with Firefox-forked browsers, such as LibreWolf

### Steps to Reproduce

1. Install a Firefox-fork, LibreWolf in this case
2. Install the firefox-pwa native package from repos, and the extension from mozilla add-ons
3. Wait for the Setup page to open
4. The setup page doesn't get to the runtime installation step

### Additional Information

I don't have much experience debugging, but fwiw I have followed the advanced installation instructions and placed all librewolf files in the required directories

### Environment

* Operating system: Arch Linux
* System architecture: 64 bit
* Desktop environment: 
* Installation method: AUR
* PWAsForFirefox extension version: 1.4.0
* PWAsForFirefox native version: 1.4.0
* Firefox version: LibreWolf 97

**Comment by filips123** [comment]
LibreWolf has its own [native manifests location](https://librewolf.net/docs/faq/#how-do-i-get-native-messaging-to-work) so it cannot detect connectors made for normal Firefox. However, you can run these two commands to link manifest locations of the normal Firefox with the LibreWolf ones:

```bash
ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
sudo ln -s /usr/lib/mozilla/native-messaging-hosts /usr/lib/librewolf/native-messaging-hosts
```

I will probably add this to the documentation in the next release.

**Comment by Sid127** [comment]
that worked beautifully, thanks a ton!

**Comment by ThisNekoGuy** [comment]
@filips123 `/usr/lib/librewolf/native-messaging-hosts` isn't a path on Gentoo; there's `/usr/lib64/librewolf` but it doesn't include `native-messaging-hosts` (at least now as of 2024)

**Comment by filips123** [comment]
What if you just copy `/usr/lib64/mozilla/native-messaging-hosts/firefoxpwa.json` to `/usr/lib64/librewolf/native-messaging-hosts/firefoxpwa.json`? Does it work if you also copy it to `/usr/lib/librewolf/native-messaging-hosts/firefoxpwa.json`?

**Comment by ThisNekoGuy** [comment]
I just managed to get it to work by symlinking like this:
`sudo ln -s /usr/lib/mozilla/native-messaging-hosts/firefoxpwa.json /usr/lib64/librewolf/native-messaging-hosts/firefoxpwa.json`

Had to create the `native-messaging-hosts` folder for librewolf first, though
