### ISSUE TITLE
Firefox PWA ignores env variables in /etc/environment and won't launch Wayland native

### ISSUE THREAD

**Issue by winteriscariot** [filips123/PWAsForFirefox#136]
I have the following variables set in /etc/envrionment:

    MOZ_USE_XINPUT2=1
    MOZ_WAYLAND_ENABLED=1

i also have this set in ~/.bashrc just in case:

    export MOZ_ENABLE_WAYLAND=1

yet all Firefox PWAs launch using Xwayland. I can't even get it to launch in a Wayland session by editing the .desktop file:

    Exec=env MOZ_WAYLAND_ENABLED=1 MOZ_USE_XINPUT2=1 /usr/bin/firefoxpwa site launch 01FWJ38MZ6WGQTFNTQ12ZE699E

this still launches in Xwayland

is there a recommended way of achieving this? Firefox certainly is capable of native Wayland.

**Comment by winteriscariot** [comment]
Note: normal firefox launches in native wayland mode without an issue

Arch Linux

**Comment by filips123** [comment]
I'm not sure why your environment variables don't work, but you can enable Wayland using the settings page in the extension.

![screenshot](https://user-images.githubusercontent.com/16626308/156930638-4f3c5950-2424-429a-b630-abb7bd864bca.png)

If enabled, `firefoxpwa` program will [automatically add](https://github.com/filips123/PWAsForFirefox/blob/7bed83a7cd02d584a4d34beb51bc658f8fe6ca5a/native/src/components/site.rs#L153-L162) required environment variables when launching Firefox.

**Comment by filips123** [comment]
I will close this issue as Wayland can be enabled through the extension settings and other environment variables can be added to the `variables` key in `config.json`. If anyone still has the same issue, please comment and I will reopen it.
