### ISSUE TITLE
is there a way to remove the window tab

### ISSUE THREAD

**Issue by safak45x** [filips123/PWAsForFirefox#141]
![Screenshot_20220326_025342](https://user-images.githubusercontent.com/59151376/160216044-62d93273-61b9-4f35-82f6-496ba9b5003b.png)
Can I completely remove the area I circled in red in the picture?
Or is it possible to add such an option as a request?

**Comment by safak45x** [comment]
![Screenshot_20220326_031258](https://user-images.githubusercontent.com/59151376/160216609-77415c16-ca63-47eb-a5c2-eeb133017177.png)
I got rid of it with a small change in your css files, it's better like this 😅

**Comment by filips123** [comment]
The recommended solution is to enable client-side decorations (CSD) for Firefox, so content inside that red area (widget and menu icons) is displayed in the same line as window control buttons. To do this, go to `about:config` (press F6 and then enter `about:config`) and set `browser.tabs.inTitlebar` to `1`.

![slika](https://user-images.githubusercontent.com/16626308/164933731-25dfef2e-fb9e-48c7-8df4-d2d5feb0f471.png)

If you don't want to use CSD, there is an "official" way of hiding that area. It should work the same as your CSS change, but it is more supported. Go to `about:config` and enable `firefoxpwa.enableHidingIconBar`. Then, go to the Firefox customize toolbar page and uncheck "Icon Bar" toolbar. If you need to show it later, you can press Ctrl+Alt.
