### ISSUE TITLE
Linux: Can't install Connector as debian package via apt repository

### ISSUE THREAD

**Issue by seltzered** [filips123/PWAsForFirefox#143]
### Description

Following the directions on https://packagecloud.io/filips/FirefoxPWA , I was not able to install the connector package following the instructions 

### Steps to Reproduce

1. Tried `curl -L "https://packagecloud.io/filips/FirefoxPWA/gpgkey" | sudo apt-key add -echo "deb https://packagecloud.io/filips/FirefoxPWA/any/ any main" | sudo tee /etc/source.list.d/firefoxpwa.list`
2. got error `100  4004  100  4004    0     0   2603      0  0:00:01  0:00:01 --:--:-- 13084
(23) Failed writing body` 
3. observed `/etc/source.list.d/firefoxpwa.list` was empty

### Workaround

Manual installation of deb package works fine. Thanks for this!

### Environment

* Operating system: Ubuntu 21.10
* System architecture: Intel
* Desktop environment: Gnome
* Installation method: DEB

**Comment by filips123** [comment]
Did you run everything as a single command? You need to run it is two commands:

```bash
curl -L "https://packagecloud.io/filips/FirefoxPWA/gpgkey" | sudo apt-key add -
```
```bash
echo "deb https://packagecloud.io/filips/FirefoxPWA/any/ any main" | sudo tee /etc/apt/sources.list.d/firefoxpwa.list
```

**Comment by seltzered** [comment]
D'oh, thought I had done that. Works now, thanks.
