### ISSUE TITLE
Mac OS produces "Only one copy of Firefox can be open at a time" error

### ISSUE THREAD

**Issue by markcellus** [filips123/PWAsForFirefox#144]
### Description

When attempting to open a PWA on Mac OS, I get a dialog that says "A copy of Firefox is already open. Only one copy of Firefox can be open at a time."

<img width="444" alt="Screen Shot 2022-04-18 at 10 02 41 AM" src="https://user-images.githubusercontent.com/1446916/163819351-28761dd1-9d39-4c2a-971d-c02ed0c6e6b9.png">

### Steps to Reproduce

1. Install a few PWAs
1. Open default browser Firefox
2. Open an installed PWA after searching for it using Apple's spotlight

### Additional Information

This seems to happen when there is already the default browser and at least 1 PWA open. But seems to keep happening with the same PWAs (e.g. Google Calendar). Other PWAs seem to work.

### Environment

* Operating system: Mac Monterey 12.2.1
* System architecture:
* Desktop environment: 
* Installation method: 
* PWAsForFirefox extension version: 1.4.0
* PWAsForFirefox native version: 1.4.0
* Firefox version: 99.0.1

**Comment by filips123** [comment]
Sorry for late reply, but what happens if you install each of those PWAs into a different profile?

**Comment by filips123** [comment]
I think this may be fixed in 2.0.0, after running "update web apps" from the extension settings.
