### ISSUE TITLE
Trying to launch site give permission denied

### ISSUE THREAD

**Issue by wisemonkey** [filips123/PWAsForFirefox#149]
### Description

I created site using command line, which was successful and I can browse it in my application list.
However launching site with ID gives `[ERROR] Permission denied (os error 13)`

* Operating system: PureOS
* System architecture: ARM 64
* Desktop environment: phosh
* Installation method: deb
* PWAsForFirefox extension version: 
* PWAsForFirefox native version: 1.4.0
* Firefox version: 91.8.0esr

**Comment by filips123** [comment]
Can you provide a full log? Check [#4 on this page](https://github.com/filips123/PWAsForFirefox/wiki/Troubleshooting) for details how to obtain it.

Also, please check if Firefox runtime (`~/.local/share/firefoxpwa/runtime/firefox`) has executable permission and the config file (`~/.local/share/firefoxpwa/config.json`) has read and write permissions.

**Comment by wisemonkey** [comment]
I've made sure config.json has permissions 666.
Created empty file DEBUG under .local/share/firefoxpwa, this doesn't create any new log files and firefoxpwa.log is empty.
I still see `Permission denied (os error 13)`

**Comment by filips123** [comment]
Does the program display any other messages before that error?

**Comment by tubbadu** [comment]
> Does the program display any other messages before that error?

```
$ /usr/bin/firefoxpwa site launch 01G53Y6P4G9DH6H8JHF7ZB53B7
11:45:17 [INFO] Launching the site
11:45:17 [ERROR] Permission denied (os error 13)
```

I tried running as root but `11:46:46 [ERROR] Site does not exist`

**Comment by filips123** [comment]
This error probably happens when `firefoxpwa` tries to launch `firefox`. Make sure `~/.local/share/firefoxpwa/runtime/firefox` (and probably other files in that directory) has executable and read permissions. Also check permissions of `/use/share/firefoxpwa` and `~/.local/share/firefoxpwa`.

It is normal that launching as root does not find the site, because they are stored per-user.

**Comment by tubbadu** [comment]
> This error probably happens when `firefoxpwa` tries to launch `firefox`. Make sure `~/.local/share/firefoxpwa/runtime/firefox` (and probably other files in that directory) has executable and read permissions. Also check permissions of `/use/share/firefoxpwa` and `~/.local/share/firefoxpwa`.
> 
> It is normal that launching as root does not find the site, because they are stored per-user.

that was the problem! I removed the folder `~/.local/share/firefoxpwa`, uninstalled `firefoxpwa`, and then reinstalled it again, and now it works perfectly!
