### ISSUE TITLE
[BUG] PWAs do not launch with the latest version [1.4.1]

### ISSUE THREAD

**Issue by IceDBorn** [filips123/PWAsForFirefox#157]
### Description
The PWAs do not launch

### Steps to Reproduce

1. Install a PWA
2. Launch the PWA

### Additional Information
This is the error I'm getting trying to run a site through the terminal:
` firefoxpwa site launch 01G4GVZPZY5D0574VG2BCMNAQQ`
`###!!! [Parent][DispatchAsyncMessage] Error: PBackgroundIDBFactory::Msg_PBackgroundIDBFactoryRequestConstructor
Value error: message was deserialized, but contained an illegal value`

### Affected Websites

All

### Environment

* Operating system: Arch
* System architecture: 64 bit
* Desktop environment:  Gnome
* Installation method:  AUR
* PWAsForFirefox extension version: 1.4.0
* PWAsForFirefox native version: 1.4.1
* Firefox version: 101

**Comment by bdefore** [comment]
since updating Firefox to 101 via yay on a manjaro sway machine, i'm no longer able to launch FirefoxPWA sites. `firefoxpwa site launch $SITEID` just opens an empty window.

i believe the FirefoxPWA team needs to update the extension to 1.4.1. if i open the extension i receive a warning 'this extension is outdated' which gives me a link to https://addons.mozilla.org/firefox/addon/pwas-for-firefox/ but only 1.4.0 is available there.

**Comment by IceDBorn** [comment]
@bdefore At least you're getting a window

**Comment by filips123** [comment]
It seems my fix in 1.4.1 isn't working properly (at least on Linux). I will try to fix it soon. Until then, you should probably roll back to PWAsForFirefox 1.4.0 and Firefox 100.0.

**Comment by Marius8** [comment]
same issue on Windows, instead of the PWA window for the site, i get the FF101 startscreen..
mabe related: in the addon store, the PWA addon is still 1.4.0

**Comment by filips123** [comment]
I've just released [v1.4.2](https://github.com/filips123/PWAsForFirefox/releases/tag/v1.4.2) which should (hopefully) properly fix the issue. It should become available in around half an hour, although Winget and Homebrew might take a bit longer. Note that the extension might still show that warning until Mozilla approves the new release.

**Comment by Marius8** [comment]
can confirm, with 1.4.2, at least on Windows, it works now

**Comment by ralphocdol** [comment]
I confirm that 1.4.2 works on linux (Manjaro Qonos 21.2.6).

**Comment by InDoubt** [comment]
Thank you!
The installation process took a lot of time and had to start it twice as it seemed to stall (brew upgrade firefoxpwa), but finally is up and running again.
BTW.: any idea why my antivirus stop the installation of: "Threat deleted  /  Name: Trojan.Mac.Generic.109856  / File name: p2_muti.o".....twice?

V.1.4.2 is running happily in:
iMac 27" i7 mid 2010
HighSierra
FF 101


![Screen Shot 2022-06-04 at 9 18 21 AM](https://user-images.githubusercontent.com/17437998/172027922-e5d04c4d-61ad-49d2-aaa3-57c8f5bb25bf.jpg)

**Comment by filips123** [comment]
> The installation process took a lot of time

That's because macOS High Sierra is not supported by Homebrew bottles anymore so it had to compile the whole program from source.

I'm not sure why it stalled and why antivirus triggered that message. File `p12_mutl.o` is part of OpenSSL, so it was probably some false positive.

**Comment by InDoubt** [comment]
Thank you very much for the answer, filips
Thank you for the explanations.
I recognized my poor 12 years old Mac has a lot of limitations, but didn't realized Homebrew could be affected too.
I can relax about that BD notification.
Thanks for developing this feature. It was something for which I was wishing for a long time, and now is a staple on my desktop.
🤗
