### ISSUE TITLE
Set titlebar colour for PWAs that don't specify one

### ISSUE THREAD

**Issue by taprobane99** [filips123/PWAsForFirefox#161]
This is really two parts:

Some PWAs have a nice coloured titlebar e.g. Simplenote.

1. Microsoft Teams 'PWA' on Edge has a purple titlebar, but FFox doesn't seem to recognise it as a PWA so its grey coloured
4. Websites without a PWA (e.g. Evernote) it would be nice to set my own titlebar colour e.g. green

Are either of these possible to implement?

**Comment by filips123** [comment]
I think it should be possible and I may implement it in the future. Until then, you can use an addon such as [VivaldiFox](https://addons.mozilla.org/firefox/addon/vivaldifox/) (and I think there are also some other similar addons) to do this. Just make sure you disable "Allow web apps to override a theme color" in Firefox settings and enable "Apply theme color" for Frame in VivaldiFox.

**Comment by filips123** [comment]
Also, I'll close this issue as it's pretty similar to #96.

**Comment by taprobane99** [comment]
Thanks, this works great - see screenshot! Although vivaldifox is a bit of overkill as I just need to change the titlebar. If you do implement it, it seems the 'white bakground for pageicon' option is also important, otherwise the icons look odd.
![canvas(1)](https://user-images.githubusercontent.com/57266492/172025080-7b88ed10-df64-4431-89ab-50178bc9d501.png)
