### ISSUE TITLE
Cannot install Facebook with manifest enabled

### ISSUE THREAD

**Issue by senolfndk** [filips123/PWAsForFirefox#174]
some sites are not loading, for example facebook is not loading

https://user-images.githubusercontent.com/52818836/175989117-115254ef-584e-474c-99f6-9d17be9d8c12.mp4

**Comment by senolfndk** [comment]
I turn off the notification but it still won't load

https://user-images.githubusercontent.com/52818836/176077532-90a61f50-3b36-4efb-a72a-933d6bb55024.mp4

**Comment by filips123** [comment]
No, you need to uncheck "Use the manifest for determining app properties" in the extension popup. Sorry if I wasn't clear enough.

**Comment by senolfndk** [comment]
where exactly is it? can you post a picture?

**Comment by filips123** [comment]
![slika](https://user-images.githubusercontent.com/16626308/176139630-66c75a24-ef28-4b50-815a-3c0b2b863744.png)

The marked checkbox needs to be disabled/unchecked.

**Comment by senolfndk** [comment]
okay, done
