### ISSUE TITLE
FR: Installation without admin rights

### ISSUE THREAD

**Issue by thehotery** [filips123/PWAsForFirefox#178]
Installation without admin rights on windows. Is it possible?  It espacially looks strange when browser itself dont require it (and many other software today)

**Comment by filips123** [comment]
It is possible, but not very easy as you will have to change source code a bit and compile it. See #111 for details.

I will try to implement better support for per-user installs (#129) in the future.

**Comment by filips123** [comment]
I will close this as it's duplicate of #129.
