### ISSUE TITLE
Spotify not installing error 10013 when using 'Use the manifest for determining app properties'

### ISSUE THREAD

**Issue by Rexadev** [filips123/PWAsForFirefox#179]
### Affected Websites

* ... https://open.spotify.com/

### Environment

* Operating system: Windows
* System architecture: x64 
* Desktop environment: 
* Installation method: 
* PWAsForFirefox extension version: 1.4.2
* PWAsForFirefox native version: 102.0.1 Release x64 Windows
* Firefox version: 102.0.1 Release

``
Failed to download PWA manifest: error sending request for url (https://open.spotifycdn.com/cdn/generated/manifest-web-player.8e800d3e.json): error trying to connect: tcp connect error: An attempt was made to access a socket in a way forbidden by its access permissions. (os error 10013): error trying to connect: tcp connect error: An attempt was made to access a socket in a way forbidden by its access permissions. (os error 10013): tcp connect error: An attempt was made to access a socket in a way forbidden by its access permissions. (os error 10013): An attempt was made to access a socket in a way forbidden by its access permissions. (os error 10013)
``

When I am not using 'Use the manifest for determining app properties' pinned PWA doesn't have Icon.

**Comment by filips123** [comment]
I think `An attempt was made to access a socket in a way forbidden by its access permissions. (os error 10013)` means that access to Spotify was blocked by firewall or antivirus. Do you have any antivirus other than Windows/Microsoft Defender, is your computer part of work domain, and do you have any internet filters enabled?

Maybe you can fix this if you explicitly allow `firefoxpwa.exe` and `firefoxpwa-connector.exe` to access the network. If you only have Windows Defender, follow the instructions [here](https://www.techinpost.com/an-attempt-was-made-to-access-a-socket-in-a-way-forbidden-by-its-access-permissions/) under "3. Allowing Application to Run through Windows Firewall". If `firefoxpwa.exe` and `firefoxpwa-connector.exe` are not listed there, click on "Allow another program" and add `C:\Program Files\FirefoxPWA\firefoxpwa.exe` and `C:\Program Files\FirefoxPWA\firefoxpwa-connector.exe`. If you have other antivirus, check how you can exclude a program from its firewall.

Also check if you have any internet filters enabled and if Spotify is blocked somewhere.
