### ISSUE TITLE
Improve style on macOS

### ISSUE THREAD

**Issue by mantou132** [filips123/PWAsForFirefox#182]
### Problem Description
Under MacOS, the title bar of the PWA does not look very beautiful

<img width="1260" alt="Screen Shot 2022-07-23 at 22 16 08" src="https://user-images.githubusercontent.com/3841872/180608902-e3db5833-68c3-4461-8c28-f249c325aec1.png">

### Proposed Solution

Imitation of chrome PWA

**Comment by black7375** [comment]
Just Info) To write a CSS that targets a specific operating system. https://github.com/black7375/Firefox-UI-Fix/issues/331#issuecomment-1037020725

v99 above firefox: https://github.com/mozilla/gecko-dev/commit/5fed8de04b3de8bb7a213deb37150af18d0b3314#diff-314c90db7a8ea5667e97a1ff5079d02192246d424244fc9dcebd568f3e1c87e7
```css
@media (-moz-platform: linux) {
}

@media (-moz-platform: macos) {
}

@media (-moz-platform: windows) {
}

@media (-moz-platform: windows-win7) {
}

@media (-moz-platform: windows-win8) {
}

@media (-moz-platform: windows-win10) {
}
```

v99 below firefox:
```css
@media (-moz-gtk-csd-available) {
  /* Linux */
}

@supports -moz-bool-pref("layout.css.osx-font-smoothing.enabled") {
  /* Mac */
}

@media (-moz-platform: windows-win7) {
}

@media (-moz-platform: windows-win8) {
}

@media (-moz-platform: windows-win10) {
}
```

**Comment by filips123** [comment]
Which changes exactly do you have in mind? I guess centering the title and removing that gap in the right corner? Other than that, Firefox and Chrome PWAs look pretty similar to me.

**Comment by black7375** [comment]
IMO, drag space(gap) should be located in the left corner.
