### ISSUE TITLE
Nextcloud mail app hangs periodically

### ISSUE THREAD

**Issue by thstyl2000** [filips123/PWAsForFirefox#183]
### Description

Using the nextcloud mail app results in periodic hangs where the pwa utilizes 100%cpu.

### Steps to Reproduce

1. Go to your nextcloud pwa
2. Click on 'mail'
3. Read/write/move etc emails.
4. PWA hangs with the message "This page is slowing down firefox"

### Additional Information

The app wants to periodically download avatars for all known email addresses from the server, which results in a large number of GET requests that fail with 404. The hang occurs when such a request coincides with a mailbox sync request. Apparently this is not a problem in a normal browser (the requests can be parallelized?) but a dealbreaker in the PWA.

EDIT: Here's more info about the 404 responses:
[https://github.com/nextcloud/server/issues/26793#issuecomment-874048839](url)

### Affected Websites

* nextcloud

### Environment

* Operating system: Kubuntu 22.04
* System architecture: x86_64 GNU/Linux
* Desktop environment: KDE Plasma 5.24.4
* Installation method: deb
* PWAsForFirefox extension version: 1.4.2
* PWAsForFirefox native version: 1.4.2
* Firefox version: 103.0

**Comment by filips123** [comment]
I don't know why this would affect performance in the PWA but not in a normal Firefox. Can you please make a performance profile on nexcloud app both in PWA and in normal Firefox when those requests occur?

To enable the profiler button:
1. Go to the Firefox customize page (Firefox menu -> More tools -> Customize toolbar).
2. If you don't see a Profiler button on the Customize page,
    * Go to the [Firefox Profiler](https://profiler.firefox.com/) website and enable it. From PWA, you can press `F6` to enter the URL.
    * For PWA only, right-click on the button that should appear next to the address bar, click "Remove from Toolbar" and then go back to step 1. (This is needed because otherwise a profiler is added to a wrong toolbar that is hidden by default)
3. Drag a Profiler button to your toolbar.

To run a profiler:
1. You need to be on nextcloud mail website. If possible, you should start a profiler as soon as nextcloud starts sending those requests, maybe even a bit earlier.
2. Click on the arrow next to the profiler button.
5. Select "Firefox" as Settings and click "Start Recording".
6. After some time (after you have observed the hang and requests end), click again on the button.
7. On a website that opens, click "Upload local profile" and send me the link. You should also check "Include resource URLs and paths" so I can see requests, but you can leave it unchecked if you would prefer not to share them.

Also, does the same thing happen if you disable all extensions in your PWA or create a fresh nextcloud mail PWA?

**Comment by filips123** [comment]
The profile shows a lot of JS activity in Nextcloud Mail scripts that seem to hang Firefox (this is shown in the profile with the red line). This mainly corresponds to [`syncEnvelopes`](https://github.com/nextcloud/mail/blob/db1966f72b0d6e9ec0ea5ef7b27b946b1bb60971/src/store/actions.js#L594-L641), which eventually calls [`addEnvelope`](https://github.com/nextcloud/mail/blob/db1966f72b0d6e9ec0ea5ef7b27b946b1bb60971/src/store/mutations.js#L223-L251). In your profile, this function has been more than 60000 times and it took (in total) more than 70 seconds. There are also some other quite slow functions, but I think this is the main culprit.

However, I still don't know why this function is so slow and why only in PWAs. Maybe you have a lot of emails and it takes a long to process them, but that doesn't explain why it only happens in PWAs. I think the only code in PWAsForFirefox that somewhat interacts with the website (and could possibly affect performance) is [to sync website title and icon](https://github.com/filips123/PWAsForFirefox/blob/main/native/userchrome/profile/chrome/pwa/content/browser.jsm#L69-L102), but it does not seam related to this problem.

If you are using your system-provided Firefox as a normal browser, can you also try if this happens in the Firefox version that you download [directly from the Mozilla website](https://www.mozilla.org/firefox/all/)? Maybe Kubuntu's Firefox is somehow different from normal Firefox (which PWAsForFirefox uses as a base) and is more optimized. I highly doubt this, but it's worth checking.

Unfortunately, I don't know what else to do, at least for now.

**Comment by thstyl2000** [comment]
After working longer with the standard version of Firefox, it appears that the problem is there too, so that's not a pwa bug but (most possibly) a nextcloud bug. So closing this anf refiling it at the nextcloud github. Thank you very much for your support!
