### ISSUE TITLE
“Copy URL of current page” context menu

### ISSUE THREAD

**Issue by mrd77** [filips123/PWAsForFirefox#187]
### Problem Description

I sometimes find myself wanting to copy the link of the site I'm currently on. With the address bar disabled, this is a non-trivial endeavor.

### Proposed Solution

Add a context-menu entry to “Copy URL of current page”

**Comment by filips123** [comment]
You can use "Copy Link" widget from the Firefox customize page.

**Comment by mrd77** [comment]
Thanks a lot for the ad-hoc solution

**Comment by filips123** [comment]
I'll close this issue because I think context menu entry is not needed as copy link widget already exists.
