### ISSUE TITLE
Runtime patching breaks runtime on macOS 12.4

### ISSUE THREAD

**Issue by TitanNano** [filips123/PWAsForFirefox#188]
### Description

After updating to v2.0.1 I noticed that the patched Firefox runtime was no longer able to start.

### Steps to Reproduce

1. install runtime
2. launch a site

### Additional Information

I'm not quite sure what caused this, as I only noticed it after updating to v2.0.1. When reverting the runtime patch function back to its v1.4.2 version, it still breaks the runtime, though. This might not be related to v2.0.1 at all and could be a change in macOS.

### Environment

* Operating system: macOS 12.4
* System architecture: M1 Pro / ARM
* Installation method: cargo make install
* PWAsForFirefox extension version: 2.0.1
* PWAsForFirefox native version: 2.0.1
* Firefox version: 103

**Comment by TitanNano** [comment]
I have a local patch that adds ad hoc signing to the Firefox runtime, which resolves the issue on my machine. I will have to do a bit more testing though to verify that this works with different system configurations as well.

**Comment by filips123** [comment]
Ok, thanks for help. Unfortunately, I cannot do much myself, as I only have macOS 10 in a VM, and it works there for me.
