### ISSUE TITLE
AniMix Play has wrong .ico even with app manifest

### ISSUE THREAD

**Issue by pc-v2** [filips123/PWAsForFirefox#189]
### Description

it does not show error here
![image](https://user-images.githubusercontent.com/58063311/182323433-9c90ae54-1f96-47b4-b5a8-d730958781ae.png)
but in start menu it looks like this 
![image](https://user-images.githubusercontent.com/58063311/182323519-f9716170-06d4-4dc9-bce9-c13dea160300.png)

### Steps to Reproduce

1. Create AniMix Play as PWA
2. Open Start Menu 
3. See AniMix Play shortcut 

### Affected Websites

https://animixplay.to

### Environment

* Operating system: Windows 11 22621.317
* System architecture: amd64
* Installation method: MSI
* PWAsForFirefox extension version: 2.0.1
* PWAsForFirefox native version: 2.0.1
* Firefox version: 103.0.1

**Comment by filips123** [comment]
Icon requests for animixplay.to hit Cloudflare's bot protection (CAPTCHA). I will check if if can work around that somehow.

**Comment by filips123** [comment]
I've just tested this again, but it seems to work now. Maybe something has changed on their end to stop blocking icon requests.
