### ISSUE TITLE
Unable to access site permissions panel

### ISSUE THREAD

**Issue by ShowMeBillyJo** [filips123/PWAsForFirefox#194]
### Description

Unable to access site permissions panel

### Steps to Reproduce

1. Click the Site Permissions button in the mini-toolbar
2. Observe that nothing happens

![image](https://user-images.githubusercontent.com/179590/182997199-2a18d31f-4f62-4a6f-9db2-addf1fe83545.png)

### Additional Information

https://support.mozilla.org/en-US/kb/site-permissions-panel

### Affected Websites

* So far only confirmed on messages.google.com

### Environment

* Operating system: Windows 10 21H2 19044.1865
* System architecture: x64
* Installation method: Chocolatey, Firefox Addons site
* PWAsForFirefox extension version: 2.0.1
* PWAsForFirefox native version: 1.4.2
* Firefox version: 103.0.1

**Comment by filips123** [comment]
Can you update native package to 2.0.1 and check again?

**Comment by ShowMeBillyJo** [comment]
That resolves the issue, thank you! I thought it looked a little suspicious as I was entering the bug. I appreciate you taking the time to check on it.
