### ISSUE TITLE
The checkboxes in in the edit menus for PWAs in the Extension, could be explained more clearly

### ISSUE THREAD

**Issue by DanielSvindseth** [filips123/PWAsForFirefox#195]
### Description

Like the title says, I am unable to disable automatic icon updates.

### Steps to Reproduce

1. Click 'edit' on a PWA in the extension's menu
2. Scroll down and uncheck the box that says "Update web app icons"
3. Click 'edit' to apply changes
4. Go back to the main extension menu
5. Repeat step 1, and the checkbox should be toggled on again :/

### Affected Websites

All from what I can see

* ...
* ...

### Environment

* Operating system: Fedora 36
* System architecture: x86_64
* Desktop environment: Gnome 42 
* Installation method:  RPM
* PWAsForFirefox extension version: 2.0.1
* PWAsForFirefox native version: 2.0.1-1
* Firefox version: 102.0

**Comment by filips123** [comment]
This is expected. "Update web app icons" and "Update web app manifest" only determine if icons and manifest will be updated when you click the "Edit" button. They are not stored anywhere after the process has been finished, and icons and manifest are not automatically updated in any case.

I could probably add some tooltips to those checkboxes to make that more clear...

**Comment by DanielSvindseth** [comment]
Ah! That makes some sense.

Yeah maybe a tooltip or something similar could help people like me who doesn't understand that from the beginning.
