### ISSUE TITLE
displayURLBar is not respected when linksTarget is 3, rather than 2

### ISSUE THREAD

**Issue by desbest** [filips123/PWAsForFirefox#200]
### Description

When the user clicks on a hyperlink that is "out of range", if they have configured their settings so that `_blank` hyperlinks should open in a new window, their setting for making out of range hyperlinks open in a new window, that is not respected.

**Expected behaviour:** When clicking an external link that is out of range, the website should appear in a new window

**Actual behaviour:** The website replaces the existing web page to move to it within the same window, leaving the old web page behind.

**Why it's annoying:** Because if the user was filling out a form on amazon.com while expecting their external out of scope website that doesn't use the amazon.com domain name, to appear in a new window and it instead replaces the existing one, the user will lose their progress.

**How to mitigate the problem:** Change `linksTarget` from **3** to **2** so that external out of range links appear in a new tab instead of a new window.

### Steps to Reproduce

1. Go to `about:config`
2. Search for `firefoxpwa`
3. Make sure that `displayUrlBar` is **0**
4. Change `enableTabsMode` is **true**
5. Change `linksTarget` to **3**
6. [Go to this instagram profile](https://www.instagram.com/slowlyapp/) Press the F6 key.
7. Click the external link in their profile description leading to the Slowly website.

### Additional Information

![pwa for firefox bug](https://user-images.githubusercontent.com/1139316/184419056-e020c71d-5ea6-4052-97d9-3d8cd7cec742.png)

### Affected Websites

N/A
### Environment

* **Operating system:** Windows 10 21H1
* **System architecture:** 64 bit
* **Desktop environment:** N/A
* **Installation method:** MSI from github
* **PWAsForFirefox extension version:** 2.0.2
* **PWAsForFirefox native version:** 2.0.2
* **Firefox version:** 103.0.2

**Comment by filips123** [comment]
I'm not sure I understand this correctly... `displayUrlBar` only determines if the address bar will be snown, not if the website will open in a new window.

However, I have found that if `openOutOfScopeInDefaultBrowser` is enabled while `linksTarget` is set to `3` (open in a new tab), opening an out-of-scope website will still close the whole window, which is not intended and will be fixed. Was this what you meant?

If you wanted to only open out-of-scope URLs in a new window while opening others only in a new tab, this is unfortunately too hard to implement due to how the code currently works.

**Comment by desbest** [comment]
linksTarget is set to 3 so any new links should open in a new window. So why isn't it?

![firefox pwa wiki quote](https://user-images.githubusercontent.com/1139316/191447923-a337c1db-8085-4b39-aecc-b7b9bd673f29.png)


![firefox pwa settings](https://user-images.githubusercontent.com/1139316/191446811-8766d74c-65b4-4f35-b7c1-4b48a32a455d.png)

https://www.youtube.com/watch?v=tQJzBpyLDGg

**Comment by filips123** [comment]
Maybe it actually opens in a new tab, but you don't see it, as tabs mode appears to be disabled. Which is weird, as you have `firefoxpwa.enableTabsMode` enabled. Have you tried restarting your open web apps after setting both preferences?

**Comment by desbest** [comment]
It seems like I have to restart the PWA app, in order for the settings changes to take effect. But that wasn't the case months ago when I reported the bug.

**Comment by filips123** [comment]
Yes, some preferences require PWAs to be restarted, as dynamically applying all changes would be too complicated. I've added a notice about that to the wiki to make it more clear.
