### ISSUE TITLE
The extension isn't detecting the native app fsr and I have no idea why!

### ISSUE THREAD

**Issue by Hazem42** [filips123/PWAsForFirefox#201]
### Description

The extension isn't detecting the native app after updating to 2.0.2, I have "Visual C++ Redistributable" and the native app (the latest version) installed, when I click the extension icon it shows the setup page in the "Connector Installation" step

### Steps to Reproduce

1. I clicked on the extension after the update
2. A new tab appeared saying that the native app is outdated (2.0.1) and it's recommended to update to (2.0.2)  
3. I downloaded the update and installed it, then the extension just stopped working
4. I checked the downloaded apps from the control panel and I saw that the 2.0.1 version was still installed!
5. I deleted the 2.0.1 version but it still didn't work 

### Additional Information

I have no idea if this is related or not, but I have the "simple tab group" extension installed, I have some contained tabs, and I have my browser's security set to strict

### Summary

 
I just installed the new 2.0.2 update and everything stopped working

### Environment

* Operating system: Windows 10 Home 64-bit
* Installation method: MSI
* PWAsForFirefox extension version: 2.0.2
* PWAsForFirefox native version: 2.0.2
* Firefox version: 103.0.2 (64-bit)

**Comment by filips123** [comment]
Can you check if the native app is installed to `C:\Program Files\FirefoxPWA` or `%LOCALAPPDATA%\Programs\FirefoxPWA`, and if there are `firefoxpwa` registry keys in `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\NativeMessagingHosts` or `Computer\HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts` (you can check this with regedit)?

Also, please try to uninstall all your existing PWAsForFirefox native installations and install 2.0.2 again (this shouldn't affect your web apps).

**Comment by Hazem42** [comment]
> Can you check if the native app is installed to `C:\Program Files\FirefoxPWA` or `%LOCALAPPDATA%\Programs\FirefoxPWA`, 

It's not actually! I tried uninstalling and reinstalling, still doesn't exist, I restarted my PC, and still doesn't exist.
weird!

> and if there are `firefoxpwa` registry keys in `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\NativeMessagingHosts` or `Computer\HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts` (you can check this with regedit)?

Yes, there is, in both locations too!

![Screenshot (21)](https://user-images.githubusercontent.com/89294365/184544824-e8f06db9-0f00-40b6-98b0-8703e938e6e1.png)
![Screenshot (22)](https://user-images.githubusercontent.com/89294365/184544825-4238283b-1fdc-4c59-a9a4-e3ecb39a33b1.png)

**Comment by Hazem42** [comment]
### Update
I uninstalled again then deleted all the reg keys and installed again, and it seems to be working fine now!
Thank you so much for mentioning the reg keys <3

**Comment by filips123** [comment]
Upgrade from 1.4.2 to 2.0.2 worked fine for me, so I'm not sure why the problem occurred for you. I will close this issue, if anyone still has problems, try to uninstall PWAsForFirefox, remove those registry keys, and install it again.

**Comment by JaneValleyhasBtaken** [comment]
I had similar issue, and turns out it was because it was installed only for current users (In the past I always click 'install for all users')
