### ISSUE TITLE
Netflix, Disney+ and MyCanal can't play video if launched in the PWA but work well in firefox

### ISSUE THREAD

**Issue by shiipou** [filips123/PWAsForFirefox#202]
### Description

When I try to watch some movies in PWA, I simply can't.
I tried on Netflix, Disney+ and MyCanal but I can't play video if launched in the PWA.

### Steps to Reproduce

1. Go to [canalplus.com](https://www.canalplus.com)
2. Create the PWA
3. Login to your account in the PWA
4. Try to play any movies
5. See error `PERSO-6;Available playsets were found, but none are supported;undefined`

### Additional Information

![image](https://user-images.githubusercontent.com/38187238/184605040-27891e82-4fcc-4e66-81d3-da604e66a91a.png)

### Affected Websites

* Netflix
* Disney+
* MyCanal
* Probably any DRM content related 

### Environment

* Operating system: Linux Fedora
* System architecture: amd64
* Desktop environment:Gnome 42
* Installation method: RPM
* PWAsForFirefox extension version: 2.0.2
* PWAsForFirefox native version: firefoxpwa 2.0.2
* Firefox version: 103

**Comment by filips123** [comment]
Please check if DRM is enabled in PWA Firefox settings.

**Comment by shiipou** [comment]
> Please check if DRM is enabled in PWA Firefox settings.

DRM is enabled, Firefox in PWA ask me to enable it after the first launch of the profile I called `movies`.

**Comment by filips123** [comment]
Please download Firefox (tar.bz2) from [official Mozilla website](https://www.mozilla.org/firefox/all/#product-desktop-release) and check if the same error also happens there.

**Comment by shiipou** [comment]
> Please download Firefox (tar.bz2) from [official Mozilla website](https://www.mozilla.org/firefox/all/#product-desktop-release) and check if the same error also happens there.

That work with the official version (104)

![image](https://user-images.githubusercontent.com/38187238/187168223-0fcdd5f8-01c1-44af-95fd-a35f49a80248.png)

Thanks for the tips.
Idk what didn't work with fedora's one
