### ISSUE TITLE
Web Apps Just Opening Blank New Tabs

### ISSUE THREAD

**Issue by PetrikM** [filips123/PWAsForFirefox#206]
I have tried to get the bug reports for my issue, but I am not sure how. That could also be because it is simply not opening the PWA apps themselves.
Whenever I try to open an app I install (be it thru the start/desktop shortcut or the launcher in firefox) a new **firefox** window pops up with just a blank screen and new tab waiting for me to enter a web address. This happens for every web app I've installed, be it sites for my school, youtube, anything. I have tried uninstalling PWA and firefox and re-installing multiple times but I can't seem to figure it out.
If someone could help walk me through the process of getting the logs to aid troubleshooting I'd appreciate it, as I couldn't really find the about tab after pressing F12.

**Comment by filips123** [comment]
Which OS do you use? The process of getting logs is described in the step 4 on [this page](https://github.com/filips123/PWAsForFirefox/wiki/Troubleshooting).

**Comment by filips123** [comment]
I'll close this issue as I cannot do anything about it without logs and steps to reproduce it. If you still have the same issue, please provide logs and I'll reopen it.
