### ISSUE TITLE
Crash when allowing Microphone/Camera usage

### ISSUE THREAD

**Issue by bentuna** [filips123/PWAsForFirefox#207]
When a website within a PWA asks for permission to use your camera or microphone, and you allow it (doesn't matter if you select "remember descision"), the PWA crashes with the Error Details below.

### Steps to reproduce

1. Create a PWA from a website that asks for camera permission, i.e. https://meet.jit.si/
2. Run the PWA, make the website ask for permission
3. Click allow

### Mozilla Crash Reporter Details

AdapterVendorID: 0x106b
Add-ons: doh-rollout%40mozilla.org:2.0.0,formautofill%40mozilla.org:1.0.1,pictureinpicture%40mozilla.org:1.0.0,screenshots%40mozilla.org:39.0.1,webcompat%40mozilla.org:104.6.0,default-theme%40mozilla.org:1.3,addons-search-detection%40mozilla.com:2.0.0,google%40search.mozilla.org:1.2,wikipedia%40search.mozilla.org:1.1,bing%40search.mozilla.org:1.3,ddg%40search.mozilla.org:1.1,amazon%40search.mozilla.org:1.9
AvailablePhysicalMemory: 215941120
AvailableSwapMemory: 0
BackgroundTaskMode: 0
BuildID: 20220829141339
ContentSandboxCapable: 1
ContentSandboxLevel: 3
CrashTime: 1662289711
DOMFissionEnabled: 1
DOMIPCEnabled: 1
ExperimentalFeatures: devtools.inspector.compatibility.enabled
GraphicsNumRenderers: 1
HeadlessMode: 0
InstallTime: 1662279279
MacAvailableMemorySysctl: 75
MacMemoryPressure: Normal
MacMemoryPressureCriticalTime: Unset
MacMemoryPressureNormalTime: 1662289705
MacMemoryPressureSysctl: 1
MacMemoryPressureWarningTime: Unset
Notes: FP(D00-L1000-W00000000-T000) WR? WR+ GL Context? GL Context+ 
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
PurgeablePhysicalMemory: 21495808
RDDProcessStatus: Running
ReleaseChannel: release
SafeMode: 0
SecondsSinceLastCrash: 124
StartupCrash: 0
StartupTime: 1662289705
SubmittedFrom: Client
TelemetryEnvironment: {"build":{"applicationId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","applicationName":"Firefox","architecture":"aarch64","buildId":"20220829141339","version":"104.0.1","vendor":"Mozilla","displayVersion":"104.0.1","platformVersion":"104.0.1","xpcomAbi":"aarch64-gcc3","updaterAvailable":true},"partner":{"distributionId":"firefoxpwa","distributionVersion":"2.0.2","partnerId":null,"distributor":null,"distributorChannel":null,"partnerNames":[]},"system":{"memoryMB":8192,"virtualMaxMB":null,"cpu":{"extensions":["hasNEON"]},"os":{"name":"Darwin","version":"21.6.0","locale":"de-DE"},"hdd":{"profile":{"model":null,"revision":null,"type":null},"binary":{"model":null,"revision":null,"type":null},"system":{"model":null,"revision":null,"type":null}},"gfx":{"D2DEnabled":null,"DWriteEnabled":null,"ContentBackend":"Skia","Headless":false,"EmbeddedInFirefoxReality":null,"adapters":[{"description":null,"vendorID":"0x106b","deviceID":null,"subsysID":null,"RAM":0,"driver":null,"driverVendor":null,"driverVersion":null,"driverDate":null,"GPUActive":true}],"monitors":[{"screenWidth":2880,"screenHeight":1800,"scale":2}],"features":{"compositor":"webrender","hwCompositing":{"status":"available"},"gpuProcess":{"status":"unused"},"wrQualified":{"status":"available"},"webrender":{"status":"available"},"wrCompositor":{"status":"available"},"wrSoftware":{"status":"available"},"openglCompositing":{"status":"available"},"omtp":{"status":"unused"}}},"appleModelId":"MacBookAir10,1","hasWinPackageId":null},"settings":{"blocklistEnabled":true,"e10sEnabled":true,"e10sMultiProcesses":8,"fissionEnabled":true,"telemetryEnabled":false,"locale":"en-US","intl":{"requestedLocales":["en-US"],"availableLocales":["en-US"],"appLocales":["en-US"],"systemLocales":["de-DE"],"regionalPrefsLocales":["de-DE"],"acceptLanguages":["en-US","en"]},"update":{"channel":"release","enabled":true,"autoDownload":true,"background":true},"userPrefs":{"browser.fixup.alternate.enabled":false,"browser.search.region":"DE","browser.search.widget.inNavBar":false,"browser.urlbar.autoFill":true,"browser.urlbar.autoFill.adaptiveHistory.enabled":false,"browser.urlbar.dnsResolveSingleWordsAfterSearch":0,"browser.urlbar.quicksuggest.dataCollection.enabled":false,"browser.urlbar.suggest.quicksuggest.nonsponsored":false,"browser.urlbar.suggest.quicksuggest.sponsored":false,"browser.urlbar.suggest.bestmatch":true,"general.config.filename":"<set>","network.trr.strict_native_fallback":false,"widget.content.allow-gtk-dark-theme":false,"widget.content.gtk-high-contrast.enabled":true},"sandbox":{"effectiveContentProcessLevel":3,"contentWin32kLockdownState":3},"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":false,"defaultSearchEngine":"google-b-d","defaultSearchEngineData":{"loadPath":"[other]addEngineWithDetails:google@search.mozilla.org","name":"Google","origin":"default","submissionURL":"https://www.google.com/search?client=firefox-b-d&q="}},"profile":{"creationDate":19239,"firstUseDate":19239},"addons":{"activeAddons":{"doh-rollout@mozilla.org":{"version":"2.0.0","scope":1,"type":"extension","updateDay":19233,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"This used to be a Mozilla add-on that supported the roll-out of DoH, but now only exists as a stub t","name":"DoH Roll-Out","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19233},"formautofill@mozilla.org":{"version":"1.0.1","scope":1,"type":"extension","updateDay":19233,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Form Autofill","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19233},"pictureinpicture@mozilla.org":{"version":"1.0.0","scope":1,"type":"extension","updateDay":19233,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Fixes for web compatibility with Picture-in-Picture","name":"Picture-In-Picture","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19233},"screenshots@mozilla.org":{"version":"39.0.1","scope":1,"type":"extension","updateDay":19233,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Take clips and screenshots from the Web and save them temporarily or permanently.","name":"Firefox Screenshots","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19233},"webcompat@mozilla.org":{"version":"104.6.0","scope":1,"type":"extension","updateDay":19233,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Urgent post-release fixes for web compatibility.","name":"Web Compatibility Interventions","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19233}},"theme":{"id":"default-theme@mozilla.org","blocklisted":false,"description":"Follow the operating system setting for buttons, menus, and windows.","name":"System theme — auto","userDisabled":false,"appDisabled":false,"version":"1.3","scope":4,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19239,"updateDay":19239},"activeGMPlugins":{"gmp-gmpopenh264":{"version":null,"userDisabled":false,"applyBackgroundUpdates":1},"gmp-widevinecdm":{"version":null,"userDisabled":false,"applyBackgroundUpdates":1}}},"experiments":{"tcp-rollout-phase-iii-tcp-on-by-default-for-50-existing-release-profiles":{"branch":"control","type":"nimbus-nimbus","enrollmentId":"d55c2255-5835-4ea5-8edf-e73ae78cd2e4"}}}
Throttleable: 1
TotalPhysicalMemory: 8589934592
URL: https://meet.jit.si/hello
UptimeTS: 6.541666666666666
UtilityProcessStatus: Running
Vendor: Mozilla
Version: 104.0.1
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.

**Comment by filips123** [comment]
Which OS do you use? It works fine for me on Windows 10 and Ubuntu 22.04... If you're on Linux, please download normal Firefox from the [Mozilla website](https://www.mozilla.org/firefox/all) and check if the same problem happens in that version.

**Comment by bentuna** [comment]
Hello,

I am on macOS 12.5.1 Monterey and Firefox 104.0.1

Best regards,
Benjamin

**Comment by filips123** [comment]
I was able to reproduce it on macOS VM and I think it happens because of some missing permissions in `Info.plist` ([some bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1742137)). I'll try to fix this next week.

**Comment by bentuna** [comment]
Oh really nice, thank you for the quick check and reply!
I am doing a setup of Nextcloud at a customers this week, so do you think you will fix it until wednesday? Bc then I would not install Chrome on their machines but firefox instead to use a PWA for Nextcloud there.

Best regards,
Benjamin

**Comment by filips123** [comment]
I tried adding `NSCameraUsageDescription` and `NSMicrophoneUsageDescription` to the web app's `Info.plist`, but it still doesn't work. Web app doesn't crash anymore, but macOS never displays a microphone access prompt and Jitsi Meet logs the error "Failed to create local tracks Array [ "audio" ]" to the console.

Maybe it has to do something with my VM, so you can try adding the following lines before the last `</dict>` in your `~/Applications/YOUR WEB APP.app/Contents/Info.plist`:

```xml
        <key>NSCameraUsageDescription</key>
        <string>Only sites you allow within Firefox will be able to use the camera.</string>
        <key>NSMicrophoneUsageDescription</key>
        <string>Only sites you allow within Firefox will be able to use the microphone.</string>
```

If that works, I can release this in a new version soon. If it doesn't, I'm not sure how to fix it... @TitanNano Sorry to bother you, but as you have some more macOS experience, could you please look into this?

**Comment by bentuna** [comment]
Hi,

thank you - I tried, but unfortunately it is happening the same crash when allowing microphone/camera.

Best regards,
Benjamin

**Comment by TitanNano** [comment]
@filips123 I reproduced this with Google meet and once I include your patch, Firefox no longer crashes and both camera and microphone appear to work fine.

**Comment by filips123** [comment]
Interesting... Then I will release that fix, and if it doesn't work, the issue can still be properly fixed later.

**Comment by filips123** [comment]
I released 2.0.3 with that fix. @bentuna After updating the native package, close opened web apps, update your web apps from the extension settings, maybe reboot your computer, and try again.

**Comment by bentuna** [comment]
Thank you su much, I got it to work nor with your steps!

Unfortunately, I have the problem that the 1Password-Extension is not working fully functional in the Web App. It is not being unlocked with Touch ID when the main App of 1Passwort is gettin unlocked. You always have to type the master password. Maybe you have a tip for that?

Best regards,
Benjamin


—

**Comment by filips123** [comment]
Unfortunately I'm not sure why that doesn't work, and I'm not familiar with how 1Password uses Touch ID.

**Comment by aiyagari** [comment]
@filips123 
I would like to reopen this as it is occurring again on Google Meet.  I am a new user of this extension on Mac OS 13.6.  Installing Google Meet into a new profile and trying to turn on Microphone and Camera causes it to crash.

```
AdapterDeviceID: 0x3e9b
AdapterVendorID: 0x8086
Add-ons: formautofill%40mozilla.org:1.0.1,pictureinpicture%40mozilla.org:1.0.0,screenshots%40mozilla.org:39.0.1,webcompat%40mozilla.org:118.0.0,default-theme%40mozilla.org:1.3,addons-search-detection%40mozilla.com:2.0.0,google%40search.mozilla.org:1.4,amazondotcom%40search.mozilla.org:1.6,wikipedia%40search.mozilla.org:1.3,bing%40search.mozilla.org:1.6,ddg%40search.mozilla.org:1.4,ebay%40search.mozilla.org:1.4
AvailablePhysicalMemory: 37773312
AvailableSwapMemory: 1110704128
BackgroundTaskMode: 0
BuildID: 20230927232528
ContentSandboxCapable: 1
ContentSandboxLevel: 3
CrashTime: 1696412391
DOMFissionEnabled: 1
DOMIPCEnabled: 1
EMCheckCompatibility: true
ExperimentalFeatures: devtools.inspector.compatibility.enabled
GpuSandboxLevel: 0
GraphicsNumRenderers: 1
HeadlessMode: 0
InstallTime: 1696379109
LastStartupWasCrash: 0
MacAvailableMemorySysctl: 75
MacMemoryPressure: Normal
MacMemoryPressureCriticalTime: Unset
MacMemoryPressureNormalTime: 1696412349
MacMemoryPressureSysctl: 1
MacMemoryPressureWarningTime: Unset
Notes: FP(D00-L1000-W0000000-T010) WR? WR+ GL Context? GL Context+ WebGL? WebGL+ 
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
PurgeablePhysicalMemory: 104812544
RDDProcessStatus: Running
ReleaseChannel: release
SafeMode: 0
SecondsSinceLastCrash: 837
StartupCacheValid: 1
StartupCrash: 0
StartupTime: 1696412349
SubmittedFrom: Client
TelemetryEnvironment: {"build":{"applicationId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","applicationName":"Firefox","architecture":"x86-64","buildId":"20230927232528","version":"118.0.1","vendor":"Mozilla","displayVersion":"118.0.1","platformVersion":"118.0.1","xpcomAbi":"x86_64-gcc3","updaterAvailable":true},"partner":{"distributionId":"firefoxpwa","distributionVersion":"2.8.0","partnerId":null,"distributor":null,"distributorChannel":null,"partnerNames":[]},"system":{"memoryMB":32768,"virtualMaxMB":null,"cpu":{"extensions":["hasMMX","hasSSE","hasSSE2","hasSSE3","hasSSSE3","hasSSE4_1","hasSSE4_2","hasAVX","hasAVX2","hasAES"]},"os":{"name":"Darwin","version":"22.6.0","locale":"en-US"},"hdd":{"profile":{"model":null,"revision":null,"type":null},"binary":{"model":null,"revision":null,"type":null},"system":{"model":null,"revision":null,"type":null}},"gfx":{"D2DEnabled":null,"DWriteEnabled":null,"ContentBackend":"Skia","Headless":false,"EmbeddedInFirefoxReality":null,"TargetFrameRate":60,"adapters":[{"description":null,"vendorID":"0x8086","deviceID":"0x3e9b","subsysID":null,"RAM":0,"driver":null,"driverVendor":null,"driverVersion":null,"driverDate":null,"GPUActive":true},{"description":null,"vendorID":"0x1002","deviceID":"0x7340","subsysID":null,"RAM":0,"driver":null,"driverVendor":null,"driverVersion":null,"driverDate":null,"GPUActive":null}],"monitors":[{"screenWidth":3840,"screenHeight":2160,"scale":1},{"screenWidth":4096,"screenHeight":2560,"scale":2}],"features":{"compositor":"webrender","hwCompositing":{"status":"available"},"gpuProcess":{"status":"unused"},"webrender":{"status":"available"},"wrCompositor":{"status":"available"},"openglCompositing":{"status":"available"},"omtp":{"status":"unused"}}},"appleModelId":"MacBookPro16,1","hasWinPackageId":null},"settings":{"blocklistEnabled":true,"e10sEnabled":true,"e10sMultiProcesses":8,"fissionEnabled":true,"telemetryEnabled":false,"locale":"en-US","intl":{"requestedLocales":["en-US"],"availableLocales":["en-US"],"appLocales":["en-US"],"systemLocales":["en-US"],"regionalPrefsLocales":["en-US"],"acceptLanguages":["en-US","en"]},"update":{"channel":"release","enabled":true,"autoDownload":true,"background":true},"userPrefs":{"app.shield.optoutstudies.enabled":false,"browser.fixup.alternate.enabled":false,"browser.search.region":"US","browser.search.widget.inNavBar":false,"browser.urlbar.autoFill":true,"browser.urlbar.autoFill.adaptiveHistory.enabled":false,"browser.urlbar.dnsResolveSingleWordsAfterSearch":0,"browser.urlbar.quicksuggest.dataCollection.enabled":false,"browser.urlbar.suggest.quicksuggest.nonsponsored":true,"browser.urlbar.suggest.quicksuggest.sponsored":true,"browser.urlbar.suggest.bestmatch":true,"general.config.filename":"<set>","media.gmp-gmpopenh264.lastInstallStart":1696411481,"media.gmp-gmpopenh264.lastDownload":1696411481,"media.gmp-gmpopenh264.lastUpdate":1696411481,"media.gmp-widevinecdm.lastInstallStart":1696411481,"media.gmp-widevinecdm.lastDownload":1696411483,"media.gmp-widevinecdm.lastUpdate":1696411483,"network.trr.strict_native_fallback":false,"widget.content.gtk-high-contrast.enabled":true},"sandbox":{"effectiveContentProcessLevel":3,"contentWin32kLockdownState":3},"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":false,"defaultSearchEngine":"google-b-1-d","defaultSearchEngineData":{"loadPath":"[addon]google@search.mozilla.org","name":"Google","origin":"default","submissionURL":"https://www.google.com/search?client=firefox-b-1-d&q="}},"profile":{"creationDate":19634,"firstUseDate":19634},"addons":{"activeAddons":{"formautofill@mozilla.org":{"version":"1.0.1","scope":1,"type":"extension","updateDay":19628,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Form Autofill","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19628,"quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false},"pictureinpicture@mozilla.org":{"version":"1.0.0","scope":1,"type":"extension","updateDay":19628,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Fixes for web compatibility with Picture-in-Picture","name":"Picture-In-Picture","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19628,"quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false},"screenshots@mozilla.org":{"version":"39.0.1","scope":1,"type":"extension","updateDay":19628,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Take clips and screenshots from the Web and save them temporarily or permanently.","name":"Firefox Screenshots","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19628,"quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false},"webcompat@mozilla.org":{"version":"118.0.0","scope":1,"type":"extension","updateDay":19628,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Urgent post-release fixes for web compatibility.","name":"Web Compatibility Interventions","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19628,"quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false}},"theme":{"id":"default-theme@mozilla.org","blocklisted":false,"description":"Follow the operating system setting for buttons, menus, and windows.","name":"System theme — auto","userDisabled":false,"appDisabled":false,"version":"1.3","scope":4,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19634,"updateDay":19634},"activeGMPlugins":{"gmp-gmpopenh264":{"version":"2.3.2","userDisabled":false,"applyBackgroundUpdates":1},"gmp-widevinecdm":{"version":"4.10.2557.0","userDisabled":false,"applyBackgroundUpdates":1}}}}
Throttleable: 1
TotalPhysicalMemory: 34359738368
URL: https://meet.google.com/egx-ftiu-eqj?ijlm=1696412387677&adhoc=1&hs=187
UptimeTS: 42.6487911
UtilityProcessStatus: Running
Vendor: Mozilla
Version: 118.0.1
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.
```
