### ISSUE TITLE
Suppress asking about making Firefox(which is in the runtime) the default browser.

### ISSUE THREAD

**Issue by kuya-carlo** [filips123/PWAsForFirefox#211]
### Problem Description

When I use the PWAs I made using the extension, It always asks me to use THAT Firefox as the default browser.

**Comment by filips123** [comment]
Which prompt do you see (please provide a screenshot)? Default browser checks should already be disabled by `browser.shell.checkDefaultBrowser`.

**Comment by filips123** [comment]
I made some changes in ac79e551b068d8fe432edc97f0318cff9dd53c76 that might solve this. Please update to 2.1.0 and check if it still happens to you.

**Comment by kuya-carlo** [comment]
Hello, The thing happened was when I install FirefoxPWA native app, the installer adds a new shortcut in the start. This makes the system detect both the PWA runtime and the main Firefox app and use the former as a browser. That is where i get the set as default browser prompt(when I got confused between the two Firefox entries and used it). I resolved it by deleting the shortcut that is linked to that but that makes me do it every time i install or update the native app.

Totally unrelated but I get more styling errors(white text being black(without any modifications) when i use the main app.

**Comment by filips123** [comment]
That's weird, the native app shouldn't add any shortcuts on its own (apart from web app shortcuts when you install them). Maybe something in the installation got corrupted? Can you try to completely uninstall the native app, remove any remaining files in `C:\Program Files\FirefoxPWA` and `%APPDATA%\FirefoxPWA` (keep profiles and `config.json` if you don't want to remove your existing web apps), and install it again?

I'll close this issue as #210 is more relevant, so please discuss further things there.
