### ISSUE TITLE
Install new app in new profile by default

### ISSUE THREAD

**Issue by galgalesh** [filips123/PWAsForFirefox#216]
### Problem Description

I saw somewhere you wanted feedback for improving the UX, so here is my suggestion. Currently, the tool suggests using the "default" profile when you install a new app. The text underneath, however, suggests not doing this.

### Proposed Solution

A better solution would be to automatically create a new profile for each new app, since that is the recommended bugless approach. Moreover, that is how all other browsers to it. If a user really wants, they can simply choose to use a different profile.

**Comment by filips123** [comment]
The reason why using a separate profile for each web app is recommended on Linux and macOS is that using multiple apps in a single profile at the same time currently doesn't work properly (#80, #81). After those issues are fixed (which may take a long time), using a single profile will also be the recommended approach, as it's already on Windows.

The main inconvenience that using a separate profile brings is that users have to set up their config manually for each web app. Something like #203 could probably improve this, as users could then pre-create a "template" profile with their settings and use them for *new* web apps. It still won't automatically sync data after the app has been created, but it's better than nothing.

I will try to implement #203 and then also this issue.

>  Moreover, that is how all other browsers to it.

Are you sure about that? At least Edge on Windows installs all web apps into the same profile as the "normal" browser.

**Comment by filips123** [comment]
I've added an option to automatically create a new profile when installing a web app. It's selected by default on Linux and macOS, but can also be used on Windows. This will be released in the next version.
