### ISSUE TITLE
Improve UI for installing a new site

### ISSUE THREAD

**Issue by galgalesh** [filips123/PWAsForFirefox#217]
### Problem Description

The current button for "install current site" is not super clear. I was a bit confused at first and didn't realise how to install a new app because I thought it was instead a banner or regular text.

### Proposed Solution

I'm not a designer but it might help to put a "+" icon there? Or make it a regular "Install this site" button?

**Comment by filips123** [comment]
This should be fine, right?

![slika](https://user-images.githubusercontent.com/16626308/190476097-b3b30a01-9753-4847-9904-d582da7b175f.png)

And the same for creating a new profile.
