### ISSUE TITLE
A way of customizing new created profiles

### ISSUE THREAD

**Issue by filips123** [filips123/PWAsForFirefox#219]
### Discussed in https://github.com/filips123/PWAsForFirefox/discussions/203

<div type='discussions-op-text'>

<sup>Originally posted by **Merlinux-source** August 17, 2022</sup>
First of all, I would love to see an option which enables auto creation of an profile per web app. But that's not the thing I want to talk about. I want to talk about customized profiles. 
Everytime I install a webapp in a new profile, firefox asks me if I want to share infos with firefox. and I have to install the same addons which I need on almost every website again. How about making pre configured new profiles an option? I imagine this as a folder created by the PWA backend, which contains a default profile, which I can load into firefox, customize it and then use it as a new default profile.
Is this hard to implement? and would one of the developers (I don't know how many there are) this as a valuable feature to implement?</div>

**Comment by filips123** [comment]
Is just a single template folder enough, or should there be support for multiple templates so you can choose which one to use when creating a profile?

Implementing just a single template should be easy, as all the program has to do is copy any files in that template to a newly created profile. Implementing support for multiple templates would require some extra work because then it also has to have a way to manage all templates, select which template to use, and an extension UI for this, but it's more useful in case you want differently-customized profiles.

(In any case, this is only a single-time copy when a new profile is created. Continuous sync between multiple profiles is something else that I currently don't plan because it would be too complicated.)

**Comment by jmdurant** [comment]
I would love something like this.  It would be great to have a web app with a specific extension loaded/installed automatically.

**Comment by filips123** [comment]
There is now an option in the extension settings to choose the default profile template. You can enter any directory you want to be copied to new profiles when they are created. It's text input because file inputs don't work with extension popups properly. You can also enter a different template when creating a specific profile.
