### ISSUE TITLE
Customiseing used css

### ISSUE THREAD

**Issue by ReubenDollmanYT** [filips123/PWAsForFirefox#222]
When useing FirefoxPWA windows they follow firefox's use high contrast buttons with custom windows themes
![image](https://user-images.githubusercontent.com/28374251/191125777-0a63e852-2977-4695-b52a-bf507202ad2f.png)
Is there any easy way to modify the css to apply css that will return these to the default buttons

**Comment by filips123** [comment]
You can use `userChrome.css` just like in normal Firefox. You can put your CSS into `chrome/userChrome.css` inside the web app's profile (located in `%APPDATA%\FirefoxPWA\profiles`) and enable `toolkit.legacyUserProfileCustomizations.stylesheets` in `about:config` (press `F6` to access URL input).

**Comment by ReubenDollmanYT** [comment]
Thanks i never knew this was possible
