### ISSUE TITLE
Disable ctrl-w in patched firefox runtime

### ISSUE THREAD

**Issue by danog** [filips123/PWAsForFirefox#223]
It would be nice to disable the ctrl-w shortcut as specified in https://www.math.cmu.edu/~gautam/sj/blog/20220329-firefox-disable-ctrl-w.html: PWAs don't use tabs anyway, and disabling ctrl-w would allow using code-server in Firefox easily.

Already tested locally by manually patching omni.ja, the code-server PWA works like a dream :)

**Comment by filips123** [comment]
Well, PWAs can use tabs if the tabs mode is enabled, but I can probably only disable the shortcut if it's not.

**Comment by cromerc** [comment]
If anything it should be optional to disable it. I use the ctrl-w shortcut all the time in some of my PWAs and would hate to lose that ability.

**Comment by danog** [comment]
Disabling ctrl-w handling in non-tabbed PWAs means PWAs can handle ctrl-w themselves (like for example in vscode), so it's actually even better this way.

**Comment by UndarkAido** [comment]
It would be very nice for this to at least be an option, this is the primary way I close extra PWA windows

**Comment by filips123** [comment]
Well, Ctrl+Shift+Q has the same functionalityy but I guess I can still add an option. Until then, you can [remove this line](https://github.com/filips123/PWAsForFirefox/blob/cdc05248f0c0fd31e6807c702f69f0043426c7f1/native/userchrome/profile/chrome/pwa/content/browser.jsm#L712) in from the profile to revert this change.
