### ISSUE TITLE
The first time I open a PWA, it opens twice. The next time, it opens just fine.

### ISSUE THREAD

**Issue by snydox** [filips123/PWAsForFirefox#226]
[Screencast from 2022-09-28 12:24:22 PM.webm](https://user-images.githubusercontent.com/13590875/192835763-71e2e13c-c9df-4861-b17e-9b9d59be220e.webm)

**Comment by filips123** [comment]
Please provide details about your system:

* Operating system:
* System architecture:
* Desktop environment: 
* Installation method: 
* PWAsForFirefox extension version:
* PWAsForFirefox native version:
* Firefox version:

Also, please obtain and provide logs: Create an empty `DEBUG` file (with no file extension) in the `~/.local/share/firefoxpwa` directory. Then, repeat an action that caused problems and check log files, `firefoxpwa.log`, `firefoxpwa-stdout.log` and `firefoxpwa-stderr.log` in the same directory.

---

What do you mean with "the first time"? Is it the first time you after install the PWA, create a new profile, reboot your computer or something else?

**Comment by snydox** [comment]
It's working fine now. I guess it just needed an update.

**Comment by filips123** [comment]
Nice. Maybe it was related to session restore problems (#175) which have been fixed in [v2.1.1](https://github.com/filips123/PWAsForFirefox/releases/tag/v2.1.1).
