### ISSUE TITLE
Unable to update webapp with an error message.

### ISSUE THREAD

**Issue by JaneValleyhasBtaken** [filips123/PWAsForFirefox#233]
### Description

Error pop up when trying to update web apps, after update the extension and native.
This happened several versions (for both the extension and the Firefox themselves) ago, but I can't remember which.

**This is the error message:**

_Failed to update web app manifest: Failed to download web app manifest: error sending request for url (https://open.scdn.co/cdn/generated/manifest-web-player.562e545c.json): error trying to connect: dns error: No such host is known. (os error 11001): error trying to connect: dns error: No such host is known. (os error 11001): dns error: No such host is known. (os error 11001): No such host is known. (os error 11001)_

### Steps to Reproduce

1. Update your extension and native, and wait for finishing (might be not relevant) .
2. Close all web apps (optional, it happened both opened and closed)
3. Click on 'update web apps'
4. The error pop up, and the update would never finish.

### Environment

* Operating system: Windows 11 22H2 
* System architecture: X64
* Installation method: MSI
* PWAsForFirefox extension version: 2.1.1
* PWAsForFirefox native version: 2.1.1 
* Firefox version: 106b9

**Comment by filips123** [comment]
Domain `open.scdn.co` does not exist (anymore?), so PWAsForFirefox cannot update the manifest from that domain. I think `open.scdn.co` should be `open.spotifycdn.com` (for Spotify). You should be able to edit `%appdata%\FirefoxPWA\config.json` to replace all occurrences of `https://open.scdn.co/cdn/generated/manifest-web-player.562e545c.json` with `https://open.spotifycdn.com/cdn/generated/manifest-web-player.8e800d3e.json` and `open.scdn.co` with `open.spotifycdn.com` and then again update web apps.

**Comment by JaneValleyhasBtaken** [comment]
OMG that works. I have never thought about that problem of Spotify!!! Thank you so much
