### ISSUE TITLE
Can't install web app with shovel

### ISSUE THREAD

**Issue by Khaled-144** [filips123/PWAsForFirefox#236]
### Description

I tried to install [shovel](https://dig.shovelapp.io) as a web app, by clicking on the icon next to the bookmark star, but I got an error 'Failed to parse web app manifest: invalid unknown format at line 24 column 21'
### Steps to Reproduce

1. Go to '[shovel](https://dig.shovelapp.io)'
2. Click on 'install this site' icon
3. Click on 'Install web app'

### Additional Information

![image](https://user-images.githubusercontent.com/116170508/196763242-bcbbf82f-3ff4-44d0-9a69-7b06b5bf152a.png)

### Affected Websites

* [shovel](https://dig.shovelapp.io)

### Environment

* Operating system: Windows 10
* System architecture: 64-bit
* Installation method: Via the browser add-ons store
* PWAsForFirefox extension version: 2.1.2
* PWAsForFirefox native version: 2.1.2
* Firefox version: 106.0 
* Waterfox version: G5.0.1
* I am using Waterfox as my main browser

**Comment by filips123** [comment]
This happens because Shovel's web app manifest includes an empty string as a theme color which causes parsing to fail. I will try to fix this. Until then, you should be able to install it if you uncheck the "Use the manifest" checkbox.
