### ISSUE TITLE
makers Command is not found. How to install it?

### ISSUE THREAD

**Issue by ArvindRSingh** [filips123/PWAsForFirefox#237]
Issue in installing the extension on Linux for Firefox.

Following the instructions to install from source mentioned on "Setup Progressive Web Apps for Firefox".

Step 6 reads "Build and install the project: makers install".

Issue: `makers` command is not found on newly installed Fedora 36 Linux, system is up to date.

How do I install `makers` or should it be make?

**Comment by filips123** [comment]
You need to install [https://github.com/sagiegurari/cargo-make](cargo-make) using cargo.

**Comment by ArvindThinkBridge** [comment]
Thanks @filips123, installed it again and found there is a warning for which I have to configure a path.
Also, I should have looked at instructions for Redhat-like installation which has instructions for Fedora's dnf package manager.
_Little too much than a single click install. I come from years of Windows usage. :)_


```
[arvindrsingh@fedora ~]$ cargo install cargo-make
    Updating crates.io index
     Ignored package `cargo-make v0.36.2` is already installed, use --force to override
**warning: be sure to add `/home/arvindrsingh/.cargo/bin` to your PATH to be able to run the installed binaries**
[arvindrsingh@fedora ~]$ cd /home/arvindrsingh/.ca
.cache/ .cargo/ 
[arvindrsingh@fedora ~]$ cd /home/arvindrsingh/.ca
.cache/ .cargo/ 
[arvindrsingh@fedora ~]$ cd /home/arvindrsingh/.cargo/bin
[arvindrsingh@fedora bin]$ ll
total 26840
-rwxr-xr-x. 1 arvindrsingh arvindrsingh 13740648 Oct 20 13:14 cargo-make
-rwxr-xr-x. 1 arvindrsingh arvindrsingh 13740608 Oct 20 13:14 makers
[arvindrsingh@fedora bin]$ cd ~
[arvindrsingh@fedora ~]$ makers
bash: makers: command not found...
```
