### ISSUE TITLE
Is there anyway to change a specific app's icon ?

### ISSUE THREAD

**Issue by Nobunaji** [filips123/PWAsForFirefox#242]
### Problem Description

I haven't been able to find a way to change the PWA App's icon. Is there anyway to do it ? I have made a PWA App from the music.youtube.com website and i would like to change its icon.

### Proposed Solution

I have no clue how you would go about adding it if it isn't currently possible.

**Comment by filips123** [comment]
It's possible to manually change the web app icon files.

   Windows:
   Web app and shortcut icons are stored in ICO format inside `%APPDATA%\FirefoxPWA\icons\APPID`.
   The web app icon is named `site.ico`, and the shortcut icons are named `shortcutN.ico`.
   Simply replace that files with your custom ICO file.

   Linux:
   Web app and shortcut icons are stored as PNGs and SVGs inside `icons/hicolor/*/apps/` in the user's data directory (`$XDG_DATA_HOME` or `$HOME/.local/share`).
   Icons are named `FFPWA-APPID.png`. All web apps have 48x48 icons, while some also have additional icon sizes.
   You probably have to delete/replace all of them to show correctly.

   macOS:
   You can follow [this tutorial](https://9to5mac.com/2021/11/08/change-mac-icons/) to change an app icon.


Easier method of changing icons might be available in the future, but I cannot promise when, as there are some things that make it harder to implement. You can follow #128 for progress.
