### ISSUE TITLE
Does not remove ~/.local/share/applications desktop file on profile deletion

### ISSUE THREAD

**Issue by Samisafool** [filips123/PWAsForFirefox#243]
### Steps to Reproduce

1. Create a new PWA with separate profile
2. Delete the whole profile
3. Look in ~/.local/share/applications
4. See that a desktop file is still there

### Affected Websites

* All websites

### Environment

* Operating system: Arch btw
* System architecture: x86_64
* Desktop environment: KDE
* Installation method: AUR
* PWAsForFirefox extension version: 2.1.2
* PWAsForFirefox native version: 2.1.2
* Firefox version: 106.0.2

**Comment by filips123** [comment]
Thanks for reporting this. It seems I forgot to call the system integration stuff when deleting profiles. I will fix this in the next release.
