### ISSUE TITLE
Setup - Connector Installation

### ISSUE THREAD

**Issue by ivandelvecchio** [filips123/PWAsForFirefox#264]
In Ubuntu 22.04, after installing the additional program, get the error "An unexpected error occurred". The additional program is installed and working, I restarted the browser, and then the pc, but the error remains
![Screenshot from 2023-01-11 13-30-28](https://user-images.githubusercontent.com/23737867/211806925-ae8728a1-20a6-4426-a0e8-3aeb175625dd.png)
![Screenshot from 2023-01-11 13-30-56](https://user-images.githubusercontent.com/23737867/211806927-ec23e44c-97e3-451a-a663-ce5e31a24189.png)

**Comment by filips123** [comment]
Which Firefox version do you have and do you use Snap or Flatpak package? You can check this if you go to Firefox Menu -> Help -> About Firefox.

**Comment by ivandelvecchio** [comment]
Hi Filip,

thanks for replying. This is my Firefox configuration:
[image: image.png]
Regards,
Ivan

Il giorno gio 12 gen 2023 alle ore 17:18 Filip Š ***@***.***>
ha scritto:

**Comment by filips123** [comment]
It looks like your image hasn't been uploaded properly.

**Comment by ivandelvecchio** [comment]
It worked, thank you!!

Il giorno gio 12 gen 2023 alle ore 18:11 Filip Š ***@***.***>
ha scritto:
