### ISSUE TITLE
'Overwrite' option when opening a new page in a Web App?

### ISSUE THREAD

**Issue by HarveyEllis** [filips123/PWAsForFirefox#265]
### Problem Description

We can currently have multiple tabs in the same window for the same PWA. We cannot however, have a new visit from outside overwrite the page in the Web app I don't think? (I've had a look round the settings and this doesn't seem to be the case?)

Use case: I have a workflow set up so that when I click on GH/Zendesk issues from slack they open a Github/Zendesk PWA. Every time I click on one, I'd like it just to use the same window, but navigate away from whatever I was looking at (I go back to slack and open a new issue, but I've either commented or read the previous one completely before I do that). 

### Proposed Solution

A new setting for "overwrite current page" would be nice so that when we click a link or open a page in a web app we can choose to have that open action overwrite whatever is already there. 

### Additional Information

I suppose this could be possible by installing some kind of tab limiter in every PWA installed, but that is a bit faffy.

**Comment by filips123** [comment]
So, you want something like "Open a web app in an existing window of that web app", except it overwrites existing tab instead of creating a new one?

**Comment by HarveyEllis** [comment]
Yes - that is what I was trying to do. 

Managed to emulate this by:
- Setting tabbed browsing to on in the window you want
- Set new tabs to open in the same 
- Use userChrome.css to disable tabs

Maybe others could just do that? 

A bit awkward and involved to set up, but works.

**Comment by filips123** [comment]
Nice that you managed to set this up. I think it shouldn't be too hard to implement, so I'll probably add a proper option for this in the future.
