### ISSUE TITLE
Opening a 2nd app on the same profile always redirects to the main browser

### ISSUE THREAD

**Issue by shrugal** [filips123/PWAsForFirefox#266]
### Description

With the "Open out-of-scope URLs in a default browser" option enabled opening an app while a different one is already running on the same profile causes the 2nd app to show a blank screen and instead open the app URL in a tab in the main browser window. If "Auto launch app" is enabled as well then this causes an endless cascade of app windows and browser tabs.

### Steps to Reproduce

1. Enable  "Open out-of-scope URLs in a default browser" option
2.  Open one app
3. Open a different app using the same profile
4. The 2nd app shows a blank screen and opens in the main browser window instead

### Additional Information

Both apps work fine individually, with out-of-scope URLs in new window disabled, or when using different profiles for each app. It also worked find in previous versions.

### Affected Websites

Tried it with

- notion.so
- music.youtube.com
- keep.google.com

### Environment

* Operating system: Windows 11
* System architecture: x64
* Installation method: MSI
* PWAsForFirefox extension version: 2.3.0
* PWAsForFirefox native version: 2.3.0
* Firefox version: 108.0.2

**Comment by filips123** [comment]
I can also reproduce this and will try to fix this soon.
