### ISSUE TITLE
PWA just opens new browser after opening the app

### ISSUE THREAD

**Issue by Xezioh** [filips123/PWAsForFirefox#270]
so , im trying to use Proton.me as a PWA , and it opens the window , says loading , then opens a new browser with the website , and app just loads forever 

### Steps to Reproduce

1. Go to proton.me
2. add as app
3. open app
thats pretty much all 

### Additional Information
already tried to uninstall everything.
did not help :( it was working a few days ago :(

* Operating system: windows 11
* System architecture: x64
* Installation method: MSI
* PWAsForFirefox extension version: newset
* PWAsForFirefox native version: newest 
* Firefox version: newest

**Comment by filips123** [comment]
Do you have "Open out-of-scope URLs in a default browser" enabled? If yes, you need to add `account.proton.me` to the "Domains always allowed to be opened in the PWA browser" option.

**Comment by Xezioh** [comment]
> 

i cant seem to find this option ..
i might be blind

**Comment by filips123** [comment]
It's in the PWA browser settings:

![slika](https://user-images.githubusercontent.com/16626308/213726988-6e50b642-02dd-406c-b3f0-f83054d810fb.png)

![slika](https://user-images.githubusercontent.com/16626308/213727079-214c6162-ac30-49ee-93d2-9e955519f6f9.png)

**Comment by Xezioh** [comment]
thank you very much!!! appreciate it a lot!
