### ISSUE TITLE
Add option to launch individual PWAs with Firefox startup

### ISSUE THREAD

**Issue by Patricek0056** [filips123/PWAsForFirefox#273]
### Problem Description

The PWAs don't have option to launch with Firefox startup.

### Proposed Solution

PWAs should have option to launch with Firefox startup.
Well, this option should be on the bottom of “Edit web app” menu.

### Additional Information

NOTE: I don't think the “Enable automatic web app launching”, I think individual PWAs to start. In short: I check YouTube, then restart Firefox, then the YouTube launches with Firefox startup and others unchecked won't launch.

**Comment by filips123** [comment]
Sounds like a good idea, I will check how to add it, but I think it shouldn't be to hard.

**Comment by filips123** [comment]
I've added two new options, one to launch web app on the system login, and another to launch it when Firefox starts. They will be available on the edit web app screen in the extension.
