### ISSUE TITLE
Feature Req: Linux System Extensions

### ISSUE THREAD

**Issue by cybik** [filips123/PWAsForFirefox#277]
### Problem Description

Linux systems are able to install extensions in "system" locations, and keep such extensions updated outside of the Mozilla Addons site. FirefoxPWA applications seem to ignore these system-installed extensions.

### Proposed Solution

It would be nice if FirefoxPWA "profiles" (or whatever is used here) could use these system-installed extensions. This way, for example, I could have my KeepassXC Web Extension installed and updated by apt completely outside of Mozilla Addons, and have it baked into *all* my FirefoxPWA applications.

Technical bonus: I could start making personalized .deb packages for other extensions so that such extensions are always available to any and all FirefoxPWA containers I use, but that's beside the point.

**Comment by filips123** [comment]
When testing on Ubuntu 22.04, the unmodified Firefox downloaded from the `.tar.bz2` file also does not detect system extensions, so I think it's not a PWAsForFirefox problem. Unfortunately, I don't think I can do anything to fix it, but you can try to report it to Bugzilla.

If you want to install the extension for all (new) profiles, you can probably use [profile templates](https://github.com/filips123/PWAsForFirefox/issues/219#issuecomment-1374853375).
