### ISSUE TITLE
macOS PWAs have no dock icon

### ISSUE THREAD

**Issue by AnthonyWharton** [filips123/PWAsForFirefox#282]
### Description

Traditionally, most interactive apps in macOS when open will have a dock icon to indicate that they are open. Firefox PWAs do not.

Furthermore, if you manually add a Firefox PWA to the Dock and then open it, it will open an instance of the window but the open window indicator "dot" underneath the Dock icon does not show. This consequently has the behaviour of opening new instances of the Firefox PWA every time you click the dock icon, rather than bringing the current instance to the foreground (which is typically the default macOS behaviour).

### Steps to Reproduce

1. Open an installed Firefox PWA from Spotlight Search.
2. Observe no dock icon is present.
3. Add the installed Firefox PWA to the dock by dragging it from Launchpad/Spotlight search to the dock.
4. Click on the Firefox PWA icon on the dock twice and observe that multiple windows open, and no window-open indicator dot shows.

### Affected Websites

Whilst this appears to affect all websites, it is particularly annoying with WhatsApp web and similar websites, which only allows for one session to be open at once.

### Environment

* Operating system: macOS 13.0.1
* System architecture: Apple Silicon (M1 PRO)
* Installation method: Homebrew
* PWAsForFirefox extension version: 2.4.0
* PWAsForFirefox native version: 2.4.0
* Firefox version: 109.0

**Comment by filips123** [comment]
It works fine for me, but I only have old macOS 10.15.7. Maybe something has changed in recent macOS versions.

@TitanNano Sorry to bother you again, but could you please check why this happens?

**Comment by TitanNano** [comment]
@AnthonyWharton I can't reproduce this on macOS 13.1. Could you post screenshots?

**Comment by AnthonyWharton** [comment]
Hi all,

I just attempted to recreate on a screen capture, but I wasn't quite getting the same behaviour. To try reset to a clean environment I rebooted my machine and updated all the web app using the button in the extension, and now it is working perfectly.

I promise I'm not going mad(!), but I cannot reproduce this issue now so I think I will close this issue unless I have it come back (at which point I will do my best to find proper reproduction steps).

Thanks for the responses and apologies for wasting your time!
Anthony

**Comment by AnthonyWharton** [comment]
(I might just add, when I wasn't having the same behaviour before I reset, I was that time getting another Firefox icon appear in my dock when I opened the PWA from my shortcut in the dock, rather than the active app indicator appearing beneath the PWA icon in the dock.)

**Comment by TitanNano** [comment]
> I was that time getting another Firefox icon appear in my dock when I opened the PWA from my shortcut in the dock, rather than the active app indicator appearing beneath the PWA icon in the dock.

This happens when the Firefox runtime that is used by this project, just has been updated. The updater restarts Firefox right when you start your PWA, and then it forgets what PWA it is actually running. I usually just close that Firefox instance and restart the PWA when it happens.
