### ISSUE TITLE
[PortableApps.com] Set default browser path

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#286]
Hi,
I use the PortableApps.com version of PWAsForFirefox, and check this item:
- Open out-of-scope URLs in a default browser (can break some web apps)
![image](https://user-images.githubusercontent.com/23485114/216663009-ff0f672a-b81c-4dcc-b2f7-4fd7ef58a0c1.png)

Now I have a question:
How do I set the default browser?

**Comment by filips123** [comment]
If you also use the portable version as normal Firefox, you can check [this](https://portableapps.com/node/61000) or some similar threads on the forums. Alternatively, you can go to the PWA settings, scroll down to the "Applications" section, select "Use other" as an action for "https"/"http" content type, and provide a path to your portable Firefox.

If you want to use system Firefox, you can change the default browser in the system settings.
