### ISSUE TITLE
Addon Buttons dissapear if you remove them.

### ISSUE THREAD

**Issue by mrd77** [filips123/PWAsForFirefox#288]
### Description

Add-on Buttons disappear completely without the possibility to re-add them from the "Customize Toolbar..." window after removing from toolbar (and restarting PWA)

### Steps to Reproduce

1. Create new Firefox PWA
2. Install Add-on with dedicated button. Button gets added beside tab-bar. You can pin it to overflow menu, or move it in via the "Customize Toolbar" window
3. You can also delete the button and re-add, until you restart the PWA (close all windows and reopen, without necesarly restarting firefox itself). Then the button dissapears from the customize menu without the possibility to re-add.

before and after restart 
!["ublock Origin" is gone in the after picture](https://user-images.githubusercontent.com/32589874/217109766-ad865d29-6a68-4cc1-a9c7-c2c2707c58f9.jpg)

### Environment

* Operating system: Windows 10
* System architecture: 64 bit
* PWAsForFirefox extension version: 2.4.0
* PWAsForFirefox native version: 2.4.0
* Firefox version: 109.0.1

**Comment by mrd77** [comment]
my guess is this has something to do with the newly introduced add-on button on main firefox?

**Comment by filips123** [comment]
Yes, it is related to the new unified extensions button. I thought I've disabled it until I add proper support, but it seems I did that too later in the code. I will soon release a new version that properly enables unified extensions.
