### ISSUE TITLE
Option to focus an existing instance of a web app

### ISSUE THREAD

**Issue by filips123** [filips123/PWAsForFirefox#291]
### Discussed in https://github.com/filips123/PWAsForFirefox/discussions/287

<div type='discussions-op-text'>

<sup>Originally posted by **ThijmenDam** February  6, 2023</sup>
Hi! I wonder if the current opening behavior of an app on macOS is intended. Right now, if I open a PWA that is already running (i.e. by double clicking the app icon or through Spotlight), a second instance of the app is opened. However, to me it would make more sense if the instance of the app that's already running would be brought to the front instead of opening a new instance. I think this is more in line with the usual behavior of macOS apps.</div>

**Comment by caph1993** [comment]
Hello. I'm in Linux and I have exactly this problem. When I double click the app launcher after its open, a second window opens.

This is my environment:
```zsh
➜  ~ 
➜  ~ firefoxpwa --version                                                                
firefoxpwa 2.12.5

➜  ~ firefox --version                                                                   
Mozilla Firefox 131.0.3

➜  ~ uname -a && lsb_release -a 2>/dev/null | grep 'Description'
Linux lat7310 6.11.5-1-default #1 SMP PREEMPT_DYNAMIC Wed Oct 23 04:27:11 UTC 2024 (b4e3aa9) x86_64 x86_64 x86_64 GNU/Linux
Description:    openSUSE Tumbleweed
```

**Comment by filips123** [comment]
You can enable focusing the existing window in [the app browser settings](https://pwasforfirefox.filips.si/user-guide/browser/#changing-the-launch-type).

**Comment by caph1993** [comment]
> You can enable focusing the existing window in [the app browser settings](https://pwasforfirefox.filips.si/user-guide/browser/#changing-the-launch-type).

Oh, yes. I was searching everywhere in the settings of the extension, not in the browser settings inside the PWA.

Thank you, I just realized that this is also mentioned by you [here](https://github.com/filips123/PWAsForFirefox/discussions/287#discussioncomment-10562156).
