### ISSUE TITLE
Rename “Categories” to “Tags” in PWAs For Firefox

### ISSUE THREAD

**Issue by Patricek0056** [filips123/PWAsForFirefox#293]
### Problem Description

I am opening this because the “Categories” in PWAs For Firefox have inconsistent name with “Tags” in Firefox library.
The “Categories” in PWAs For Firefox and “Tags” in Firefox library have the same functionality.

I think categories under the edit web app menu.

### Proposed Solution

Rename “Categories” to “Tags” in PWAs For Firefox.

### Additional Information
— I think, that this would be easy to solve.

Related issues:
— https://github.com/filips123/PWAsForFirefox/issues/260
— https://github.com/filips123/PWAsForFirefox/issues/292

**Comment by filips123** [comment]
I use "categories" because "categories" is also used in the [web app manifest specification](https://w3c.github.io/manifest-app-info/#categories-member):

> The `categories` member is an array of strings that describes the application categories to which the web application belongs. It is meant as a hint to catalogs or stores listing web applications and it is expected that these will make a best effort to find appropriate categories (or category) under which to list the web application. Like search engines and meta keywords, catalogs and stores are not required to honor this hint. 

This is also consistent with their functionality [in the system integration](https://github.com/filips123/PWAsForFirefox/blob/main/native/src/integrations/categories.rs), where they are also called "categories".

**Comment by Patricek0056** [comment]
So this is invalid?

**Comment by Patricek0056** [comment]
And categories and tags are the same, I am right?

**Comment by filips123** [comment]
Yes, this bug is invalid, but I posted quite a lot of things related to the app organization in https://github.com/filips123/PWAsForFirefox/issues/292#issuecomment-1422491237.
