### ISSUE TITLE
Exception List to prevent operating link to PWA

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#296]
Hello
I want to prevent some links from opening in the PWAs.
For example:
https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbWhsQ3Byd0taaWJpRTRvSGpQakFHZlNucnRIZ3xBQ3Jtc0tuTVA0azlxUVhobnljT181MVNUZVA0XzJrUlhyVHVWaHhJbjVuNlFyQnNJbmdQTzNJVFZHendlSW91aUJMYklDNHpQa0FJQTY5bXVGRUczN0o3Q1F4U081VXVBcm1hUnM2bVNjSkRxZ3FpbUdNaktXNA&q=https%3A%2F%2Fgithub.com%2Ffilips123%2FPWAsForFirefox&v=a19hwmDFw3E
Please support this feature using regex: `^(?:https?:\/\/)(?:www.)?youtube.com\/redirect(.*)`
Thanks.

**Comment by filips123** [comment]
Do you mean the "Enable automatic web app launching" feature in the extension? So, if you opened such link in the main Firefox, it wouldn't be opened in the PWA?

**Comment by xmha97** [comment]
> Do you mean the \"Enable automatic web app launching\" feature in the extension?

Yes, I mean this feature.

> So, if you opened such link in the main Firefox, it wouldn't be opened in the PWA?

If I click on this link, it will open in PWA.
I don't want all links to open in PWA, for example redirect links.

**Comment by filips123** [comment]
Well, how often do you come across such links when not already in the YouTube PWA? Isn't basically the only place where you could find those links if you were already on YouTube, so it's kinda pointless to prevent them from opening PWA?

I don't know how exactly to implement this feature, and I'm not completely sure yet if it's worth spending time on it...

**Comment by ItsRogueRen** [comment]
> Well, how often do you come across such links when not already in the YouTube PWA? Isn't basically the only place where you could find those links if you were already on YouTube, so it's kinda pointless to prevent them from opening PWA?
> 
> I don't know how exactly to implement this feature, and I'm not completely sure yet if it's worth spending time on it...

The use case I see for this is using social apps as a PWA (Mastodon, Discord, Twitter, etc.) where you want to open the link shared in your browser but not need to reload the PWA to stay on Discord, Mastodon, etc. This is 100% an issue I face using this with Discord as a PWA

**Comment by filips123** [comment]
So, for example, if someone sends you a link through some other communication channel, but it uses Twitter's redirection because they've found it on Twitter and only copied it, without resolving to the actual URL?

Yeah, this sounds annoying... Maybe some addon already exists that can resolve such URLs without triggering PWAsForFirefox? Otherwise, I will probably check what I can do.

**Comment by ItsRogueRen** [comment]
> 

There is an "open in" series of add-ons for chromium browsers and Firefox forks like Waterfox, but nothing for if Firefox is your default browser

**Comment by filips123** [comment]
I was thinking about addons that can turn "redirection URLs" into their actual target URLs, without causing PWAsForFirefox's auto launch to trigger. I think some such addons already exist, but I'm not sure if they still cause PWAsForFirefox to auto launch PWAs on redirection URLs or not.

**Comment by filips123** [comment]
In the next release, there will be an additional regex field in the extension settings that can be used to exclude URLs from auto launch. There is just a single global regex for all web apps, so you will probably have to write a bit longer regex with "or" operators if you want to use it for multiple web apps.

It seems there are some proposals for specifications that would allow web apps to configure excluded paths themselves, however, they are not finalized yet. So, until they become more stable and adopted, I will probably just support that single regex, as that is the simplest way to implement this...

**Comment by xmha97** [comment]
Thanks 🙏
