### ISSUE TITLE
Can't install extensions in web apps

### ISSUE THREAD

**Issue by XCraftMC23** [filips123/PWAsForFirefox#297]
### Description

Whenever I try to install an extension inside an app, it just loads forever. For example: I tried to install uBlock Origin so I can block ads, but it won't install the addon.

### Steps to reproduce this bug

1. Press f6
2. Go to addons.mozilla.org
3. Install uBlock Origin
4. Load forever

### Additional Information

I installed the desktop version through the .msi installer.
Version 2.4.1

### Environment

* Operating system: Windows 10 Pro
* System architecture: x64
* Desktop environment: N/A
* Installation method: MSI
* PWAsForFirefox extension version: 2.4.1
* PWAsForFirefox native version: 2.4.1
* Firefox version: 109.0.1

**Comment by filips123** [comment]
Have you removed the (unified) extensions widget from the toolbar? If yes, I think this is why you cannot install extensions anymore. You will need to add it back and restart the web app before the installation will work again.

Although removing the unified extensions widget is kinda unsupported, I'll check if I can fix this.

**Comment by XCraftMC23** [comment]
I don't know what you mean by unified extensions widget, but I haven't removed anything at all.

**Comment by filips123** [comment]
If you go to the Customize page inside your web app (Firefox menu -> More tools -> Customize toolbar), do you see the "Extensions" widget? If so, drag it to the toolbar, restart web app, and try to install uBlock Origin again.

![screenshot](https://user-images.githubusercontent.com/16626308/218572046-4022bc3a-e81e-46ec-a3c6-64d11aea4c61.png)

**Comment by XCraftMC23** [comment]
Yep, that fixed it, thanks!

**Comment by filips123** [comment]
This should be fixed in the next release.
