### ISSUE TITLE
Version 2.4.1 connector is not available on Winget

### ISSUE THREAD

**Issue by charlesroper** [filips123/PWAsForFirefox#298]
### Description

Instructions say:

> 3. Install PWAsForFirefox using winget: `winget install firefoxpwa --version 2.4.1`

However, only `2.4.0` is available to Winget:

```pwsh
> winget search firefoxpwa
Name           Id                Version Source
------------------------------------------------
PWAsForFirefox filips.FirefoxPWA 2.4.0   winget
```

**Comment by filips123** [comment]
New version to `winget` is currently delayed because of some dependency issues (microsoft/winget-pkgs#95798). I don't know when it will be solved, but hopefully soon. In the meantime, you can install the connector manually.

**Comment by filips123** [comment]
This has been resolved.
