### ISSUE TITLE
Feature Request: choose the firefox executable to use

### ISSUE THREAD

**Issue by Rathmox** [filips123/PWAsForFirefox#300]
### Problem Description

I want to use Librewolf instead of Firefox. Or a specific installation of Firefox.

### Proposed Solution

Adding a setting to select the Firefox executable.

**Comment by filips123** [comment]
You can manually download and extract LibreWolf (or another Firefox-based browser) and use it as runtime. Instructions for this are in [FAQ](https://github.com/filips123/PWAsForFirefox/wiki/Frequently-Asked-Questions) (question 5).

**Comment by Rathmox** [comment]
Thanks.
I tried but it just lauches a normal Librewolf and doesn't open the website

**Comment by filips123** [comment]
Try to enable "Always patch runtime and profile" in the extension settings and launch web app again. If it works, you can then disable this setting.

**Comment by Rathmox** [comment]
Doesn't work, and destroys my profiles everytime

**Comment by filips123** [comment]
What do you mean with this? Also, which OS do you use?

**Comment by Rathmox** [comment]
Arch Linux

**Comment by filips123** [comment]
I tried to reproduce this on fresh Arch Linux with KDE, but it works fine for me.

**Comment by filips123** [comment]
I'll close this issue because it seems to work fine. If you still have problems, please check if you have done everything correctly.
