### ISSUE TITLE
Firefox opens automatically on login

### ISSUE THREAD

**Issue by Rathmox** [filips123/PWAsForFirefox#303]
### Description

When logging in, firefox automatically opens

### Steps to Reproduce

1. Login to 
2. Firefox auto starts

### Additional Information

Firefox isn't in my auto start list

### Environment

* Operating system: Arch Linux
* System architecture: x86_64
* Desktop environment:  KDE Plasme 5.27.1
* Installation method:  AUR
* PWAsForFirefox extension version: 2.4.1
* PWAsForFirefox native version: 2.4.1-1
* Firefox version: 110.0

**Comment by filips123** [comment]
Does it open any specific PWA or just normal Firefox?

**Comment by Rathmox** [comment]
normal firefox but with a default pwa profile or something like that

**Comment by eljejer** [comment]
Same here. When I have an open Firefox session when logging off, when logging in again Firefox opens automatically.
When I disable the PWA extension before logging off, this does not happen

**Comment by eljejer** [comment]
Same here. When I have an open Firefox session when logging off, when logging in again Firefox opens automatically.
When I disable the PWA extension before logging off, this does not happen.
There is no active PWA session open at the moment.

Never mind, this turned out to be a KDE setting 'Session restore'. When I change to 'Start with an empty session' obviously, Firefox is not started automatically.

**Comment by filips123** [comment]
@Rathmox Can you check if it's the same for you?

**Comment by eljejer** [comment]
However, when I change KDE settings back to 'On login, launch apps that were open on last logout' and I have one PWA sessions open on logout as well as a normal Firefox session, the normal Firefox is restored, but the PWA (mail.proton.me) is not restored. In stead, an extra Firefox Home session is opened where I am not logged in to Firefox. I am logged in to Firefox in the normal session.

**Comment by Rathmox** [comment]
@filips123 yes, it's fixed

**Comment by filips123** [comment]
Session restore with PWAs has some known problems (#256) that are unlikely to get fixed soon. Workaround for this is to either completely disable KDE session restore or exclude Firefox PWAs/runtime from it.
