### ISSUE TITLE
Rename "firefox.exe" to "ffpwa.exe"

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#304]
Hi,
I use this command below to close Firefox:
```
TASKKILL /F /IM firefox.exe /T
```
Firefox closes but all PWAs close too.
Please rename "firefox.exe" to "ffpwa.exe"

![image](https://user-images.githubusercontent.com/23485114/221329890-6bb68bbf-0779-4ab3-b544-63ca5be67a39.png)

Thanks.

**Comment by filips123** [comment]
I don't want want to rename Firefox executable because this might break other things that expect the standard executable name. Maybe there is a way that you could kill normal Firefox by its full path?

**Comment by xmha97** [comment]
Thanks 👍
