### ISSUE TITLE
PWA open 2 times when opening for the first time after login

### ISSUE THREAD

**Issue by Rathmox** [filips123/PWAsForFirefox#305]
### Description

When starting a PWA for the first time after logging in, the PWA opens 2 times

### Steps to Reproduce

1. Login
2. Start a PWA
3. the PWA should open 2 times

### Additional Information

I only have one PWA so I can't tell if it happens with every PWA or if when one gets this bug, the others aren't affected

### Environment

* Operating system: Arch Linux
* System architecture: x86_64
* Desktop environment:  KDE Plasme 5.27.1
* Installation method:  AUR
* PWAsForFirefox extension version: 2.4.1
* PWAsForFirefox native version: 2.4.1-1
* Firefox version: 110.0

**Comment by filips123** [comment]
I think this might also be related to the session restore problems. You can try to disable KDE's session restote. Also, you can try to go to `about:config` (press `F6` for the URL input) and disable all `browser.sessionstore`'s resume/restore preferences.

**Comment by Rathmox** [comment]
I opened this issue because even after disabling KDE session restore, the issue was still there.
So it means, even if the PWA is closed, firefox is still running in the background ?

**Comment by filips123** [comment]
It shouldn't be, so I don't know what's happening here. Please try to disable Firefox's session store in `about:config`. Also, check how "Open previous windows and tabs" is set in the PWA settings.

**Comment by Rathmox** [comment]
I haven't tested but I'm pretty sure it was the problem so I will mark as fixed
