### ISSUE TITLE
Extensions menu does't open on anything but first PWA window opened.

### ISSUE THREAD

**Issue by charlesroper** [filips123/PWAsForFirefox#308]
### Description

If I have more than one PWA window open, the extensions menu will not open on anything but the first window. This seems to be because the menu is opening in the first window, even though I'm clicking on the icon in a subsequently opened window. This means the menu is effectively broken and doesn't show up on anything but the first window, unless you happen to have the first window showing at the same time.

### Steps to Reproduce

1. Open two windows
2. Place them side-by-side
3. Toggle the extensions menu of the first window (it should open and close as expected)
4. Toggle the extension menu of the second window (it should open and close the menu in the first window)

### Additional Information

Screenshot

![2023-03-06_02](https://user-images.githubusercontent.com/176/223148179-d3b74356-1b1e-402e-929a-ff6dd4f16f89.png)

### Environment

* Operating system: Windows 10
* System architecture: 64 bit
* Installation method: MSI
* PWAsForFirefox extension version: 2.4.1
* PWAsForFirefox native version: 2.4.1
* Firefox version: 110.0.1 (64-bit)

**Comment by haihefa** [comment]
Pardon my ignorance but how did you get tabs on your PWAs? also, I don't have any option to _enable_ extensions button within my PWAs, I think I'm doing something wrong

**Comment by filips123** [comment]
This should be fixed in the next release.
