### ISSUE TITLE
Window decorations (close, minimize, etc.) are visible in fullscreen (Linux)

### ISSUE THREAD

**Issue by ParadoxPandox** [filips123/PWAsForFirefox#312]
### Description

When I open a video in fullscreen on a YouTube PWA on my installation of Pop!_OS, the window decorations, specifically close, minimize, and maximize, are still visible on the screen in the corner. 

### Steps to Reproduce

1. Go to [YouTube](https://www.youtube.com/)
2. Click on a video
3. Go into fullscreen
4. The buttons end up still visible

### Additional Information

At first, I thought it was maybe my theme or my placement of those buttons, as I use them on the left, macOS-style, but neither seems to be the issue. I also tried switching between the default compositor and Wayland to check that, as well, but that didn't fix the problem, either.

I've attached an image. Look in the top left for the buttons.

![image](https://user-images.githubusercontent.com/24617343/225806241-d4e0ac32-d4b5-413b-9eb4-f0a4fd7b592c.png)

This does not happen on other OSes I use (Windows 11 and macOS 13).

### Affected Websites

* [YouTube](https://www.youtube.com/)

This is the only web app I currently have installed on this system.

### Environment

* Operating system: Pop!_OS 22.04
* System architecture: x86_64
* Desktop environment: GNOME
* Installation method: APT Repository
* PWAsForFirefox extension version: 2.4.1
* PWAsForFirefox native version: 2.4.1
* Firefox version: 111.0

**Comment by filips123** [comment]
Can you check if this also happens with the normal Firefox that you can download from [Mozilla website](https://www.mozilla.org/firefox/all/)?
