### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by sajonCC** [filips123/PWAsForFirefox#313]
When opening PWA from firefox tool bar, I'm receiving a message "An unexpected error occurred".

### Steps to Reproduce

1. Install PWA extension from firefox AddOns list.
2. Follow installation procedure as described in open webpage. Download and install deb package.
3. Webpage never detects running backend.
4. During installation an pop-up is show not allow extension to run in private window. When acknowledged, web page with installation procedure disappeared. 
5. Clicking PWA icon on Firefox toolbard is showing an error message "An unexpected error occurred".

Based on troubleshooting guidelines, please see additional information.
 
![image](https://user-images.githubusercontent.com/76811268/225905412-f6cc4f1a-c03e-4bd8-970c-a2b0956003ab.png)

* Operating system: Latest KDE Neon based on Ubuntu 22.04
* System architecture: x86_64
* Desktop environment: KDE
* Installation method: DEB
* PWAsForFirefox extension version: 2.4.1
* PWAsForFirefox native version: 2.4.1
* Firefox version: 111

**Comment by filips123** [comment]
It appears that default Firefox distributed with KDE Neon has a bug that breaks native messaging. See https://github.com/filips123/PWAsForFirefox/issues/283#issuecomment-1418030583 for more details. You can try to download Firefox directly from Mozilla website and use that one.

**Comment by sajonCC** [comment]
Thank you and sorry for duplicated post. I was not able to find by search a bug report from your link.

To confirm that everything is working fine with Firefox downloaded from Mozilla webpage.
