### ISSUE TITLE
Updating the https://time.is web app manifest prompts an error

### ISSUE THREAD

**Issue by Patricek0056** [filips123/PWAsForFirefox#314]
### Description
Error description: Failed to update system integration: Failed to create menu shortcut: Failed to rename shortcut: The system cannot find the file specified. (os error 2)

### Steps to Reproduce
It is maybe a problem with the https://time.is title, because the title changes from e.g. 10:26 to 10:27.

### Additional Information
(Actually nothing)

### Affected Websites
https://time.is/

### Environment
* Operating system: Windows 11 22621.1413
* System architecture: 64-bit
* Installation method: MSI
* PWAsForFirefox extension version: 2.4.1
* PWAsForFirefox native version: 2.4.1
* Firefox version: 111.0

**Comment by Patricek0056** [comment]
I think the “Update web apps” in the PWAsForFirefox menu in the settings tab.

**Comment by Patricek0056** [comment]
Oh, I just found what web app is causing this problem, it is the: https://time.is/ web app.

**Comment by filips123** [comment]
It works fine for me on Windows 10. I think it's probably not caused by title changes, because PWAsForFirefox should be able to handle those. It might becaused by the dot in the title instead.

Can you try to uninstall time.is and install it again, and then try to update it?

**Comment by Patricek0056** [comment]
Interesting, without the dot it is no longer reproducible.

**Comment by filips123** [comment]
Maybe Windows 11 changed something with dot handling in filenames, or it was just some weird glitch. Can you check if this happens if you install time.is *with* the dot again?

**Comment by Patricek0056** [comment]
Even with the dot it is still not reproducible. I think, that there is maybe a problem with the “:” character, because it is a reserved character.
