### ISSUE TITLE
Allow wildcards in "Domains always allowed"

### ISSUE THREAD

**Issue by raleik-pl** [filips123/PWAsForFirefox#328]
### Problem Description

I want to have a pwa window for e.g. all google apps. Right now I need to specify all the domains, like this:
`mail.google.com,calendar.google.com,drive.google.com,accounts.google.com,meet.google.com,docs.google.com,myaccount.google.com,contacts.google.com,keep.google.com`
This list is not complete, i.e. there are domains that google apps jump to for authentication etc,

### Proposed Solution

I'd like a possibility to specify allowed domain with a wildcard, like this
`*.google.com`

### Additional Information
n/a

**Comment by filips123** [comment]
This will be added in the next release. Also, due to how wildcard matching works here, to match domains such as `mail.google.com`, `calendar.google.com` etc. **and** `google.com`, you will also need to include `google.com` domains separately (like `*.google.com,google.com`).
