### ISSUE TITLE
Linux: 'Failed to load storage: EOF while parsing a value at line 1 column 0'

### ISSUE THREAD

**Issue by hey-its-joao** [filips123/PWAsForFirefox#330]
### Steps to Reproduce

1. Go to 'PWAsForFirefox extension'
2. See error 'Failed to load storage: EOF while parsing a value at line 1 column 0'

### Additional Information

Hey, so, not sure what's up.  I'm using Xubuntu 22.04.2 and I had been using FirefoxPWA without any issue for a while.  Today I tried to install Reddit, and it seemed things froze up.  After this, all of my PWAs failed to open and the extension failed to operate, showing me the aforementioned 'Failed to load storage: EOF while parsing a value at line 1 column 0'.

I switched over to the terminal, where I get:

> [ERROR] Failed to load storage

> Caused by:
>    EOF while parsing a value at line 1 column 0

So that was strange.  I figured I'd try my best to figure something out.  So I uninstalled the runtime, uninstalled the extension, and purged firefoxpwa.  Then I figured I'd just install it all again.  Same thing.  Installation went fine, but same issues experienced.

"Well," I thought, "Maybe it's an issue with my Firefox installation."  I had been thinking of swapping the snap for the apt, so I did that.  I removed all the FirefoxPWA components again, uninstalled the snap, installed the apt, and tried to reinstall FirefoxPWA.  The connector failed to connect this time, but I don't know that it matters much as the terminal was still reading the same error as before.

"I'm probably in over my head," I muttered.  I have a degree in English.  I don't know what a computer is.  I figured I'd go back to square one again.  I uninstalled everything and the Firefox apt, I reinstalled the snap, and I reinstalled FirefoxPWA.  Back to basics, back to the original issue.

So like a toddler with a hammer, I did the only thing I know how to do.  Start writing 'sudo' a lot and see if things work or everything breaks.  Seems that when I run FirefoxPWA in the terminal with sudo, I don't get the "Failed to load storage" error.  While interesting, it means nothing to me because I still have no idea what's going on and still can't get the extension to work.

Finally then, after a workday spent dawdling around doing all this (don't get me wrong, it was more fun than the work I was supposed to be doing, so I'm not complaining), I figured it's time for be to give up and have someone with a little more experience and insight tell me the simple fix.

Thank you!

### Affected Websites

* Reddit?

### Environment

* Operating system: Xubuntu 22.04.2
* System architecture: x86_64
* Desktop environment: XFCE
* Installation method: DEB
* PWAsForFirefox extension version: 2.5.0
* PWAsForFirefox native version: 2.5.0
* Firefox version: 112.0.2 (64-bit), Mozilla Firefox Snap for Ubuntu, canonical-002 - 1.0

**Comment by filips123** [comment]
It seems that your config file has been corrupted for some reason, so it's not a valid JSON anymore and the program can't load it. 
Perhaps the program was killed just when writing the config file when you were installing Reddit, so it wasn't saved properly.

Can you check what's inside the config file? It's located in `$HOME/.local/share/firefoxpwa/config.json` (or `$XDG_DATA_HOME/firefoxpwa/config.json`).

**Comment by hey-its-joao** [comment]
Huh, that's interesting.  I looked in the config file, and it's completely empty.  Firefoxpwa log tells me the following (just the part that seems relevant excerpted):

> 14:11:41 [WARN] No required 48x48 icon is provided
> 14:11:41 [WARN] Generating it from other available icons
> 16:05:52 [ERROR] Failed to process icon

> Caused by:
>     0: Failed to load icon
>    1: The image format could not be determined
> 16:05:52 [WARN] Falling back to the next available icon
> 16:05:52 [WARN] No required 48x48 icon is provided
> 16:05:52 [WARN] Generating it from other available icons
> 19:18:40 [WARN] No required 48x48 icon is provided
> 19:18:40 [WARN] Generating it from other available icons
> 17:49:28 [WARN] No required 48x48 icon is provided
> 17:49:28 [WARN] Generating it from other available icons
> 17:49:28 [WARN] No compatible or working icon was found
> 17:49:28 [WARN] Falling back to the generated icon from the name
> 16:55:01 [WARN] No required 48x48 icon is provided
> 16:55:01 [WARN] Generating it from other available icons
> 17:27:17 [ERROR] Failed to process request

> Caused by:
>    0: Failed to parse web app manifest
>    1: Provided URL (https://www.redditstatic.com/) is not within the scope (https://www.reddit.com/)
> 17:30:55 [ERROR] Failed to process request

> Caused by:
>    0: Failed to parse web app manifest
>    1: Provided URL (https://www.redditstatic.com/) is not within the scope (https://www.reddit.com/)
> 17:32:11 [ERROR] Failed to process request

> Caused by:
>    0: Failed to parse web app manifest
>    1: Provided URL (https://www.redditstatic.com/) is not within the scope (https://www.reddit.com/)
> 17:34:44 [WARN] No required 48x48 icon is provided
> 17:34:44 [WARN] Generating it from other available icons
> 17:34:56 [ERROR] Failed to process request

> Caused by:
>    0: Failed to load storage
>    1: EOF while parsing a value at line 1 column 0
> 17:35:06 [ERROR] Failed to process request

**Comment by hey-its-joao** [comment]
I just renamed the firefoxpwa folder and reinstalled the runtime to recreate the folder.  It seems like it works again, I'll just have to re-add my webapps.  Not sure why the whole issue happened, but definitely happy that it seems like it can be fixed!  I'm absolutely in love with the project and I've already recommended it to friends.

**Comment by filips123** [comment]
Yeah, it probably got overwritten but I'm not sure why. I hope it won't happen again.

Also, if you just delete `config.json` but keep `profiles` and other stuff, you will still have to re-add your web apps, but they should keep your previous data (as long as they are installed to the same profile).

I'll close this issue as it seems like some one-time glitch that I cannot really fix. If it still happens in the future, I'll re-open it and try to fix the problem.
