### ISSUE TITLE
[Issue fixed, patch needed] Can't create a new PWA using template

### ISSUE THREAD

**Issue by FanderWasTaken** [filips123/PWAsForFirefox#337]
### Description

After adding path to a profile template I get an error and can't create a PWA

### Steps to Reproduce

1. Add a template path in extention settings
2. Try creating PWA
3. See error

### Additional Information

```
06:31:17 [INFO] Received a request: CreateProfile(CreateProfile { name: Some("GitHub"), description: None, template: Some("/home/niko/.local/share/firefoxpwa/profiles/Template") })
06:31:17 [INFO] Creating the profile
06:31:17 [INFO] Copying a profile template
06:31:17 [ERROR] Failed to process request

Caused by:
    0: Failed to copy a profile template
    1: No such file or directory (os error 2)
```

### Environment

* Operating system: Fedora 37
* System architecture: x86_64
* Desktop environment: KDE Plasma
* Installation method: [packagecloud](https://packagecloud.io/filips/FirefoxPWA)
* PWAsForFirefox extension version: 2.5.0
* PWAsForFirefox native version: 2.5.0-1
* Firefox version: 112.0.2 (64-bit)

**Comment by filips123** [comment]
Does the directory that you specified as a template (`/home/niko/.local/share/firefoxpwa/profiles/Template`) exist?

**Comment by FanderWasTaken** [comment]
> Does the directory that you specified as a template (`/home/niko/.local/share/firefoxpwa/profiles/Template`) exist?

Yes it does. The way I made it was that I created a PWA, set it up and copied the folder and changed it's name.

**Comment by filips123** [comment]
This is interesting... There are two things you can try. First, check if your template directory and files within it are readable by the `firefoxpwa`/`firefoxpwa-connector`. Second, check if a new empty profile directory is created just before this error occurs.

**Comment by dboy591** [comment]
Had the same issue. There is a file named lock inside your Template folder than needs deleted. Works now for me after deleting the lock file.

**Comment by FanderWasTaken** [comment]
> There is a file named lock inside your Template folder than needs to be deleted.

Yep, that fixed the issue.

**Comment by filips123** [comment]
I'll close this issue. Those files probably can't be removed automatically if they can't even be copied, so you will need to remove them manually. I also think they can only generate if you copy the directory while that profile is running, so the issue shouldn't happen if you close PWA before copying.

But I'll mention what to do in this case on a new documentation website that I'm preparing. More details in #335.
