### ISSUE TITLE
Unable to disable "icon bar"

### ISSUE THREAD

**Issue by gzpr** [filips123/PWAsForFirefox#350]
The instructions from  #49 do not work anymore since last update. Despite enabling `firefoxpwa.enableHidingIconBar` in `about:config` and enabling title bar and unticking "icon bar" the icon bar is still present. 

* Operating system: Linux
* System architecture: x86-64
* Desktop environment: GNOME
* Installation method: AUR
* PWAsForFirefox extension version: 2.6.0-1
* PWAsForFirefox native version: 2.6.0
* Firefox version: 113.0.2

**Comment by filips123** [comment]
Yes, there has been a regression in a recent release. I've already fixed this in e0e24a6a27dd7f1ce7f7a4d41a9aa1bedee9d9fb, but I haven't released it yet. I will probably release it today or tomorrow.

**Comment by filips123** [comment]
I'll close this issue, 2.6.1 wil a fix will be released soon.
