### ISSUE TITLE
Unable to install on VOID Linux

### ISSUE THREAD

**Issue by mcsk8r** [filips123/PWAsForFirefox#355]
Unable to install on VOID Linux

Steps to Reproduce

Followed instructions to make from source. When running 'makers install' error command not found 'makers'

Environment
* Operating system: VOID Linux
* System architecture: x64
* Desktop environment: GNOME
* Installation method: source
* PWAsForFirefox extension version: 2.6.1
* PWAsForFirefox native version: 2.6.1
* Firefox version: 114 

![Screenshot from 2023-06-08 13-15-11](https://github.com/filips123/PWAsForFirefox/assets/114460809/94074d48-7ab7-481d-a153-9bc35f75b2d6)

**Comment by filips123** [comment]
You need to install [`cargo-make`](https://github.com/sagiegurari/cargo-make) to make `makers` available.

**Comment by mcsk8r** [comment]
> You need to install [`cargo-make`](https://github.com/sagiegurari/cargo-make) to make `makers` available.

Any idea where I can get that from for VOID?

![image](https://github.com/filips123/PWAsForFirefox/assets/114460809/62607a33-c5b1-4a71-9ed4-8ec105a0e2f5)

**Comment by mcsk8r** [comment]
Answered my own question. https://github.com/sagiegurari/cargo-make

**Comment by filips123** [comment]
Yeah, if it's not available from your distro repos you can install it using Cargo or from GitHub releases. I'll close this issue now.
