### ISSUE TITLE
Cannot Install extension on Librewolf

### ISSUE THREAD

**Issue by SleeplessOne1917** [filips123/PWAsForFirefox#357]
### Description

I cannot install the extension on Librewolf, a fork of Firefox. I'm unsure if I should be opening this issue here or for that browser.

I am stuck on screen 2 of the extension setup wizard despite installing `firefox-pwa-bin` from the AUR. 

### Steps to Reproduce
1. Download Librewolf if you do not have it already
2. Open Librewolf, navigate to the [Firefox add-on page](https://addons.mozilla.org/en-US/firefox/addon/pwas-for-firefox/), and click "Add to Firefox"
3. When the extension auto-navigates you to the license agreement, accept it.
4. If you don't have it already, install `firefox-pwa-bin` from the AUR.
5. Get stuck on page 2 of the setup despite message saying the setup will automatically proceed.
6. Refreshing and closing and opening the browser again do nothing.

### Additional Information

It's worth noting that the extension worked just fine on vanilla Firefox that I got from the pacman repo. I encountered this issue specifically on Librewolf.

### Environment

Here's my neofetch results for system details:
```
            :::::::::::::::::::::::                insomnia@the-void
          .:^!!!!!!!!!^.^!!!!!!!!!^:.              -----------------
         .:~!!!!!!!!!!^.^!!!!!!!!!!~:.             OS: RebornOS Linux x86_64
        .:~!!!!!~~~~~~^.^~~~~~~!!!!!~:.            Host: Z370 AORUS Gaming 7
       .^!!!!!~::=====:.:=====::~!!!!!^.           Kernel: 6.3.6-arch1-1
     .::^~~!!~:^77777?~.~?77777^:~!!~~^::.         Uptime: 3 hours, 17 mins
    .:~~^:::^.^77777!!^.^7!77777^.^:::^~~:.        Packages: 1597 (pacman)
   .:~!!!!~::::^~!!::^^^^^::!!~^::::~!!!!~:.       Shell: fish 3.6.1
  .^!!!!!~::!7!~^:.^?JJJJJ?^.:^~!7!::~!!!!!^.      Display: 3840x2160 @ 60Hz
.:^!!!!!~:^77777~.~JJJJJJJJJ~.~77777^:~!!!!!^:.    DE: KDE Plasma 5.27.5
.:^!!!!!~:^77777~.~JJJJJJJJJ~.~77777^:~!!!!!^:.    WM: KWin (X11)
  .^!!!!!~::!7!~^:.^?JJJJJ?^.:^~!7!::~!!!!!^.      WM Theme: Breeze
   .:~!!!!~::::^~!!::^^^^^::!!~^::::~!!!!~:.       Theme: Breeze (Dark) [QT], Breeze [GTK2/3]
    .:~~^:::^.^77777!!^.^7!77777^.^:::^~~:.        Icons: breeze [QT], breeze [GTK2/3/4]
     .::^~~!!~:^77777?~.~?77777^:~!!~~^::.         Font: Noto Sans (10pt) [QT], Noto Sans (10pt) [GTK2/3/4]
       .^!!!!!~::=====:.:=====::~!!!!!^.           Cursor: breeze (24px)
        .:~!!!!!~~~~~~^.^~~~~~~!!!!!~:.            Terminal: konsole 23.4.2
         .:~!!!!!!!!!!^.^!!!!!!!!!!~:.             CPU: Intel(R) Core(TM) i7-8700K (12) @ 4.7 GHz
          .:^!!!!!!!!!^.^!!!!!!!!!^:.              GPU 1: NVIDIA GeForce GTX 1080 Ti
            :::::::::::::::::::::::                GPU 2: NVIDIA GeForce GTX 1080 Ti
                                                   Memory: 7.77 GiB / 31.17 GiB (24%)
                                                   Disk (/): 103 GiB / 2 TiB (5%)
                                                   Locale: en_US.UTF-8

```
Librewolf version: librewolf-bin 113.0-3 on pacman repo
Working Firefox version: firefox 114.0.1-1 on pacman repo
`firefox-pwa-bin` version: firefox-pwa-bin 2.6.1-1

**Comment by filips123** [comment]
LibreWolf looks for native manifests on a different location than Firefox, so it cannot find PWAsForFirefox's manifest by default.

You can symlink LibreWolf's location with Firefox's default location:

```bash
ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
sudo ln -s /usr/lib/mozilla/native-messaging-hosts /usr/lib/librewolf/native-messaging-hosts
```

Alternatively, you can copy `/usr/lib/mozilla/native-messaging-hosts/firefoxpwa.json` to `/usr/lib/librewolf/native-messaging-hosts/firefoxpwa.json`.

**Comment by SleeplessOne1917** [comment]
Thanks for the fast response. Is there a way to make the extension detect the correct directory to use automatically so that manual symlinking isn't needed?

**Comment by filips123** [comment]
The extension itself cannot detect the directory by itself as this is done by the browser. PWAsForFirefox just installs manifests to the location that is expected by normal Firefox, however, some Firefox forks (like LibreWolf) use custom directories.

Theoretically, PWAsForFirefox could install manifests to the location for LibreWolf, but I don't want to do this, as then I should probably also do this for every Firefox fork that uses its own directory, which would become too hard to manage and cause unnecessary duplicated files. I think that most other programs that use native messaging also only provide manifests for Firefox, and LibreWolf documentation also recommends [using symlinks](https://librewolf.net/docs/faq/#how-do-i-get-native-messaging-to-work) for this.

**Comment by soymadip** [comment]
> LibreWolf looks for native manifests on a different location than Firefox, so it cannot find PWAsForFirefox's manifest by default.
> 
> You can symlink LibreWolf's location with Firefox's default location:
> 
> ```shell
> ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
> sudo ln -s /usr/lib/mozilla/native-messaging-hosts /usr/lib/librewolf/native-messaging-hosts
> ```
> 
> Alternatively, you can copy `/usr/lib/mozilla/native-messaging-hosts/firefoxpwa.json` to `/usr/lib/librewolf/native-messaging-hosts/firefoxpwa.json`.

can you please mention this in installation page also. 
because i have the same problem as @SleeplessOne1917 and i was stuck for about 1 hour then  thought i should check closed issues......

if this is added in repo wiki or the screen 2 of extension setup wizard, it will be a huge lifesaver for new users....

**Comment by soymadip** [comment]
> 

and also i am facing one more problem. 
i don't have librewolf folder in /usr/lib/ directory

i am on Ubuntu 23.04 & librewolf native(.deb) package..

**Comment by lenntil** [comment]
Ref for OS specific location of Native manifests: [Native manifests location - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#manifest_location)
