### ISSUE TITLE
Installation of "firefoxpwa runtime install" on macOS not detected

### ISSUE THREAD

**Issue by dazdaz** [filips123/PWAsForFirefox#364]
Installation of "firefoxpwa runtime install" on macOS 13.4.1 / homebrew 4.0.28 / Firefox 115.0.1 (64-bit) not detected by PWA addon.

When I goto he installer here moz-extension://6077e062-a186-41be-9d4c-7d242fec22cc/setup/install.html
License Agreement and Connector Installation are installed and are highlighted with a Blue background, indicating installation successful.

The rutime installs correctly, however the installation is not detected, so I can't use PWA's within Firefox.

$ firefoxpwa runtime install
13:35:42 [WARN] This will download the unmodified Mozilla Firefox and locally modify it
13:35:42 [WARN] Firefox is licensed under the Mozilla Public License 2.0
13:35:42 [WARN] Firefox is a trademark of the Mozilla Foundation in the U.S. and other countries
13:35:42 [WARN] This project is not affiliated with the Mozilla Foundation in any way
13:35:42 [WARN] By using this project you also agree to the Firefox Privacy Notice: https://www.mozilla.org/privacy/firefox/
13:35:42 [WARN] Check the Firefox website for more details: https://www.mozilla.org/firefox/
13:35:42 [INFO] Downloading the runtime archive
13:35:45 [INFO] Extracting the runtime archive
13:35:45 [INFO] Attaching "hdiutil" "attach" "-plist" "/var/folders/72/03ts3p757ds6s3zfynvwtzv800qfj4/T/.tmpXEeesW"
13:35:54 [INFO] Status ExitStatus(unix_wait_status(0))
13:36:02 [INFO] Copying the runtime
13:36:02 [INFO] Runtime installed!
13:36:02 [INFO] Detaching (force: false): "hdiutil" "detach" "/dev/disk4s3"
13:36:02 [INFO] Status ExitStatus(unix_wait_status(0))

**Comment by filips123** [comment]
Are you on the "Connector Installation" step, where instructions to install the native program are displayed? If so, did you link the native messaging manifest as displayed after installation with Homebrew:

```sh
sudo mkdir -p "/Library/Application Support/Mozilla/NativeMessagingHosts"
sudo ln -sf "$HOMEBREW_PREFIX/opt/firefoxpwa/share/firefoxpwa.json" "/Library/Application Support/Mozilla/NativeMessagingHosts/firefoxpwa.json"
```

> License Agreement and Connector Installation are installed and are highlighted with a Blue background, indicating installation successful.

The last highlighted step is the current step, not the completed step. So, if only the license agreement and connector installation are highlighted, you are currently still on the connector installation step.

**Comment by dazdaz** [comment]
Thank you, I didn't see that text - perhaps add this into the Wiki too and also into the macOS page ?

**Comment by cronkenstein** [comment]
> Well, it says "Follow instructions displayed in the caveats section of installation output to link the manifest" in the instructions on the setup page, and these commands should also be displayed after you installed Homebrew package. Maybe I could also add those commands directly to the installation steps, but I'm not sure, because they might change depending on different Homebrew configurations.

Had a couple individuals running it today with brew and all you get after `Caveats`:

```
==> Caveats
zsh completions have been installed to:
/opt/homebrew/share/zsh/site-functions
```

**Comment by filips123** [comment]
Caveats are specified [in the formula](https://github.com/Homebrew/homebrew-core/blob/main/Formula/f/firefoxpwa.rb#L46-L61) and also displayed [on the website](https://formulae.brew.sh/formula/firefoxpwa), so I don't know why they are not displayed there. Maybe Homebrew has some flag to hide them?
