### ISSUE TITLE
Error when installing PWA with manifest of https://outlook.office.com/mail/

### ISSUE THREAD

**Issue by stollr** [filips123/PWAsForFirefox#374]
### Description

When I tried to install https://outlook.office.com/mail/ as PWA with the manifest I get an error. Even if i tried to do that with the cli. Installing it without the manifest worked fine.

### Steps to Reproduce

Running the following per CLI:

> firefoxpwa site install https://outlook.office.com/mail/manifests/pwa.json?culture=de --profile 01H63AD0B14H3PGW0JSSCAKCB1
> 06:52:21 [INFO] Installing the web app
> 06:52:21 [INFO] Downloading the web app manifest
> 06:52:21 [INFO] Parsing the web app manifest
> 06:52:21 [INFO] Installing system integration
> thread 'reqwest-internal-sync-runtime' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', /cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.18/src/into_url.rs:80:14
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'main' panicked at 'event loop thread panicked', /cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.18/src/blocking/client.rs:1150:5

### Affected Websites

https://outlook.office.com/mail/

### Environment

* Operating system: Debian Linux 11.7
* System architecture: amd64
* Desktop environment: KDE Plasma
* Installation method: deb
* PWAsForFirefox extension version: 2.7.2
* PWAsForFirefox native version: 2.7.2
* PWAsForFirefox runtime version: don't know where to find it :-(
* Firefox version: 102.13.0esr (64-Bit)

**Comment by filips123** [comment]
This is a known problem with Outlook. When using a non-English locale, Outlook's manifest will contain some broken icon URLs that will cause the program to panic:

```json
{
  "src": "https://{{CDN_HOST_NAME}}/assets/mail/pwa/v1/pngs/Outlook.48x48x32.png",
  "sizes": "48x48",
  "type": "image/png"
}
```

(Actually, the program shouldn't panic, but that's another bug with a used library, which I can't fix. But in any case, the main problem is that Outlook sends invalid URLs in manifest, and even without that bug in a library, you would still get an invalid icon.)

A good workaround is to install English version manifest from CLI:

```bash
firefoxpwa site install "https://outlook.live.com/mail/0/manifests/pwa.json/?culture=en"
```

This way, you will still get additional features such as shortcuts, although they will be in English.

This issue has already been reported in #353. Also, I'm preparing a new documentation website where issues like this will be documented. I've already [documented this one](https://github.com/filips123/PWAsForFirefox/blob/wip-documentation/docs/docs/resources/specific-website-tips.md#websites-with-invalid-manifests), although the whole documentation isn't ready and published yet.
