### ISSUE TITLE
Create default profile using template

### ISSUE THREAD

**Issue by www-wagner** [filips123/PWAsForFirefox#376]
### Problem Description

In current situation it isn't possible use a template to create the _Default_ profile. Only additional profiles follow the template setting.

### Proposed Solution

Possibility to apply the template defined in settings to the _Default_ profile.

### Additional Information

I've used the arkenfox project to create a hardened Firefox profile, so I would like to use it as a template to create other profiles, Firefox PWA including! If the Default profile followed the template defined in settings, this could be easier.

**Comment by filips123** [comment]
There will be an option to apply the template when editing an existing profile in the next release.
