### ISSUE TITLE
Ubuntu Mantic x86_64, browser doesn't detect runtime, reports "Error: An unexpected error occurred"

### ISSUE THREAD

**Issue by jikamens** [filips123/PWAsForFirefox#379]
### Description

Ubuntu Mantic x86_64, browser doesn't detect runtime, reports "Error: An unexpected error occurred"

### Steps to Reproduce

I just attempted to install and configure the extension on three different computers all running Ubuntu Mantic x86_64. It worked just fine with no hiccups on two of the three computers. On the third computer it's refusing to recognize that firefoxpwa is installed. The setup screen shows "Error: an unexpected error occurred" on the "Connector Installation" step.

I've confirmed firefoxpwa is installed on this computer and I can run it from a terminal window.

I've confirmed that the firefox snap version on this computer is the same as it is on the computers where things are working.

I've tried uninstalling and reinstalling the extension.

I've run the flatpak command given on your FAQ page for setting the native messing permission to true.

I've confirmed that native messaging is working, at least I believe I have, by visiting extensions.gnome.org and confirming that it is able to list my locally installed extensions, which I believe requires native messaging with the GNOME browser connector.

None of these have solved the problem.

Any other guidance about what may be preventing things from working on this particular computer and what I can do about it?

### Additional Information

Please tell me which log files to provide and I will gladly provide them.

### Affected Websites

N/A

### Environment

* Operating system: Ubuntu Linux
* System architecture: x86_64
* Desktop environment: GNOME
* Installation method: DEB
* PWAsForFirefox extension version: Current version as of 2023-08-03 when I installed it
* PWAsForFirefox native version: Current version as of 2023-08-03 when I installed it
* PWAsForFirefox runtime version: N/A since I'm not able to install the runtime
* Firefox version: 116.0 snap version is 116.0-2

**Comment by jikamens** [comment]
I also tried restarting the computer and then uninstalling and reinstalling the extension in Firefox, and that didn't help either.

**Comment by filips123** [comment]
Very interesting. I have no idea why it would work on two computers but not on the third...

You should provide extension and native logs with instructions from [here](https://pwasforfirefox.filips.si/help/troubleshooting/). You can also check if the native messaging manifests exists at `/usr/lib/mozilla/native-messaging-hosts/firefoxpwa.json` and points to `/usr/libexec/firefoxpwa-connector`, and that the connector exists and is executable. If you haven't already, you can also try to reinstall the DEB package. You can also try to use it with non-Snap Firefox, to test if the problem is with PWAsForFirefox installation or somewhere in Snap.

Other than that, I don't know why this happened and how to fix it. I'll let you know if I find anything else.

**Comment by jikamens** [comment]
Extension logs attached.
[extension logs.txt](https://github.com/filips123/PWAsForFirefox/files/12253931/extension.logs.txt)

There are no native logs, I don't think it's ever successfully activating the connector so nothing gets logged.

The manifest exists and looks correct.

The connector exists and is executable.

Reinstalling the DEB did not help.

Firefox downloaded from Mozilla _does_ work.

I checked the output of `snap connections firefox` on a working and non-working computer and they're identical.

Thanks for looking at this.

**Comment by filips123** [comment]
You can try asking on Ubuntu forums or somewhere with Ubuntu-specific support/problem reports. [This](https://discourse.ubuntu.com/t/call-for-testing-native-messaging-support-in-the-firefox-snap/29759/111) is is the forum topic from when they were still testing Native Messaging in Snap, so maybe you can ask there, although it's quite old and mostly inactive.

Also, in that topic, someone mentioned logs from Firefox startup, so if you can get them, they might be useful.

**Comment by jikamens** [comment]
Posted about it here: https://discourse.ubuntu.com/t/call-for-testing-native-messaging-support-in-the-firefox-snap/29759/117?u=jik

Also as noted there I wrapped the connector in a script that captures inputs and outputs and confirmed that Firefox isn't actually invoking the connector.

**Comment by yllekz** [comment]
Same here but on macOS. Runtime installed, Firefox/the extension aren't detecting it, even after symlinks are present and browser restarted.

**Comment by jikamens** [comment]
> Same here but on macOS. Runtime installed, Firefox/the extension aren't detecting it, even after symlinks are present and browser restarted.

This is likely to be a different issue from my Ubuntu issue, so you should probably open a new issue about it rather than commenting about your issue on this one.

**Comment by filips123** [comment]
@yllekz Yes, please open a new issue about that.

**Comment by jikamens** [comment]
This appears to be a Firefox snap bug of some sort so I've opened an issue with Mozilla about it (since they maintain both the snap and Firefox): https://bugzilla.mozilla.org/show_bug.cgi?id=1847377

**Comment by reinouts** [comment]
I have a similar issue with Firefox 117.0.1 on Fedora 38. I get 'an unexpected error occurred' when trying to install Outlook as PWA. The issue seems to be that `thread 'reqwest-internal-sync-runtime' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', /cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.18/src/into_url.rs:80:14`
I am attaching the debug logs. 
[firefoxpwa.log](https://github.com/filips123/PWAsForFirefox/files/12725157/firefoxpwa.log)
[firefoxpwa-stderr.log](https://github.com/filips123/PWAsForFirefox/files/12725160/firefoxpwa-stderr.log)
[firefoxpwa-stdout.log](https://github.com/filips123/PWAsForFirefox/files/12725162/firefoxpwa-stdout.log)

**Comment by filips123** [comment]
This is an issue with the manifest that Outlook provides. You will need to install the English manifest from the command line. You can see the instructions [here](https://pwasforfirefox.filips.si/resources/specific-website-tips/#websites-with-invalid-manifests).

**Comment by reinouts** [comment]
> This is an issue with the manifest that Outlook provides. You will need to install the English manifest from the command line. You can see the instructions [here](https://pwasforfirefox.filips.si/resources/specific-website-tips/#websites-with-invalid-manifests).

Thank you. I didn't find this in the FAQ. It would be even better if the extension would automatically do the right thing for these specific two websites instead of throwing an error without any details to go on.

**Comment by stark1tty** [comment]
I am also having this problem.

**Comment by filips123** [comment]
This is very likely a bug with Firefox or Snap. You can instead install Firefox manually or from their [APT repository](https://support.mozilla.org/en/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions).

**Comment by matteof04** [comment]
I've got the same issue with Firefox installed via Snap on Ubuntu 24.04, after the command
```
dbus-send --print-reply \
    --dest=org.freedesktop.impl.portal.PermissionStore \
    /org/freedesktop/impl/portal/PermissionStore \
    org.freedesktop.impl.portal.PermissionStore.SetPermission \
    string:'webextensions' \
    boolean:'true' \
    string:'firefoxpwa' \
    string:'snap.firefox' \
    array:string:'yes'
```
the problems was fixed.
I've found this [here](https://askubuntu.com/questions/1466483/is-there-an-equivalent-snap-command-to-the-flatpaks-permission-show-and-perm). Hope it helps other users.
