### ISSUE TITLE
PWA doesn't need fission, disabling it to save a lot of RAM

### ISSUE THREAD

**Issue by GunGunGun** [filips123/PWAsForFirefox#386]
### Problem Description

PWA apps still use quite decent amount of RAM because it's Firefox with Fission enabled by default but single web application doesn't need protection from fission (multiprocessing) because we only open 1 single webpage, we're immune to Spectre and Meltdown, we should have an option or disable fission by default

### Proposed Solution

Just set `about:config` `fission.autostart` to `false` and `dom.ipc.processCount` to `1`

### Additional Information

Nothing

**Comment by filips123** [comment]
There can still be multiple web apps running in the same profile at the same time. Additionally, web apps can use (i)frames where Fission is still useful for isolation. Besides that, from quick testing, it doesn't reduce the RAM usage that much, so I don't think it's worth trading security for a bit more unused RAM.

You can still manually disable Fission in `about:config` if you want. You may also want to use profile templates if you want to do this automatically for all new profiles.
