### ISSUE TITLE
Web apps stop working after updating to Firefox 117 (solution here)

### ISSUE THREAD

**Issue by HiroDane** [filips123/PWAsForFirefox#388]
### Description

When I try to open any web app it just opens up a completely white window, even without the usual close, minimize or maximize button, just completely blank and pure white. I have tried uninstalling and reinstalling everything from scratch but nothing changes. The extension also keeps saying its out of date even though I explicitly installed the latest msi. I tried 2 other ways to install also which were: through choco and through winget. Still same issue.

### Steps to Reproduce

1. Go to 'Firefox Extension'
2. Click on 'Launch for any installed WebApp'

### Additional Information

I have tried restarting browser and the system, did not change anything.
When I try to edit a WebApp I get an error about invalid icon. I tried to give the icon URL manually but when I click the 'Edit' button and leave the edit menu it resets back to invalid url for icon error.

### Affected Websites

All websites have same issue, for example youtube.com

### Environment

* Operating system: Windows 10 version 10.0.19045 Build 19045
* System architecture: x64
* Desktop environment: Windows
* Installation method: MSI
* PWAsForFirefox extension version: 2.7.3
* PWAsForFirefox native version: 2.7.3
* PWAsForFirefox runtime version: 2.7.3
* Firefox version: 117.0

**Comment by filips123** [comment]
Does it work if you enable "Always patch runtime and profile" in the extension settings and then launch PWAs?

**Comment by lwindolf** [comment]
Had the same problem during the Firefox 116 -> 117 upgrade. Running "Update web apps" from the settings menu fixed the issue for me and all web apps startet to work again.

**Comment by filips123** [comment]
I added compatibility with Firefox 17 in [v2.7.3](https://github.com/filips123/PWAsForFirefox/releases/tag/v2.7.3). I don't know why the fix didn't automatically apply to all web apps as it should. Maybe it's the same issue as #165.

**Solution for this issue:** After updating to PWAsForFirefox 2.7.3 and Firefox 117, run "Update web apps" from the extension settings to apply the fix.

**Comment by HiroDane** [comment]
Tried "Update web apps", the issue persists. still completely blank window opens up. I also noticed that the extension detects native version as 2.0.3 even though I manually installed the latest msi from release page. May be related somehow. idk.

**Comment by filips123** [comment]
Hmm, this is something else. Have you installed PWAsForFirefox per user (instead of per machine)? If so, maybe you have two installations, one per user and one per machine, and one of them is actually outdated.

**Comment by HiroDane** [comment]
As far as I remember multiple installs should not be the case, but what do I do to check? I looked through all AppData folders and only one user account has FireFoxPWA. 
Also I tried to launch through command line and same thing happens. In command line I could verify that version was 2.7.3. Is there a cmd way to do "Update web apps"?

**Comment by filips123** [comment]
You can try to completely uninstall PWAsForFirefox and its registry keys:

1. Run the normal uninstaller.
2. Delete `HKCU\Software\Mozilla\NativeMessagingHosts\firefoxpwa` and `HKLM\Software\Mozilla\NativeMessagingHosts\firefoxpwa` registry keys.
2. Delete `HKCU\Software\filips\FirefoxPWA` and `HKLM\Software\filips\FirefoxPWA` in registry.
3. Delete `C:\Program Files\FirefoxPWA` and `%LOCALAPPDATA%\Programs\FirefoxPWA`.

If any of HKCU keys existed, you probably had an old per-user install. After you remove those directories and keys, you can try to install PWAsForFirefox again.

**Comment by HiroDane** [comment]
Yes this was the issue, I guess i tried three different ways to install and one of them ( i am guessing chocolatey) made a user only install that was messing with things. Thank you so much!

**Comment by filips123** [comment]
Good to see that you fixed this. I'll close this issue then.

**Comment by fungs** [comment]
Same problem here, reinstalling the runtime and updating the webapps worked, but only for those that I didn't open while the bug existed. I had to remove and reinstall those apps/profiles.
