### ISSUE TITLE
Disable "Firefox Private Browsing" shortcut

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#393]
Hi, I'm using the PortableApps version of PWAsForFirefox on my SSD flash.
After running the YouTube PWA, I noticed that a shortcut was created in the start menu.

![image](https://github.com/filips123/PWAsForFirefox/assets/23485114/866cc271-94c6-4780-a6aa-9b4b7d40c911)

![image](https://github.com/filips123/PWAsForFirefox/assets/23485114/260ad297-7c8e-40db-8da7-cdf7dcfe84f5)

I have not found any way to solve this problem!

**Comment by filips123** [comment]
Can you check if `browser.privateWindowSeparation.enabled` is enabled in `about:config`? It should be `false` by default, but maybe it wasn't set correctly.

**Comment by filips123** [comment]
I also made additional changes that are more likely to properly disable this shortcut, so I'll close this issue. This changes will be released in the next version.

**Comment by xmha97** [comment]
Thanks

**Comment by xmha97** [comment]
This issue still exists and should be opened. @filips123
