### ISSUE TITLE
Favicons/Thumbnails are not catched correctly when installing PWAs without app manifests

### ISSUE THREAD

**Issue by v3DJG6GL** [filips123/PWAsForFirefox#396]
### Description

As already described in the title: When I install new web pages that don't have app manifests, the thumbnail/favicon is somehow not added correctly. There is an option to specify the favicon manually, but that does not work either.

But within the PWA plugin the icons are displayed correctly:
![image](https://github.com/filips123/PWAsForFirefox/assets/72495210/59a6f707-7361-40dc-a99e-ed10e25e59f3)

However, the icon is not visible outside the plugin:
![image](https://github.com/filips123/PWAsForFirefox/assets/72495210/6a876d91-d37e-415f-a80b-0fc70834128d)
![image](https://github.com/filips123/PWAsForFirefox/assets/72495210/99bd5771-74e4-4b7f-801d-d127616b48ac)
![image](https://github.com/filips123/PWAsForFirefox/assets/72495210/0803b218-78c7-4dc9-b39f-f923bbe673b9)

This problem only occurs with websites that do not provide native support for PWA (or at least do not provide a manifest)
With Nextcloud, for example, the icons are displayed correctly in Windows:
![image](https://github.com/filips123/PWAsForFirefox/assets/72495210/da8862fa-c76d-4e53-a4a1-57bc0e4e1913)

### Steps to Reproduce
1. install a website as a PWA that does not provide native PWA support/manifest.
2. it doesn't matter if you provide a direct link to a favicon or not: these PWAs will not display their favicon outside the plugin management window.

### Additional Information

-

### Affected Websites

Every website who doesn't provide an app manifest.

### Environment
* Operating system: Windows 10 Pro & Windows 11 Pro
* System architecture: x64
* Installation method: MSI (Winget)
* Extension version: 2.7.3
* Native version: 2.7.3
* Runtime version: 117.0-1
* Firefox version: 116.0.3-1

**Comment by filips123** [comment]
Can you provide a website where this happens? I tried on a few websites that aren't PWAs and icons still work fine.

**Comment by v3DJG6GL** [comment]
It's kinda difficult since those apps are mostly hosted on my own server behind a reverse proxy and Authelia as authentication and some are even locally installed.
I just checked and I didn't found any hosted demo sites which you could use for testing.

Here is a list of the affected apps:

- TrueNAS SCALE (NAS/Server/Cloud) --> https://www.truenas.com/download-truenas-scale/
- OPNsense (Hardware Firewall) --> https://opnsense.org/download/
- Acronis Cyber Protect (locally deployed backup software) --> https://www.acronis.com/de-de/products/cyber-protect/
- qBittorrent (Cloud App) --> https://truecharts.org/charts/stable/qbittorrent/

**Comment by filips123** [comment]
Icons are downloaded by the native program, which does not share sessions and cookies with the browser. Maybe it can't download icons because they are protected by Authelia. You can [check native logs](https://pwasforfirefox.filips.si/help/troubleshooting/#obtaining-native-logs) if there are any such errors.

If this is the case, can you configure Authelia to allow access to icons even without authentication?

**Comment by v3DJG6GL** [comment]
alright, that makes totally sense!
I thought the favicons are catched either from within the main browser or from the PWA specific browser inside the selected profile.
ANd yes, I get those errors:
`Caused by:
    0: Failed to load raster icon
    1: The image format could not be determined
19:53:39 [WARN] Falling back to the next available icon
19:53:39 [DEBUG] (1) firefoxpwa::integrations::utils: Processing icon https://DOMAIN.com/favicon.png
19:53:39 [DEBUG] (2) reqwest::async_impl::client: redirecting 'https://DOMAIN.com/favicon.png' to 'https://auth.DOMAIN.com/?rd=https%3A%2F%2FDOMAIN.com%2Ffavicon.png&rm=GET'
19:53:39 [DEBUG] (1) firefoxpwa::integrations::utils: Processing as raster icon
19:53:39 [ERROR] Failed to process icon`

> If this is the case, can you configure Authelia to allow access to icons even without authentication?
Yes, I might be able to do that with RegEx and so on.

Thanks alot for the hint!
