### ISSUE TITLE
Couldn't load COM

### ISSUE THREAD

**Issue by desbest** [filips123/PWAsForFirefox#397]
### Description

When I try to open a PWA I made, I get this error.

![pwa for firefox error couldn't load com](https://github.com/filips123/PWAsForFirefox/assets/1139316/e4367932-0661-4e12-b835-03246a089c4c)

### Steps to Reproduce

1. Go to https://example.com
2. Create a PWA by clicking the "install web app" button on the extension. Don't change any settings.
3. Open the app
4. The error appears

### Affected Websites

It affects every website, including https://example.com

### Environment

* **Operating system:** Windows 11 22H2
* **System architecture:** 64 bit
* **Installation method:** MSI
* PWAsForFirefox extension version: 2.7.3
* **PWAsForFirefox native version:** 2.7.3
* **PWAsForFirefox runtime version:** 117.0.1
* **Firefox version:** 117.0.1

* **Antivirus Software:** Comodo Internet Security

**Comment by filips123** [comment]
Please try to reinstall the runtime from the extension settings. Then, enable "always patch runtime and profile" in the settings and launch a web app again. Also, try to install a web app info a new profile.

**Comment by desbest** [comment]
It works now. Thank you for your help.
