### ISSUE TITLE
Scripting: Open and close a program before launching and after exiting PWA

### ISSUE THREAD

**Issue by LSeelig** [filips123/PWAsForFirefox#398]
### Problem Description

 Yes.
 

There are some programs that use web app interfaces while running the program/server either on the user's machine or remotely. While it is simple enough to install the webpage as a PWA, the cli program that serves the content must be opened and closed separately.

I am trying to do this with code serve-web. The electron application for VSCode has graphical bugs and runs poorly on my system. Running the UI in the browser/as a PWA and running the server in the background is much better, but it requires me to manually start and stop the server.

### Proposed Solution

In the PWA settings/config, users should be able to select "script" or "process" option that runs a command provided by the user and stops it when the PWA is closed.

I tried writing a bash script to accomplish this, but it was surprisingly complex. I had trouble getting the process (code serve-web --without-connection-token) to run in the background and to close when the last active window of the PWA was closed. Since I am very inexperienced, I realize there may be a better way to do it. I am aware I cannot judge the merit, importance, and practicality of this, so if this gets removed or shelved, I understand.

### Additional Information

As I said before, I am aware I might be barking up the wrong tree. This approach seems like a way to give PWAs and web apps a lot of power without resorting to electron.

 No, sorry. I am a beginner, not a dev.

**Comment by filips123** [comment]
This seems to be the same request as #145, so I'll close this issue. I'm not against it, but it's not a priority for now, as it would be quite complex to implement, especially stopping the program after exiting PWAs. I will probably try to implement it in the future, but I don't know when.
