### ISSUE TITLE
Version 2.8.0 Not found

### ISSUE THREAD

**Issue by tismofied** [filips123/PWAsForFirefox#402]
### Description

No version 2.8.0 is available 
### Steps to Reproduce
puting cmd in windows terminal with winget and returns  `no version 2.8.0 available`

1. Go to '....'

### Affected Websites

* ...
* ...

### Environment

* Operating system: windows 11 23H2 build 25951.1010
* System architecture:
* Desktop environment: 
* Installation method: 
* PWAsForFirefox extension version:
* PWAsForFirefox native version:
* PWAsForFirefox runtime version:
* Firefox version: 118.0.1

`C:\Users\T***>winget install firefoxpwa --version 2.8.0
Found an existing package already installed. Trying to upgrade the installed package...
No version found matching: 2.8.0`

**Comment by filips123** [comment]
The PR to update winget package (microsoft/winget-pkgs#121520) hasn't been merged yet. Until it's merged, you can install the program manually using the MSI installer.
