### ISSUE TITLE
Option to delete profile when deleting its last PWA

### ISSUE THREAD

**Issue by iTrooz** [filips123/PWAsForFirefox#407]
### Problem Description

When deleting a PWA, the profile used for it isn't deleted, even if it doesn't host any other PWAs

### Proposed Solution

A enabled-by-default checkbox that says "Delete the associated profile ?" when deleting the last PWA of a profile (if there are other PWAs in the profile, the checkbox would not appear)

I'd be ready to submit a PR for this (no promise tho), but I want your approval first, so I'm waiting for your response

**Comment by filips123** [comment]
This feature would be fine.

**Comment by iTrooz** [comment]
In the message "Are you sure you want to remove this web app? App data will <strong>not</strong> be removed, but you can remove them through the app browser or by deleting app's profile.", what is this "app browser" you are talking about ?

**Comment by filips123** [comment]
The "app browser" is the Firefox runtime that is used for PWAs (that one that is downloaded by the native program and patched with UserChrome modifications).
