### ISSUE TITLE
Thunderbird Addon

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#408]
Hi, the Firefox addon of `PWAsForFirefox` can be installed on Thunderbird.

![image](https://github.com/filips123/PWAsForFirefox/assets/23485114/433394b0-76ca-42a6-842d-16d8697fc90b)

But it doesn't work :(
Please create an addon for Thunderbird 
Thanks

**Comment by filips123** [comment]
How did you install it to Thunderbird, as it isn't available on the Thunderbird store? Also, what exactly doesn't work? I tried installing it from file and it seems to work fine.

**Comment by filips123** [comment]
I will close the issue as the extension seems to work fine even in Thunderbird.
