### ISSUE TITLE
Using template profile makes extensions not work properly

### ISSUE THREAD

**Issue by lenntil** [filips123/PWAsForFirefox#428]
### Description

Overwritten titlebar, toolbar, overflowmenu configuration makes PWA work unintended way.
- Launching extension by pressing icon in titlebar, toolbar, overflowmenu does work
- Extension list icon(puzzle shaped one) does not appear and cannot be added from `Customize Toolbar` feature.
- `Restore to Defaults` from `Customize Toolbar` feature does not fix this issue

### Steps to Reproduce

1. Create default profile in `about:profiles`
3. Open the profile in new window and install any extensions(e.g., uBlock Origin).
4. Set the profile as template
5. Create PWA in any website(e.g., YouTube)

### Additional Information

Without using template also makes similar issue sometimes, but restarting solve the issue.

### Affected Websites

All (Tested with 6 sites)

### Environment

* Operating system: macOS
* System architecture: M1 Pro
* Desktop environment: 
* Installation method: 
* PWAsForFirefox extension version: 2.9.0
* PWAsForFirefox native version:
* PWAsForFirefox runtime version:
* Firefox version: 120.0.1

**Comment by filips123** [comment]
Can you check [the runtime logs](https://pwasforfirefox.filips.si/help/troubleshooting/#obtaining-runtime-logs)?

**Comment by filips123** [comment]
I was able to reproduce this partially. However, after restoring to default and restarting the web app, it started working fine. Does this also happen to you?

**Comment by lenntil** [comment]
> It's recommended to create a template in the PWAsForFirefox's runtime.

I created profiles in `about:profiles` page and it was the problem.

**No-problem steps I used:**

1. Go to PWAsForFirefox: [https://pwasforfirefox.filips.si/](https://pwasforfirefox.filips.si/).
2. Run `Install current site` on the page.
3. Set the created profile path as the template path.
    - For me, it was `/Users/username/Library/Application Support/firefoxpwa/profiles/01HH6EZ1AGV1RDMK18DDAVG62Y` (macOS).
4. Launch the app created in step 2 and set up the template, e.g., install extensions, configure settings, etc.

**Comment by filips123** [comment]
> I created profiles in `about:profiles` page and it was the problem.

Yeah, this can happen in this case as not all PWAsForFirefox modifications are applied to the profile. There is probably nothing I can do in this case, so I'll close the issue.
