### ISSUE TITLE
Apps Crashing on opening

### ISSUE THREAD

**Issue by lunacerberus** [filips123/PWAsForFirefox#432]
### Description
Web apps crash on opening. This happened after opening a webapp and going to customize the toolbar, and closing the webapp before clicking done.

### Steps to Reproduce

1. Right click toolbar in webapp
2. Customize toolbar
3. Close Webapp
4. Try opening webapp
5. See error

### Affected Websites

* ...
* ...

### Environment

* Operating system:
* System architecture:
* Desktop environment: 
* Installation method: 
* PWAsForFirefox extension version:
* PWAsForFirefox native version:
* PWAsForFirefox runtime version:
* Firefox version:

**Comment by filips123** [comment]
I can reproduce this issue. It's probably caused by a Firefox bug with session restore.

To fix your web apps, you can remove `sessionstore-backups`, `sessionCheckpoints.json` and `sessionstore.jsonlz4` in your web app's profile.
