### ISSUE TITLE
Can't Install Extensions

### ISSUE THREAD

**Issue by UndarkAido** [filips123/PWAsForFirefox#434]
### Description

I can't install extensions

### Steps to Reproduce

1. Attempt to install an extension from addons.mozilla.org or manually from about:addons
2. Observe as the spinner goes forever (addons.mozilla.org) or nothing happens (about:addons)

### Additional Information

```
Twice on addons.mozilla.org reload:
Unable to find target with innerWindowId:10737418242 watcher.js:188:13
    getWindowGlobalTargetByInnerWindowId resource://devtools/client/fronts/watcher.js:188
    _getTargetForWatcherResource resource://devtools/shared/commands/resource/resource-command.js:905
    _onResourceUpdated resource://devtools/shared/commands/resource/resource-command.js:780
    _emit resource://devtools/shared/event-emitter.js:242
    emit resource://devtools/shared/event-emitter.js:186
    emit resource://devtools/shared/event-emitter.js:330
    onPacket resource://devtools/shared/protocol/Front.js:349
    onPacket resource://devtools/client/devtools-client.js:471
    send resource://devtools/shared/transport/local-transport.js:67
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103
Twice on addons.mozilla.org or about:addons install:
TypeError: aWindow.document.getElementById(...) is null 2 browser-addons.js:1271:41
```

### Affected Websites

* https://addons.mozilla.org/
* about:addons

### Environment

* Operating system: Windows 11
* System architecture: 64-bit
* Desktop environment: 
* Installation method: `winget`/MSI
* PWAsForFirefox extension version: 2.9.1
* PWAsForFirefox native version: 2.9.1
* PWAsForFirefox runtime version: 120.0.1
* Firefox version: 120.0.1

**Comment by alchzh** [comment]
Do you have `enableHidingIconBar` set in `about:config` and the icon bar hidden? I think the error you see is Firefox trying to find the extension button on the icon bar but not finding it. Easy to fix, just unhide the icon bar for a second when you are installing the extension.

**Comment by filips123** [comment]
Yeah, this might be the problem. I also tried to reproduce this issue in a fresh profile with default toolbar configuration, and it worked fine.

**Comment by itsoulos** [comment]
Problem solved (partially)! I have installed librewolf instead firefox esr and the problem solved
Now I have faced another problem. The librewolf demands many GB of ram but I think that is because I have only 8GB of ram

**Comment by filips123** [comment]
@itsoulos It seems like that was an issue with Firefox ESR. Maybe it was already fixed in newer versions of Firefox, but not yet in ESR, or only in LibreWolf specifically. So, you should probably report it to maintainers of Firefox ESR package for Asahi. Regarding RAM usage, it's probably also an issue with LibreWolf, and I think I can't do anything about it.

**Comment by UndarkAido** [comment]
> Do you have `enableHidingIconBar` set in `about:config` and the icon bar hidden? I think the error you see is Firefox trying to find the extension button on the icon bar but not finding it. Easy to fix, just unhide the icon bar for a second when you are installing the extension.

That was the issue, I didn't have an extension button!

**Comment by filips123** [comment]
I will add a warning to the documentation that installing extensions (and other popups) might not work if the icon bar is hidden. In the future, I will maybe also try to fix this properly.

**Comment by UndarkAido** [comment]
Oh the problem was the missing extension icon, I don't have the icon bar hidden.

**Comment by filips123** [comment]
Interesting, I thought the popup anchor is moved to another element if the extensions button is hidden. I will check if I can fix that.

But I will still add that warning to the documentation, as the problem can still happen in that case.
