### ISSUE TITLE
Profile ID reported by the extension does not match the ID in ~/.local/share/firefoxpwa/profiles

### ISSUE THREAD

**Issue by winteriscariot** [filips123/PWAsForFirefox#436]
Arch Linux

When I create a webapp, it creates a new profile in ~/.local/share/firefoxpwa/profiles

However, this profile ID does not match the ID as reported in the extension drop-down. This makes it troublesome to find the correct profile when doing something eg modifying userChrome.css

Is it possible to make the ID in the extension match the profile ID in ~/.local/share/firefoxpwa/profiles ? Or maybe add a button to 'open profile in file manager' so we can get directly easily and unambiguously?

**Comment by filips123** [comment]
> However, this profile ID does not match the ID as reported in the extension drop-down.

Do you mean the ID that is displayed in the "edit web app" page in the extension? That is the web app ID, not the profile ID, so it's normal that they are different. You can view the actual profile ID in the profiles section of the extension.

However, if you are already viewing the profile ID in the profiles section, but it still doesn't match, this could be a bug.
