### ISSUE TITLE
Microsoft Teams Individual Call Cannot be Initiated

### ISSUE THREAD

**Issue by work-flower** [filips123/PWAsForFirefox#440]
### Description
Although it's possible to initiate a call from FireFox it's not possible to do the same from PWA application. I believe it should be related with a few settings need to be done in PWA app but couldn't find what it is/are.

### Steps to Reproduce

1. Install Microsoft Teams as PWA by using FireFox
2. Open Teams PWA
3. Navigate to a Person
4. Hit Call button or try to hit Video Call button

### Affected Websites

* https://teams.microsoft.com

### Environment

* Operating system: Ubuntu
* System architecture: 64 Bit
* Desktop environment: GNOME 42.9 - Wayland
* Installation method: source: https://packagecloud.io/filips/FirefoxPWA/any
* PWAsForFirefox extension version: 2.9.1
* PWAsForFirefox native version: 2.9.1
* PWAsForFirefox runtime version: 2.9.1
* Firefox version: 121 (64 Bit)

### Ubuntu Details
![image](https://github.com/filips123/PWAsForFirefox/assets/27060067/aab7e3e4-83b4-4539-a14c-c96bab993db1)

### Teams PWA Screenshots
![image](https://github.com/filips123/PWAsForFirefox/assets/27060067/711f028b-ced3-4f2a-a423-2a9b49d57ae9)
![image](https://github.com/filips123/PWAsForFirefox/assets/27060067/d6bab84c-2636-4bd6-a97f-a3f97e505b5c)

**Comment by work-flower** [comment]
just an update, I think we can close this issue as this is a limitation imposed by Microsoft. Firefox doesn't support individual calls but you can join on a conference calls. Strange! :-1:

**Comment by filips123** [comment]
Maybe you can get around this limitation by using user-agent switchers.

**Comment by work-flower** [comment]
> Maybe you can get around this limitation by using user-agent switchers.

That's what I did but now having microphone feedback 😀 though not sure if it's because of the browser or my computer. Will check it and write here

**Comment by WMarks-Enertech** [comment]
I had to switch to using a Chrome/Windows user-agent just to get Teams to open.
