### ISSUE TITLE
Ctrl+W closes the PWA

### ISSUE THREAD

**Issue by bam80** [filips123/PWAsForFirefox#443]
### Description
The Ctrl+W shortcut is intercepted by browser and closes the PWA (as it's default shortcut to close a tab), even if it's used by the PWA itself.  

### Steps to Reproduce

1. Open any installed PWA. Good example - Github's Codespaces.
2. Press Ctrl+W
3. The PWA window closes immediately
 
### Additional Information
There is no such problem with Chromium PWAs - tabs in Chromium are also closed by Ctrl+W, but PWAs there handle the shortcut correctly and do not close the window.

### Environment

* Operating system: Ubuntu 23.04
* Desktop environment: Gnome
* Installation method: DEB
*    Extension version: 2.9.1
*    Native version: 2.9.1
*    Runtime version: 121.0.1
*    Firefox version: 121.0

**Comment by bam80** [comment]
I see there is a https://github.com/filips123/PWAsForFirefox/commit/ac5032fe0b9a43e19c13476c1a26a896db037e33 but maybe make the default behavior in-sync with the Chromium one, to not confuse the users?

**Comment by bam80** [comment]
Well, as it's an "application" now it's more expected it would want to handle such combination itself.
Also, I think it's still better to keep this behavior consistent between  different PWA vendors, as casual user shouldn't care much which vendor provides the PWA but just expects consistent behavior of the app itself.
My 2 cents.

**Comment by bam80** [comment]
> I may add another option for this

Let's make task/issue for that to track?

**Comment by filips123** [comment]
Ok, I will create it soon.

**Comment by filips123** [comment]
I created #446. Also, please comment there if you know any other shortcuts that are commonly used in PWAs and conflict with built-in Firefox options (apart from ones already on the list).
