### ISSUE TITLE
Feature request: Support for opening links in PWA not in the PWA-specific profile

### ISSUE THREAD

**Issue by justin13888** [filips123/PWAsForFirefox#448]
### Problem Description

Because PWAs are ran in a separate Firefox profile, all links opened in the PWA will be opened as another profile. This is typically okay for apps like Spotify where you don't really need to open links other than what's already in spotify. But let's say you use an email app as a PWA, and open dozens of links to work websites, you wouldn't be logged into any of that and that starts to get quite tedious.

### Proposed Solution

While I agree running PWAs in separate Firefox profile is a rationale design decision, it would be useful to have all links open to your main firefox profile (where extension is installed) or just open it through OS' link handler. These are two options that may or may not be easily feasible but it was definitely improve the experience of PWAs where you open external links many times.

A third option I could think of would be to let PWAs run in the same profile but as written in the README, it seems to be a unpreferable option by some.

**Comment by filips123** [comment]
This sound like the [open out-of-scope URLs in a default browser](https://pwasforfirefox.filips.si/user-guide/browser/#open-out-of-scope-urls-in-a-default-browser) option. If it's enabled, any out-of-scope URLs (except allowed domains) will be opened in a default system browser.

**Comment by justin13888** [comment]
Thanks for the tip! I read over the whole documentation again. I configured the setting you mentioned but I suggest making it more clear in the documentation page on how to configure those App Browser settings.

I found the first comment in this post about it most useful: https://www.reddit.com/r/firefox/comments/11guvel/pwa_and_webapps_in_firefox_issue_regarding/

So specifically, on top of that page (https://pwasforfirefox.filips.si/user-guide/browser/), I'd specify it's found in the Settings access through hamburger menu in PWA.

Additionally, is it possible to disable this prompt? it's very tedious to click on it everytime.

![image](https://github.com/filips123/PWAsForFirefox/assets/20733699/2fe75dec-4e54-4ab1-a01c-fb6ea958f1e7)

**Comment by filips123** [comment]
> So specifically, on top of that page ([pwasforfirefox.filips.si/user-guide/browser](https://pwasforfirefox.filips.si/user-guide/browser/)), I'd specify it's found in the Settings access through hamburger menu in PWA.

Well, should it really be on top of that page? I think it would make more sense if it was under the Configuration Options section, in a "tip" box, as the page also contains other information not relevant to settings.

> Additionally, is it possible to disable this prompt? it's very tedious to click on it everytime.

That will be fixed in the next release.

**Comment by filips123** [comment]
I added a tip box that makes it more clear [where settings are located](https://github.com/filips123/PWAsForFirefox/commit/116c766f69bf17f5f8e70358f44d8bc178956e27). Please let me know if you have any other suggestions.

I'll also close this issue as the originally requested feature has already been implemented.

**Comment by justin13888** [comment]
Sounds good! Great work :)
