### ISSUE TITLE
Error: "can't access property "href", e is null"

### ISSUE THREAD

**Issue by aqua-wolf** [filips123/PWAsForFirefox#452]
### Description

I am not able to install PWAs for any website and immediately get the error: "can't access property "href", e is null"

### Steps to Reproduce

1. Go to any website
2. Click on "Install this site"
3. See error

### Additional Information

![image](https://github.com/filips123/PWAsForFirefox/assets/44662270/3dc7ea95-de44-474b-9f9d-410757141c34)

### Affected Websites

- All websites

### Environment

* Operating system: macOS 12.5
* System architecture: x64
* Installation method: extension / brew
* PWAsForFirefox extension version: 2.10.0
* PWAsForFirefox native version: 2.10.0
* PWAsForFirefox runtime version: 2.10.0
* Firefox version: 122.0b9

**Comment by filips123** [comment]
I think I know why this happens and will try to fix it soon. You can temporarily downgrade to 2.9.1 to fix this issue. I also disabled 2.10.0 so no more users should get updated to this version.

**Comment by filips123** [comment]
This should be fixed in 2.10.1. The problem was specific to Linux and macOS so I didn't find it during normal testing...
