### ISSUE TITLE
Allow user to edit the name of the PWA when installing

### ISSUE THREAD

**Issue by Jaifroid** [filips123/PWAsForFirefox#455]
### Problem Description

On Windows 11 and on Linux (Ubuntu), I was unable to edit the name of the PWA when installing (none of the fields shown were editable). I wanted to add "Firefox" in order to distinguish the Firefox-installed PWA from the Chrome- or Edge-installed versions (as a developer, I need to test different versions). This is possible on Android when installing the Firefox PWA (native installation is supported on Firefox for Android).

### Proposed Solution

Make the shortcut fields presented to the user in the installation confirmation into editable fields.

### Additional Information

As mentioned, I tested on Win11 and Ubuntu and in both cases, the fields were greyed out. I only really tested the shortcut name field.

**Comment by filips123** [comment]
Changing the name works fine for me:

![slika](https://github.com/filips123/PWAsForFirefox/assets/16626308/cbd73a32-3370-4e91-9107-d5fd5247312d)

**Comment by Jaifroid** [comment]
Oh, how strange. I tried on the two mentioned platforms, and it wouldn't let me change it. I'll try again!

**Comment by filips123** [comment]
Please also make sure that you are on the latest version (2.10.1). Also, if it doesn't work on the install screen for some reason, also try it from the edit screen.

**Comment by Jaifroid** [comment]
My apologies, the fields are indeed editable, only in a slightly weird way. My error was to try to use the arrow keys to edit the existing text, and it didn't occur to me simply to start typing in the field, at which point the existing text disappears to be replaced by whatever you are typing. This isn't the usual behaviour for an editable field, but it is perfectly serviceable if you actually try to type, and not just uses arrow keys or backspace key.

**Comment by filips123** [comment]
The default values are set as placeholders, because otherwise it would be harder to know if the user wanted to (re)set the values to their defaults.
