### ISSUE TITLE
All PWA windows open as a Blank window

### ISSUE THREAD

**Issue by Oxika95** [filips123/PWAsForFirefox#464]
![image](https://github.com/filips123/PWAsForFirefox/assets/48342370/1cce3d4a-7074-4477-a4e7-1eea74c8a0c9)

All PWA windows open as a Blank window. Tried with google calendar and https://herolab.online/login. 

Console errors are empty, logs included.

[firefoxpwa-stdout.log](https://github.com/filips123/PWAsForFirefox/files/14217331/firefoxpwa-stdout.log)
[firefoxpwa-stderr.log](https://github.com/filips123/PWAsForFirefox/files/14217332/firefoxpwa-stderr.log)
[firefoxpwa.log](https://github.com/filips123/PWAsForFirefox/files/14217333/firefoxpwa.log)

**Comment by Oxika95** [comment]
This was on my personal laptop. Just got to work today and installed on my work PC using winget same as the laptop. PWAs work as expected on this PC, but not on the laptop.

**Comment by filips123** [comment]
First, try to get the runtime logs (these are different from the extension console logs). Instructions for this are available [here](https://pwasforfirefox.filips.si/help/troubleshooting/#obtaining-runtime-logs).

Please also try to install PWA into a new profile. You can change profile when installing PWA from the extension.

**Comment by Oxika95** [comment]
Alright I'll give that a try as soon as I get home from work.

**Comment by Jayrom3** [comment]
Same experience here. I've just installed the plugin and all I get is a blank page when I launch an app.
But what worried me is that Firefox is now broken : it does not restore previous sessions anymore (the option is still checked in parameters). I have uninstall the plugin and this problem is still there. Firefox is now partialy broken.

**Comment by Jayrom3** [comment]
Okay. Reinstalling Firefox has fixed the session problem. For now, I will stick to Brave or Edge when I need a PWA. Thank you for your efforts in supporting the Firefox users community. I hope one day Mozilla will realize how important PWA is nowadays.

**Comment by Oxika95** [comment]
Well finally came back to do troubleshooting and it appears to be working. Not sure what happened to make it work now. My device power cycled but I had already tested that. Sorry I was unable to get you the logs to figure out what the issue was but things look good now.

**Comment by filips123** [comment]
Ok, I'll close this issue. If you still have this problem in the future, please comment and try to provide the logs.

**Comment by Duckle29** [comment]
@filips123 I think I may have this issue, and I can't seem to resolve it.

I've even "deleted" the default profile and re-added PWAs

The page works fine in the normal browser, but doesn't work when launched as an app.

This worked 30min ago, but I had to do some electrical work, so turned off power (shut down PC properly first) and now this I have this issue.
Here's an example of Shlink, right after re-installing it. The behaviour was the same before tho
![image](https://github.com/user-attachments/assets/9a601a22-5552-402f-b114-62453f34178b)

**Comment by lil-greasy** [comment]
I have this problem!

It happened to me once before, and I reinstalled the runtime, the extension, and all of my applications. It helped. But that doesn’t seem like a long-term solution.

Today, I’ve been using a variety of applications, all in their own profiles, quite happily until I hit this brick wall. I can’t open the developer console normally (F12) from the blank window, but opening it from the command line as you described earlier works. Here’s what I see:


Browser Console Mode
Parent process only(Fast)
Multiprocess(Slower)
1736292492761	addons.xpi	WARN	Checking C:\Users\patri\AppData\Roaming\FirefoxPWA\runtime\distribution\extensions for addons
TypeError: currentPlacements is undefined
(CustomizableUI.sys.mjs:3936:11)
• get inDefaultState --- resource:///modules/CustomizableUI.sys.mjs:3936
• get inDefaultState --- resource:///modules/CustomizableUI.sys.mjs:5135
• _updateResetButton --- resource:///modules/CustomizeMode.sys.mjs:1532
• observe --- resource:///modules/CustomizeMode.sys.mjs:1652
• set --- resource://pwa/utils/xPref.jsm:37
• configureSettings --- file:///C:/Users/patri/AppData/Roaming/FirefoxPWA/profiles/01JFQYK17X67XAMH8YMRFHYXNC/chrome/pwa/content/browser.jsm:1892
• configureAll --- file:///C:/Users/patri/AppData/Roaming/FirefoxPWA/profiles/01JFQYK17X67XAMH8YMRFHYXNC/chrome/pwa/content/browser.jsm:1805
• PwaBrowser --- file:///C:/Users/patri/AppData/Roaming/FirefoxPWA/profiles/01JFQYK17X67XAMH8YMRFHYXNC/chrome/pwa/content/browser.jsm:18
• <anonymous> --- file:///C:/Users/patri/AppData/Roaming/FirefoxPWA/profiles/01JFQYK17X67XAMH8YMRFHYXNC/chrome/pwa/content/browser.jsm:2128
• loadUserScript --- resource://pwa/chrome.jsm:118
• handleEvent --- resource://pwa/chrome.jsm:97
TypeError: currentPlacements is undefined
(CustomizableUI.sys.mjs:3936:11)
TypeError: window.gBrowser is undefined
(browser.jsm:99:5)
TypeError: this.editor is null
• UrlbarInput --- resource:///modules/UrlbarInput.sys.mjs:308
• <anonymous> --- chrome://browser/content/browser.js:361
• shouldSuppress --- chrome://browser/content/browser.js:445
• PopupNotifications --- resource://gre/modules/PopupNotifications.sys.mjs:236
• <anonymous> --- chrome://browser/content/browser.js:472
• onCreated --- file:///C:/Users/patri/AppData/Roaming/FirefoxPWA/profiles/01JFQYK17X67XAMH8YMRFHYXNC/chrome/pwa/content/browser.jsm:1661
• aEventName --- resource:///modules/CustomizableUI.sys.mjs:3415
• buildWidget --- resource:///modules/CustomizableUI.sys.mjs:2161
• getWidgetNode --- resource:///modules/CustomizableUI.sys.mjs:1456
• buildArea --- resource:///modules/CustomizableUI.sys.mjs:1250
• registerToolbarNode --- resource:///modules/CustomizableUI.sys.mjs:1161
• registerToolbarNode --- resource:///modules/CustomizableUI.sys.mjs:4549
• onDOMContentLoaded --- chrome://browser/content/browser-init.js:168
(browser.js:479:13)
• <anonymous> --- chrome://browser/content/browser.js:479
• onCreated --- file:///C:/Users/patri/AppData/Roaming/FirefoxPWA/profiles/01JFQYK17X67XAMH8YMRFHYXNC/chrome/pwa/content/browser.jsm:1661
• aEventName --- resource:///modules/CustomizableUI.sys.mjs:3415
• buildWidget --- resource:///modules/CustomizableUI.sys.mjs:2161
• getWidgetNode --- resource:///modules/CustomizableUI.sys.mjs:1456
• buildArea --- resource:///modules/CustomizableUI.sys.mjs:1250
• registerToolbarNode --- resource:///modules/CustomizableUI.sys.mjs:1161
• registerToolbarNode --- resource:///modules/CustomizableUI.sys.mjs:4549
• onDOMContentLoaded --- chrome://browser/content/browser-init.js:168
TypeError: functionContext is null
• hookFunction --- resource://pwa/utils/hookFunction.jsm:23
• onCreated --- file:///C:/Users/patri/AppData/Roaming/FirefoxPWA/profiles/01JFQYK17X67XAMH8YMRFHYXNC/chrome/pwa/content/browser.jsm:1661
• aEventName --- resource:///modules/CustomizableUI.sys.mjs:3415
• buildWidget --- resource:///modules/CustomizableUI.sys.mjs:2161
• getWidgetNode --- resource:///modules/CustomizableUI.sys.mjs:1456
• buildArea --- resource:///modules/CustomizableUI.sys.mjs:1250
• registerToolbarNode --- resource:///modules/CustomizableUI.sys.mjs:1161
• registerToolbarNode --- resource:///modules/CustomizableUI.sys.mjs:4549
• onDOMContentLoaded --- chrome://browser/content/browser-init.js:168
(CustomizableUI.sys.mjs:3420:17)
Uncaught TypeError: gURLBar is undefined
• _setURLBarPlaceholder --- chrome://browser/content/browser.js:2062
• initPlaceHolder --- chrome://browser/content/browser.js:1967
• onDOMContentLoaded --- chrome://browser/content/browser-init.js:200
(browser.js:2062:7)
Uncaught TypeError: window.gFFPWABrowser is undefined
• onCreated --- file:///C:/Users/patri/AppData/Roaming/FirefoxPWA/profiles/01JFQYK17X67XAMH8YMRFHYXNC/chrome/pwa/content/browser.jsm:1205
(browser.jsm:1205:37)
Uncaught TypeError: gURLBar is undefined
• update --- chrome://browser/content/browser.js:4781
• init --- chrome://browser/content/browser.js:4699
• onLoad --- chrome://browser/content/browser-init.js:283
(browser.js:4781:5)
Uncaught TypeError: gURLBar is undefined
• _adjustFocusBeforeTabSwitch --- chrome://browser/content/tabbrowser/tabbrowser.js:1432
• updateDisplay --- resource:///modules/AsyncTabSwitcher.sys.mjs:461
• postActions --- resource:///modules/AsyncTabSwitcher.sys.mjs:686
• handleEvent --- resource:///modules/AsyncTabSwitcher.sys.mjs:1164
• queueUnload --- resource:///modules/AsyncTabSwitcher.sys.mjs:1085
• requestTab --- resource:///modules/AsyncTabSwitcher.sys.mjs:1081
• updateCurrentBrowser --- chrome://browser/content/tabbrowser/tabbrowser.js:1200
• replacementFunction --- resource://pwa/utils/hookFunction.jsm:34
• _setupEventListeners --- chrome://browser/content/tabbrowser/tabbrowser.js:6623
• set selectedIndex --- chrome://global/content/elements/tabbox.js:235
• set selectedPanel --- chrome://global/content/elements/tabbox.js:245
• set selectedIndex --- chrome://global/content/elements/tabbox.js:555
• set selectedItem --- chrome://global/content/elements/tabbox.js:579
• set selectedTab --- chrome://global/content/elements/tabbox.js:83
• set selectedTab --- chrome://browser/content/tabbrowser/tabbrowser.js:430
• addTab --- chrome://browser/content/tabbrowser/tabbrowser.js:2889
• viewSourceOfDocument --- chrome://browser/content/browser-commands.js:499
• viewSource --- chrome://global/content/viewSourceUtils.js:66
• viewSource --- resource://devtools/client/webconsole/webconsole.js:223
• onViewSource --- resource://devtools/client/webconsole/service-container.js:43
• selectFrame --- resource://devtools/client/shared/components/SmartTrace.js:299
• onMouseDown --- resource://devtools/client/debugger/src/components/SecondaryPanes/Frames/Frame.js:125
• onMouseDown --- resource://devtools/client/debugger/src/components/SecondaryPanes/Frames/Frame.js:165
• React 19
(tabbrowser.js:1432:7)
TypeError: gURLBar is undefined
(tabbrowser.js:1432:7)
TypeError: gURLBar is undefined
(tabbrowser.js:1432:7)
TypeError: gURLBar is undefined
(×2, tabbrowser.js:1432:7)
TypeError: PopupNotifications is null
• onLocationChange --- chrome://browser/content/browser.js:4094
• callListeners --- chrome://browser/content/tabbrowser/tabbrowser.js:1006
• _callProgressListeners --- chrome://browser/content/tabbrowser/tabbrowser.js:1026
• _callProgressListeners --- chrome://browser/content/tabbrowser/tabbrowser.js:7197
• onLocationChange --- chrome://browser/content/tabbrowser/tabbrowser.js:7672
(tabbrowser.js:1011:23)
TypeError: gURLBar is undefined
(×2 tabbrowser.js:1432:7)
TypeError: gURLBar is undefined
(tabbrowser.js:1432:7)
TypeError: gURLBar is undefined
(50 tabbrowser.js:1432:7)

**Comment by Duckle29** [comment]
@filips123 Thanks, that did solve it!
I appreciate the work you put into maintaining this and supporting people! ❤️
