### ISSUE TITLE
Failed to uninstall firefoxpwa runtime

### ISSUE THREAD

**Issue by Jayrom3** [filips123/PWAsForFirefox#465]
### Description

On Windows 10, when I try to uninstall firefoxpwa runtime with the documented command, it fails.

### Steps to Reproduce

1. Open an elevated (run as admin) Command or Powershell shell.
2. Type "firefoxpwa runtime uninstall"

### Additional Information

This is the error message :

> C:\WINDOWS\system32>firefoxpwa runtime uninstall
12:19:35 [INFO] Uninstalling the runtime
12:19:35 [ERROR] Failed to uninstall runtime
>
> Caused by:
    0: Failed to remove runtime directory
    1: Accès refusé. (os error 5)

### Environment

* Operating system: Windows 10 Home 22H2 build 19045.3930
* System architecture: x64
* Installation method: winget 
* PWAsForFirefox extension version: 2.10.1
* PWAsForFirefox native version: 2.10.1
* PWAsForFirefox runtime version: 2.10.1
* Firefox version: 122.0.1 (64bits)

**Comment by filips123** [comment]
Maybe the runtime is still running? Also, what if you try to manually delete it by deleting `%APPDATA%\FirefoxPWA\runtime`?

**Comment by Jayrom3** [comment]
Thanks for your feedback. I have managed to uninstall FirefoxPWA with Windows uninstall.
