### ISSUE TITLE
CORS whitelist option

### ISSUE THREAD

**Issue by sirati** [filips123/PWAsForFirefox#467]
### Description
I have used this project to load a PWA that usually runs as an extension on chrome and it makes requests to API backends that do not provide a CORS header response. Because of this firefox refuses the connection to the API backend.

### Steps to Reproduce
i have made minimal changes to this https://chromewebstore.google.com/detail/line/ophjlpahpchlmihnnnihgmmeilfjmjjc to make it a PWA.
my changes are published to https://line-pwa.sirati.me (please mind that this is for my person hack and you should definitely not trust your LINE login with code served from a source other that LINE!)

1. you can either use my url above to test the PWA or download from the chromewebstore as zip, add the <link rel="manifest" href="manifest.json" /> to all html files, and replace the manifest.json with https://line-pwa.sirati.me/manifest.json 
2. add it as a PWA
3. open
4. check console for CORS error

### Additional Information

I understand that ignoring CORS is a security risk, however if firefoxfwa would add an explicit commandline option to whitelist backend API to ignore missing/mismatching CORS originating ONLY from the PWA source domain the risk is controlled as it would work only in an explicit PWA after explicit user action

**Comment by filips123** [comment]
Don't some Firefox extensions to disable CORS already exist? It seems there are [quite a lot](https://addons.mozilla.org/firefox/search/?q=CORS) of them, although I don't know how they work. So, I think it's not really needed to add a CORS option here.

**Comment by filips123** [comment]
I decided not to implement this option because other addons for this already exist.
