### ISSUE TITLE
Corners are not rounded, inner site overlaps. 

### ISSUE THREAD

**Issue by McBaumwolle** [filips123/PWAsForFirefox#470]
### Description

Some apps (I could not find a pattern) do have buggy corners (see screenshot) and the inner page overlaps on all four edges. 

### Steps to Reproduce

1. Go to 'https://messages.google.com/' (in my case this is one of them)
2. Click on 'install this site'
4. Check corners

### Additional Information

![image](https://github.com/filips123/PWAsForFirefox/assets/67203883/e7d0ef69-2f64-4a47-973e-a9017053f5eb)

I am using the custom [surface kernel](https://github.com/linux-surface/linux-surface) for my device if that helps. 

### Affected Websites

- https://messages.google.com/
- https://photos.google.com/
(Okay mabye it is Google.)

### Environment

* Operating system: Ubuntu 22.04.4 LTS
* System architecture: 64bit
* Desktop environment: GNOME
* Installation method: DEB
* PWAsForFirefox extension version: 2.10.1
* PWAsForFirefox native version: 2.10.1
* PWAsForFirefox runtime version:  123.0
* Firefox version: 123.0 (64-bit)

Thank you.

**Comment by filips123** [comment]
Can you check if disabling "Allow web apps to override a theme (titlebar) color" and "Allow web apps to override a background (window) color" in the app browser settings helps? Also, what do you mean that the inner page overlaps?

**Comment by McBaumwolle** [comment]
Thanks for the response, the two options actually fixed the issue!

(Oh and with "overlaps" I just meant it looks like the page is rendered after the frame and the corners are visible (does this make sense)).

Thanks!

**Comment by McBaumwolle** [comment]
Let me just add that the lower corners are still unrounded, but I think that is intentional. 

![image](https://github.com/filips123/PWAsForFirefox/assets/67203883/acbe051f-d229-4941-97b8-97074e40b100)
