### ISSUE TITLE
False positive malware detection by Microsoft Defender

### ISSUE THREAD

**Issue by nanashinasubi** [filips123/PWAsForFirefox#480]
I really wanted this application to work. However, every time I download the installation packages and run the system, Microsoft virus & threat protection identifies severe Trojan malware in the files. When the system removes the Trojan malware, the extension has an error and I cannot save any websites as PWAs. Any workarounds? 
![image](https://github.com/filips123/PWAsForFirefox/assets/164282731/7b21dafe-2423-493e-a14f-9e726082e934)
![image](https://github.com/filips123/PWAsForFirefox/assets/164282731/ef4cba67-96ab-464c-b1a5-1f93aed652e0)

_Originally posted by @nanashinasubi in https://github.com/filips123/PWAsForFirefox/discussions/479_

**Comment by jonm58** [comment]
you need directory in the Microsoft virus & threat protection identifies whitelist,

**Comment by nanashinasubi** [comment]
> you need directory put in the Microsoft virus & threat protection identifies whitelist.

I want to avoid whitelisting any malware that might be present in the files, as this could damage my computer. Can you confirm if it's safe to proceed with the whitelist, considering the possibility of malware? I haven't found any discussions on this forum about malware in the application, so I'm unsure about the safety of bypassing the whitelist and allowing it to run on my computer.
