### ISSUE TITLE
Crunchyroll doesn't work with manifest enabled

### ISSUE THREAD

**Issue by AthreyaV** [filips123/PWAsForFirefox#482]
### Description

Crunchyroll website doesn't work unless the "use manifest" checkbox is unticked

![image](https://github.com/filips123/PWAsForFirefox/assets/40580892/105aad27-1a18-468b-a785-a7eb6efaee1c)

### Steps to Reproduce

1. Go to crunchyroll.com
2. Click on install current site
3. Create using default settings
4. Error

### Additional Information

I already discovered that this is a non issue as long as the use manifest is unticked, but weirdly enough not all of crunchyroll's websites are affected. Some pages like the games tab, buy/free trial premium page, and sso login work just fine. Mostly just opening the issue for tracking on the website.

### Environment

* Operating system: Windows
* PWAsForFirefox extension version: (latest as of 3/21.24)
* PWAsForFirefox native version: (latest as of 3/21.24)
* PWAsForFirefox runtime version: (latest as of 3/21.24)
* Firefox version: (latest as of 3/21.24)

**Comment by AthreyaV** [comment]
Actually quick follow up here, this problem doesn't seem to happen on edge/chrome

**Comment by filips123** [comment]
The request to download the manifest is blocked by Cloudflare for some reason. This has already been repoted [last year](https://github.com/filips123/PWAsForFirefox/issues/318#issuecomment-1771515471).

I probably can't do anything about this... However, I've created a discussion on the repo of HTTP client if maybe someone knows how to fix it: seanmonstar/reqwest#2227
