### ISSUE TITLE
Allowed Domains: Support Wildcard/Regex

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#484]
I added Wikipedia as a PWA.
I checked "Open out-of-scope URLs in a default browser (can break some web apps)"
And add "https:\/\/([a-z]{2,3})\.wikipedia\.com\/" or "*.wikipedia.com"

![image](https://github.com/filips123/PWAsForFirefox/assets/23485114/6868e721-9557-4b58-a06c-a0b9901f53df)

But doesn't support it.
If I select language, the site opens on the default browser,

![image](https://github.com/filips123/PWAsForFirefox/assets/23485114/6ab394b1-acdb-4dcc-a053-435c1acecb94)

**Comment by filips123** [comment]
This option only support simple wildcard patterns. And `*.domain` only matches subdomains.

So for Wikipedia, `wikipedia.org,*.wikipedia.org` should work. You will probably also need to restart PWA so the option is applied.
