### ISSUE TITLE
Proxy support.

### ISSUE THREAD

**Issue by fxzxmicah** [filips123/PWAsForFirefox#486]
### Problem Description

It seems that the browser proxy or system proxy was not used when installing the PWA application.

### Proposed Solution

Use browser proxy or system proxy when installing PWA applications.

### Additional Information

None.
If you need any other information, please feel free to ask.

**Comment by filips123** [comment]
PWAsForFirefox uses a separate program to make requests, so browser proxy can't be used.

However, it should already use a system proxy if it exists. It gets proxies from the environment variable `HTTP_PROXY` for HTTP connections and `HTTPS_PROXY` for HTTPS. And on Windows, it also tries to get a proxy from the registry (`HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings` -> `ProxyEnable` and `ProxyServer`).

**Comment by fxzxmicah** [comment]
But it didn't recognize the proxy on my computer. I don't know why.
But it's not a problem for me now, because I switched to tproxy.

**Comment by filips123** [comment]
Was the proxy set in these environment variables?

**Comment by fxzxmicah** [comment]
> Was the proxy set in these environment variables?
Set, curl can recognize the proxy and use it.

**Comment by filips123** [comment]
How are they set? If you only set them in `.bashrc` (or similar), they might not be applied to PWAsForFirefox, because it's launched by Firefox when installing web apps.

**Comment by filips123** [comment]
Can you try to run PWAsForFirefox from terminal and check if it uses proxy in that case? So, try running something like:

```
firefoxpwa site install https://github.com/manifest.json
```

Also, check if these environment variables are set when running from terminal.

**Comment by fxzxmicah** [comment]
I don't use the HTTP proxy anymore, so I can't test it.
However, there are environment variables for the HTTP proxy in the terminal.
