### ISSUE TITLE
Unable to launch apps through PowerToys Run

### ISSUE THREAD

**Issue by AthreyaV** [filips123/PWAsForFirefox#489]
### Description

when attempting to launch the shortcuts for a webapp through PowerToys Run, nothing happens. 

### Steps to Reproduce

1. Enable PowerToys Run through the PowerToys app
2. run the PowerToys Run search bar and type the name of the FirefoxPWA app you want to launch
3. hit enter to run the shortcut
4. nothing happens

### Additional Information

running as administrator through PowerToys Run seems to fix the issue, though it does ask for a UAC prompt every time which is a pretty shoddy workaround. Upon further investigation, launching cmd itself through PowerToys Run and attempting to run the command to launch the site through there results in the error "access is denied (os error 5)

### Environment

* Operating system: Windows 11 (latest)
* System architecture: x64
* PWAsForFirefox extension version: latest
* PWAsForFirefox native version: latest
* PWAsForFirefox runtime version: latest
* Firefox version: latest

**Comment by filips123** [comment]
> launching cmd itself through PowerToys Run and attempting to run the command to launch the site through there results in the error "access is denied (os error 5)

Considering that this happens, it might be the same issue as #460.

Basically, PWAsForFirefox needs a `JOB_OBJECT_LIMIT_BREAKAWAY_OK` permission when launching the runtime, so that launching web apps from the extension works. But some tools (possibly including PowerToys Run), don't set this permission for some reason, so launching fails.

However, your problem is a bit different, as running as administrator fixed your issue, but didn't in case of the original one. So I'm not completely sure why this happens.

I will try to fix launching when that permission is not set in the future.

**Comment by AthreyaV** [comment]
Follow up info, I learned that you can actually set power toys as a whole to run as admin through settings and this effectively fixes the issue- PWA shortcuts launch fine and no UAC prompt every time. I assume the actual mechanism as to why this works is the same as my initial workaround, just applied at a different point in the chain. 

I would say this issue is technically closed but I'm curious to see where your digging leads with that permissions issue

**Comment by filips123** [comment]
I've tested it on Windows 10 and 11 (although with a quite old version of 11), with the latest [PowerToys 0.80.1](https://github.com/microsoft/PowerToys/releases/tag/v0.80.1), and it works fine without any additional configuration or running as admin.

I've also checked if PowerToys uses job objects anywhere but I couldn't find it (but maybe I missed something). So, maybe it's not related to the issue with the `JOB_OBJECT_LIMIT_BREAKAWAY_OK` permission.

Do you use the latest PowerToys version? Also, can you check if it works with the default PowerToys settings?

**Comment by filips123** [comment]
I fixed the issue with `JOB_OBJECT_LIMIT_BREAKAWAY_OK` in 2.12.0. Please update (the native program) to 2.12.0 and check if it fixes your issue.

**Comment by AthreyaV** [comment]
solved, works perfectly fine without requiring admin now
