### ISSUE TITLE
Redirects always within the PWA

### ISSUE THREAD

**Issue by kugel-** [filips123/PWAsForFirefox#490]
### Description

Open redirects within the PWA but clicked links on the default browser.

### Steps to Reproduce

1. Select "Open out-of-scope URLs in a default browser (can break some web apps)"
2. Open web-app
3. Redirects to authentication opens in default firefox window (global instance)
4. redirect back to the mail pwa remains in the default firefox window

### Additional Information

I installed "HCL Verse" webmail as PWA. This works fine generally. However, I do want links I click in the mails to open in the default firefox window. Therefore I select "Open out-of-scope URLs in a default browser (can break some web apps)". However, this also triggers the login procedure to open in the default firefox.

The procedure redirects to a login page which then sets a cookie and redirects back to the mail application (original site, to be exact). As described above, as long as the "Open out-of-scope URLs in a default browser (can break some web apps)" option is enabled, this effectively moves the entire PWA back to the default browser while the PWA window just shows a running circle.

The authentication site is on a different subdomain (id.$corp.de instead of mail.$corp.de/verse). The links that I *do* want to open are on yet another subdomains (e.g. bug.$corp.de) but I open these only via hyperlinks in the mails, not via automatic redirects.

### Affected Websites

HCL Verse. Don't know if there are public instances but this one is in our internal network. See https://www.hcl-software.com/verse for more info about the webapp.

I think it came with a manifast. How can I check?

### Environment

Linux, Ubuntu 22.04, PWA helper installed via https://packagecloud.io/filips/FirefoxPWA and the "fuse-overlay" method.

* Desktop environment: KDE
* Installation method: DEB
* PWAsForFirefox extension version: 2.11.1
* PWAsForFirefox native version: 2.11.1
* PWAsForFirefox runtime version: ??
* Firefox version: 123.0.1

**Comment by filips123** [comment]
Well, this is one of the reasons that "can break some web apps" is mentioned... You should be able to fix this by adding the authentication site's domain (only domain, without protocol or path) to the "Domains always allowed to be opened in the app browser" input in the app browser settings.

Unfortunately, I think it's not possible to differentiate between automatic redirects and manually clicked links, because many websites use JS even for normal navigation. So, you will have to manually add the domain as mentioned above.

**Comment by H-Tevin** [comment]
Where did you find the option to "Open out-of-scope URLs in a default browser (can break some web apps)"?

That is exactly what I want to enable, but I can't seem to find the button.
Thanks!

**Comment by filips123** [comment]
In the PWA, open the app menu and go to settings. You should then see the option in the "Progressive Web Apps" section.

![slika](https://github.com/filips123/PWAsForFirefox/assets/16626308/4c8b3e0e-823a-471d-a2b8-55a7ba69d69f)

![slika](https://github.com/filips123/PWAsForFirefox/assets/16626308/78ac5512-d0f0-4e40-a713-e39396c03438)

**Comment by H-Tevin** [comment]
Awesome, I didn't realize that settings page existed. Thanks!

**Comment by kugel-** [comment]
> Well, this is one of the reasons that "can break some web apps" is mentioned... You should be able to fix this by adding the authentication site's domain (only domain, without protocol or path) to the "Domains always allowed to be opened in the app browser" input in the app browser settings.

Thanks, I somehow totally missed that entry box. I could make it work by listing the authentication site and one more internal domain. The latter wasn't obvious to me. Only the authentication site did not work and it wasn't obvious why and which domain is missing in the blacklist.

I made a lucky guess. Do you know how else one can diagnose the needed domains in case the authentication site still opens in the main firefox window?


> Unfortunately, I think it's not possible to differentiate between automatic redirects and manually clicked links, because many websites use JS even for normal navigation. So, you will have to manually add the domain as mentioned above.

That's sad. Luckily the blacklist works for me now. Closing.

**Comment by filips123** [comment]
> Do you know how else one can diagnose the needed domains in case the authentication site still opens in the main firefox window?

Probably by disabling "Open out-of-scope URLs in a default browser" and then observing which URLs you are redirected to. Maybe you could also see these URLs in the history.

In the future, I will probably also implement a way to show historically accessed domains as suggestions for the input (#284).
