### ISSUE TITLE
Can't open a PWA from another PWA when check "Open out-of-scope URLs in a default browser"

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#496]
Hi, dear @filips123
I installed GitHub.com, X.com, and Instagram.com as PWAs.
On GitHub PWA I checked "Open out-of-scope URLs in a default browser".
**When I click on X and Instagram links on GitHub PWA, I want it to open as a PWA instead of opening to the default browser.**
I installed the "Progressive Web Apps for Firefox" extension on GitHub PWA for this and check "Enable automatic web app launching".
In this case, X and Instagram URLs are also opened in the default browser in addition to out-of-scope URLs.
If I uncheck "Open out-of-scope URLs in a default browser" on GitHub PWA, I can open X and Instagram URLs as PWA.
But I don't want the out-of-scope URLs to open in the PWA and I want it to open in the default browser.
Please help me.
Sorry for my bad English.

**Comment by filips123** [comment]
You can add Twitter/X and Instagram to a list of domains always allowed to be opened in the app browser. So, something like:

```
twitter.com,x.com,instagram.com,github.com
```

This way, links to Twitter and Instagram won't be forced to the default browser, so the extension will be able to open them in the PWA, while other links should open in the default browser as normal.

**Comment by filips123** [comment]
Also, you will probably have to reinstall Twitter/X as they changed the main URL to https://x.com, and this breaks existing PWA installations.
