### ISSUE TITLE
All PWAs are collapsed (categorized together) with the main Firefox icon on KDE Wayland

### ISSUE THREAD

**Issue by PeterCxy** [filips123/PWAsForFirefox#50]
### Description

On KDE Wayland, all PWAs are collapsed on the task bar with the main Firefox icon, even when none of them use the same profile. This does not happen on KDE Xorg.

### Steps to Reproduce

1. Install PWAs on KDE Wayland
2. Observe that none of them show up as their own icon on the task bar

### Additional Information

I am not sure if this is a bug of KDE, Firefox, or just Wayland in general. I'm posting it here for more information, e.g. does it happen on other Wayland-based Linux desktops?

**Comment by markcellus** [comment]
I'm on Ubuntu (xorg) and I'm seeing this happen as well. I can't "tab" to different apps because of it. :sob:

**Comment by PeterCxy** [comment]
@markcellus On KDE Xorg it works fine here. Make sure to use different profiles for each app, as otherwise Firefox itself tries to collapse all of them into one.

**Comment by filips123** [comment]
I don't know why this happens. Maybe Firefox on Xorg sets separate window IDs for each profile, but keeps them the same on Wayland? However, it works for me on Ubuntu with Wayland, so maybe it is KDE-specific problem?

**Comment by markcellus** [comment]
Thanks @PeterCxy. I was just using the "Default" profile for all apps which seemed not to collapse everything at first. But using a totally different profile fixed issue. 👍

**Comment by filipkemuel** [comment]
> I don't know why this happens. Maybe Firefox on Xorg sets separate window IDs for each profile, but keeps them the same on Wayland? However, it works for me on Ubuntu with Wayland, so maybe it is KDE-specific problem?

For me all windows are lumped together with the main Firefox instance regardless of using different profiles for each app.
I'm using Gnome on Wayland on Arch.

However a solution I found is to pass a `--name=[SomeName]` argument to the Firefox runtime. 
And then  the site launches as an individual app. 

The only problem is that then there is no icon. But if I rename the desktop-file in `~/.local/share/applications` to `[SomeName].desktop` the icon appears.

**Comment by dithom** [comment]
I'm on macos. The issue appears a bit different here. When launching the first pwa, a new app icon with a new separate window is launched. However, when I launch another pwa, the window of the new pwa is launched as a window of the first running pwa.

**Comment by filips123** [comment]
@filipkemuel Is icon displayed if `[SomeName]` is the same as original `.desktop` filename (like `FFPWA-01F9YK54NXPC3Z9FA1NTJH8JH3`? If yes, FirefoxPWA could just additionally pass `--name` along with [`--class`](https://github.com/filips123/FirefoxPWA/blob/ae9a568da33e2c0c50e0c8ea28bfda4af0a0e679/native/src/components/site.rs#L123) and maybe this issue (at least on Linux) will be solved.

@dithom Fixing this on macOS will probably be harder as macOS has some restrictions for apps. Can you try if windows are grouped correctly if you install each site into a different profile?

**Comment by filipkemuel** [comment]
At first no.. I had to rename the file to the same name as title..
But I just renamed it back to the class-name and now it is working wonderfully..

So I guess that passing a title is enough to solve it.. at least on Linux/Gnome..

**Comment by filipkemuel** [comment]
Sorry.. I was a bit too fast to answer.. I forgot I had switched to xorg.. Now back on Wayland it only works if the desktop-file has the same name as the title..

It might actually be a bug in Gnome..

**Comment by dithom** [comment]
@filips123 using separate profiles for every app solved this issue, thanks!

**Comment by filips123** [comment]
I made #80 for issues where PWAs are merged when all of them are in the same profile, and will keep this issue for when PWAs are merged despite using multiple profiles. Unfortunately, I still don't know how to fix this, but it will at least be more organized.

**Comment by filips123** [comment]
Passing `--name` when launching Firefox runtime actually fixed this issue but I didn't know this because my Firefox wasn't running in Wayland. Now, PWAs in different profiles should be correctly separated. Note that PWAs in the same profile are still grouped together, but this is tracked in #80.
