### ISSUE TITLE
Remove absolute path to firefoxpwa from app .desktop files

### ISSUE THREAD

**Issue by Bennyhill500** [filips123/PWAsForFirefox#501]
### Description

When using FirefoxPWA in a Distrobox container the .desktop files will fail to open because `/usr/bin/firefoxpwa` is inside the container. 
Distrobox can export binaries to `~/.local/bin` for use on the host, but because the desktop files point to the absolute path of `/usr/bin/firefoxpwa` it doesnt work.
I have to manually change all the .desktop files to replace `/usr/bin/firefoxpwa` to just `firefoxpwa` to make them work. The .desktop files should always point to just `firefoxpwa` so they will work no matter where it is installed.

### Environment

For immutable distros where native install of firefox and firefoxpwa isnt possible

**Comment by filips123** [comment]
You can set the `FFPWA_EXECUTABLES` to an empty value and the generated desktop entries will specify `firefoxpwa` without any absolute path. This is also used [on NixOS](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/fi/firefoxpwa/package.nix#L61) for example.
