### ISSUE TITLE
Hide PWA titlebar

### ISSUE THREAD

**Issue by SamuXzX** [filips123/PWAsForFirefox#511]
### Problem Description

It seems it hasn't been requested yet. I'd like to be able to hide the titlebar of PWAs, as I don't actually need it.
I tried following the instructions to add custom CSS (https://pwasforfirefox.filips.si/help/faq/#how-to-make-the-web-app-titlebar-look-more-native), but apart from the fact that I'm not able to access about:config to enable `toolkit.legacyUserProfileCustomizations.stylesheets`, reading the thread I linked in the "Proposed Solution" section it seems that I can only personalize the content and actually hiding the entire titlebar seems another task.

### Proposed Solution

I did a quick googling and someone proposes using the kiosk function: https://stackoverflow.com/questions/77117093/how-to-hide-top-default-toolbar-bar-from-the-installed-pwa
I tried adding `--kiosk` as an argument in the launcher of the PWA but it just failed starting.

**Comment by filips123** [comment]
You can already [hide the toolbar](https://pwasforfirefox.filips.si/user-guide/browser/#allowing-hiding-the-icon-bar) by enabling `firefoxpwa.enableHidingIconBar` in `about:config` and then unckecking icon bar in the Firefox customize page. You might also need to restart PWA. You can access `about:config` if you press `Ctrl+L` and enter `about:config`.
