### ISSUE TITLE
PWA doesn't install

### ISSUE THREAD

**Issue by hollerknight** [filips123/PWAsForFirefox#519]
### Steps to Reproduce

1. Go to '....'

### Affected Websites

* ...
* ...

### Environment

* Operating system:Windows 7
* System architecture:
* Desktop environment: 
* Installation method: 
* PWAsForFirefox extension version:
* PWAsForFirefox native version:
* PWAsForFirefox runtime version:
* Firefox version:115esr
* Errors:
* Error in parsing value for ‘white-space’.  Declaration dropped. 4 manage.html
Uncaught (in promise) Error: An unexpected error occurred undefined
    $ moz-extension://a74677a2-c513-4f4e-bd82-c7a2ebdd9dc1/sites/manage.216686a6.js:1
    AsyncFunctionThrow self-hosted:856
    (Async: async)
    <anonymous> moz-extension://a74677a2-c513-4f4e-bd82-c7a2ebdd9dc1/sites/manage.216686a6.js:1
Uncaught (in promise) Error: An unexpected error occurred undefined
    <anonymous> moz-extension://a74677a2-c513-4f4e-bd82-c7a2ebdd9dc1/sites/manage.216686a6.js:1
    AsyncFunctionThrow self-hosted:856
    (Async: async)
    <anonymous> moz-extension://a74677a2-c513-4f4e-bd82-c7a2ebdd9dc1/sites/manage.216686a6.js:1
Uncaught (in promise) Error: An unexpected error occurred undefined
    D moz-extension://a74677a2-c513-4f4e-bd82-c7a2ebdd9dc1/sites/manage.216686a6.js:1
    AsyncFunctionThrow self-hosted:856
    (Async: async)
    <anonymous> moz-extension://a74677a2-c513-4f4e-bd82-c7a2ebdd9dc1/sites/manage.216686a6.js:1
Uncaught (in promise) Error: An unexpected error occurred undefined
    H moz-extension://a74677a2-c513-4f4e-bd82-c7a2ebdd9dc1/sites/manage.216686a6.js:1
    AsyncFunctionThrow self-hosted:856
    (Async: async)
    H moz-extension://a74677a2-c513-4f4e-bd82-c7a2ebdd9dc1/sites/manage.216686a6.js:1
    InterpretGeneratorResume self-hosted:1455
    AsyncFunctionNext self-hosted:852
    (Async: async)
    <anonymous> moz-extension://a74677a2-c513-4f4e-bd82-c7a2ebdd9dc1/sites/manage.216686a6.js:1
Error in parsing value for ‘white-space’.  Declaration dropped. 4 manage.html
Uncaught (in promise) Error: An unexpected error occurred undefined
Uncaught (in promise) Error: An unexpected error occurred undefined
Uncaught (in promise) Error: An unexpected error occurred undefined
Uncaught (in promise) Error: An unexpected error occurred undefined
Error in parsing value for ‘white-space’.  Declaration dropped. 4 install.html
XHRGET
https://www.ecosia.org/static/manifest.json
[HTTP/2 200 OK 480ms]

Uncaught (in promise) Error: An unexpected error occurred undefined

**Comment by filips123** [comment]
When did this error happen? If it happened when installing a PWA, please check if it works with other websites. Also, please provide [the native logs](https://pwasforfirefox.filips.si/help/troubleshooting/#obtaining-native-logs).

**Comment by hollerknight** [comment]
i don't have runtime installed i think how can i do that

**Comment by filips123** [comment]
Well, opening PWAsForFirefox popup should show you the setup page if the native program and runtime are not already installed. If it didn't open for some reason, you can manually open `moz-extension://c7c2a08c-f45b-440d-80c7-c96aebfc80f1/setup/install.html`. Then, follow the instructions to install the native program and runtime.

**Comment by hollerknight** [comment]
i can't seem to open that for some reason

**Comment by filips123** [comment]
Oh, the extension UUID might be unique for each installation, so that URL won't work. Instead, try to go to `about:debugging#/runtime/this-firefox` (copy and paste it, clicking won't work), find Progressive Web Apps for Firefox in the list, and click on the manifest URL:

![slika](https://github.com/filips123/PWAsForFirefox/assets/16626308/724315c6-5321-4267-8e08-160eb7abe785)

Then, in that URL, replace `manifest.json` with `setup/install.html`.

**Comment by filips123** [comment]
Also, I've noticed that you are using Windows 7. Rust no longer supports Windows 7 in the default target, so it's possible that the native program won't work. If this is the case, you will have to download Rust (version 1.77.1, for example, [this one](https://static.rust-lang.org/dist/rust-1.77.1-x86_64-pc-windows-msvc.msi), as newer versions don't support Windows 7), clone the repository and build it yourself. You can see the instructions [here](https://github.com/filips123/PWAsForFirefox/tree/main/native#from-source). However, Windows 7 is not tested and supported officially, so things may not work properly.

**Comment by NiffirgkcaJ** [comment]
I can't install any PWA in Arch Linux.

**Comment by filips123** [comment]
What exactly happens? Please provide the extension and native logs.

**Comment by NiffirgkcaJ** [comment]
> What exactly happens? Please provide the extension and native logs.

The extension doesn't show the "Install" button when I try to install a website, it seems like the extension prompt is being cut-off. I have tried it on multiple Arch distros both the KDE and GNOME DEs so I think the DE has nothing to do with the DEs, but it's the same. It works on my Ubuntu installation though.

**Comment by filips123** [comment]
Do you have fractional scaling enabled? There are some issues with cut-off extension popup when it's enabled for some reason. see #230 and #503.

Also, you can try to zoom in/out in the popup by pressing Ctrl and scrolling with the scrollwheel. Maybe the button will appear...

**Comment by NiffirgkcaJ** [comment]
> Do you have fractional scaling enabled? There are some issues with cut-off extension popup when it's enabled for some reason. see #230 and #503.
> 
> Also, you can try to zoom in/out in the popup by pressing Ctrl and scrolling with the scrollwheel. Maybe the button will appear...

You're right, it's because of the fractional scaling.

**Comment by filips123** [comment]
I think the original issue happened because Windows 7 is no longer supported, so I will close it. If it also happens on supported systems, please let me know.
