### ISSUE TITLE
Multiple tabs in the custom Firefox instance

### ISSUE THREAD

**Issue by SamuXzX** [filips123/PWAsForFirefox#523]
### Description

The extension does a great job providing a new window for websites, but the Firefox instance still behaves as a browser: sometimes I accidentally open new tabs by muscle memory, because I forget to focus the real Firefox browser, and this opens new tabs in the PWA. These tabs stay there and when, again by muscle memory focusing the wrong window, I switch tabs with a shortcut, I see which other tabs are open.
It seems that the only shortcut which doesn't work is the one to close tabs, so I cannot solve the problem this way.

### Steps to Reproduce

1. Open an installed PWA
2. Press Ctrl+T to open a new tab
3. Press Ctrl+Tab or Ctrl+Tab+Shift to navigate through these hidden tabs

### Environment

* Operating system: Fedora 40
* System architecture: 
* Desktop environment: KDE Plasma 6.1
* Installation method: RPM
* PWAsForFirefox extension version: 2.12.1
* PWAsForFirefox native version: 2.12.1
* PWAsForFirefox runtime version: 128.0
* Firefox version: 128.0

**Comment by filips123** [comment]
I think opening new tabs with Ctrl+T has already been disabled, but maybe something broke in the recent Firefox versions. I'll probably check this next week.

**Comment by eagle00789** [comment]
In the current release, i'm unable to reproduce this myself.

**Comment by SamuXzX** [comment]
Maybe there's a way I can reset everything and try again, like deleting the profiles?

**Comment by filips123** [comment]
The easiest way is to install the PWA again, choose a different name, and select "automatically create a new profile". If you want to delete the old profile, you can do this from the extension.

Also, unfortunately, I didn't have time yet to properly check why this issue happens.

**Comment by eagle00789** [comment]
@SamuXzX are you by any change using any extensions in your PWA that aren't mentioned in your bugreport?

**Comment by SamuXzX** [comment]
I didn't install extensions in the Firefox instance for PWAs

**Comment by SamuXzX** [comment]
Deleting the profile and creating it again worked: I can no longer open a new tab with Ctrl+T...
