### ISSUE TITLE
I need to relaunch PWAs everytime I reboot my computer.

### ISSUE THREAD

**Issue by quebexer** [filips123/PWAsForFirefox#524]
### Description

I could click on any PWA and it will open the window for a second but then it would disappear. So I have to click on the icon again to relaunch it. If I close it and then reopen it, the problem is no longer there, it only happens the first time I launch the PWA.

### Environment
OS: Fedora Linux 40 (Workstation Edition) x86_64
Host: HP EliteBook 845 14 inch G9 Notebook PC (SBKPF)
Kernel: Linux 6.9.9-200.fc40.x86_64
DE: GNOME 46.3.1
WM: Mutter (Wayland)
CPU: AMD Ryzen 7 PRO 6850U (16) @ 4.77 GHz
Browser: Firefox 128
Extrension: FirefoxPWA 2.12.1

https://github.com/user-attachments/assets/aaffee03-e1f6-46c8-a730-dbdf125efc09

**Comment by filips123** [comment]
I think this is the same issue as #488. You can try to set [this preference](https://github.com/filips123/PWAsForFirefox/issues/488#issuecomment-2144018725) to fix it.

**Comment by quebexer** [comment]
Thank you @filips123. I set: browser.sessionstore.max_resumed_crashes to zero and that worked.

**Comment by quebexer** [comment]
Thank you @filips123. I set: browser.sessionstore.max_resumed_crashes to zero and that worked.
