### ISSUE TITLE
Can't install some sites as PWA, no error message

### ISSUE THREAD

**Issue by uwkopf840** [filips123/PWAsForFirefox#528]
### Description

I can't install some websites as a PWA, at this moment specifically proton.me websites (Proton Mail, Proton Drive etc)
After clicking "Install web app", a profile is created ("Automatically create a new profile" is selected) but no new apps are added to the apps list. But no error message pops up.

### Steps to Reproduce

1. Go to [https://proton.me/](https://proton.me/) as an example for all Proton websites
2. Open PWAsForFirefox extension and click install current site
3. Have "Automatically create a new profile" selected
4. Either check or don't check "Use the manifest for determining app properties" it doesn't appear to make a difference
5. Check "Launch this web app on browser launch"
6. Click "Install web app", a new profile is added called "Proton" but no web app is installed or launched

### Additional Information

I've tested some other websites and so far successfully able to install them as PWAs (Wikipedia, Bluesky, Cryptee etc)
Sorry if I'm missing or not understanding something! I'm not that technologically savvy

### Environment

I'm using an alternative browser (Librewolf)

* Operating system: macOS
* Installation method: macOS homebrew following directions in FAQ for Librewolf as main and app browser.
* PWAsForFirefox extension version: 2.12.1
* Firefox version: Librewolf 128.0.3-1

**Comment by filips123** [comment]
Please obtain and provide the extension and native logs as mentioned [here](https://pwasforfirefox.filips.si/help/troubleshooting/).

**Comment by filips123** [comment]
Did you close the extension while the PWA was installing? Or did you wait until the button changed to "Web app installed"?

From the logs it appears like the installation stopped just after downloading a few icons, so the actual PWA was not properly installed. This may happen if you closed the extension while the PWA was installing, as then the program is stopped.
