### ISSUE TITLE
Can't access webcam in Whatsapp Web

### ISSUE THREAD

**Issue by SamuXzX** [filips123/PWAsForFirefox#529]
### Description

I'm trying to use the webcam in a webapp, specifically inside web.whatsapp.com. I receive a negative answer: it seems that the webcam is not found, but I often use it in the main Firefox installation.

### Steps to Reproduce

1. Open web.whatsapp.com
2. In any chat, try to open the webcam

### Additional Information
![immagine](https://github.com/user-attachments/assets/05d65152-f7b6-4d4b-b42b-9a80d6f835c1)

### Affected Websites

* web.whatsapp.com

### Environment

* Operating system: Fedora 40
* System architecture: x86-64?
* Desktop environment: KDE Plasma 6.1
* Installation method: RPM
* PWAsForFirefox extension version: 2.12.1
* PWAsForFirefox native version: 2.12.1
* PWAsForFirefox runtime version: 128.0.3
* Firefox version: 128.0.3

**Comment by filips123** [comment]
Can you download Firefox [directly from Mozilla](https://www.mozilla.org/firefox/all/#product-desktop-release) and check if webcam works there? Also, did you see any permissions popups?

**Comment by filips123** [comment]
Can you check if there are any errors when loading PWA or trying to use the camera [in runtime logs](https://pwasforfirefox.filips.si/help/troubleshooting/#obtaining-runtime-logs)? Maybe something broke the permissions handling (although it works fine for me for notifications permission, haven't tested camera yet)...

You can check in the settings of the PWA browser if you have maybe blocked camera permission. You can also try to install WhatsApp in a new profile, as permission popups aren't blocked by default, so you should see one.

**Comment by SamuXzX** [comment]
![immagine](https://github.com/user-attachments/assets/41441388-8541-4a9f-9a91-5723b6db7ae5)
It seems the permissions in the PWA browser are okay. I'll check the logs.

**Comment by SamuXzX** [comment]
I found the problem: I had hidden the icon bar changing the "firefoxpwa.enableHidingIconBar" option in about:config; now, when trying to use send a voice message or take a picture, the popups which appear asking to grand access to microphone and webcam appear only briefly, and even when I succeed in putting my mouse there, they are not clickable.

I solved showing the icon bar, granting access and then hiding again the icon bar.

**Comment by filips123** [comment]
You will probably have to show the icon bar every time before the permissions popup is supposed to appear. This is known issue (and is documented [here](https://pwasforfirefox.filips.si/user-guide/browser/#allowing-hiding-the-icon-bar)), but fixing it would require quite a lot of work. I plan to do it at some point while rewriting the UserChrome modifications, but that probably won't be ready anytime soon.

**Comment by SamuXzX** [comment]
Thank you very much!
