### ISSUE TITLE
Remove validation for start_url

### ISSUE THREAD

**Issue by ccoager** [filips123/PWAsForFirefox#530]
### Problem Description
I understand there are issues and limitations with Firefox containers/Multi-Account Containers impacting PWA.  I have found a work around using the [Open external links in a container](https://addons.mozilla.org/en-US/firefox/addon/open-url-in-container/) add-on.  This will launch the PWA directly into the container of your choice.  The only issue is the PWA start_url validation prevents you from using the syntax needed for this add-on and gives the error, "Start URL needs to be a valid URL".

I have tested this work around by editing the PWA config.json directly and can confirm that it does work.

### Proposed Solution
Could you remove the validation for start_url?

**Comment by filips123** [comment]
I can try to turn it into warning or someting similar. But I'm not sure if it will work properly, as I think there is also some validation in the manifest that requires start URL to be in the scope.

**Comment by filips123** [comment]
I turned start URL validation into a warning in the next version.
