### ISSUE TITLE
No Icon in Task Bar

### ISSUE THREAD

**Issue by Rexadev** [filips123/PWAsForFirefox#532]
### Additional Information

![image](https://github.com/user-attachments/assets/7e55956a-fa2a-44b0-9bdb-730fdb016215)

### Environment

* Operating system: Windows 11
* System architecture: x64
* Desktop environment: 
* Installation method:  MSI
* PWAsForFirefox extension version: 2.12.1
* PWAsForFirefox native version: What
* PWAsForFirefox runtime version: 129.0
* Firefox version: 129.0

**Comment by filips123** [comment]
Does it happen with all PWAs or just specific ones?

**Comment by Rexadev** [comment]
@filips123 All

**Comment by filips123** [comment]
Please enable [debug logging](https://pwasforfirefox.filips.si/help/troubleshooting/#obtaining-native-logs), run "Update web apps" from the extension settings, and provide the logs.

**Comment by Rexadev** [comment]
1723719529905	addons.xpi	WARN	Checking C:\Users\Noah\AppData\Roaming\FirefoxPWA\runtime\distribution\extensions for addons
TopSitesFeed: Failed to fetch data from Contile server: NetworkError when attempting to fetch resource. [TopSitesFeed.sys.mjs:542](resource://activity-stream/lib/TopSitesFeed.sys.mjs)
attribute_error: normandy.country [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719532690	app.normandy.recipe-runner	ERROR	Error checking filter for "Initial rollout of TCP". Filter: [(normandy.country in ["RU","UA"]) && (((normandy.channel in ["release"]&&["tcp-east-eu-rollout",normandy.userId]|bucketSample(0,10000,10000)&&(env.version|versionCompare("91.!")>=0)&&(env.version|versionCompare("120.*")<0))||(normandy.channel in ["beta"]&&["tcp-east-eu-rollout",normandy.userId]|bucketSample(0,10000,10000)&&(env.version|versionCompare("99.!")>=0)&&(env.version|versionCompare("120.*")<0))))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719532706	app.normandy.recipe-runner	ERROR	Error checking filter for "Heartbeat: Daily Viewpoint Survey (de)". Filter: [(normandy.channel in ["release"]) && (normandy.locale in ["de"]) && (['rolling-viewpoint', normandy.userId]|bucketSample(19468 + normandy.request_time / (24*60*60*1000) + 7, 7, 7000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719532724	app.normandy.recipe-runner	ERROR	Error checking filter for "Heartbeat: Daily Viewpoint Survey (fr)". Filter: [(normandy.channel in ["release"]) && (normandy.locale in ["fr"]) && (['rolling-viewpoint', normandy.userId]|bucketSample(19468 + normandy.request_time / (24*60*60*1000) + 7, 7, 7000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719532743	app.normandy.recipe-runner	ERROR	Error checking filter for "Heartbeat: Daily Viewpoint Survey (ru)". Filter: [(normandy.channel in ["release"]) && (normandy.locale in ["ru"]) && (['rolling-viewpoint', normandy.userId]|bucketSample(19468 + normandy.request_time / (24*60*60*1000) + 7, 7, 7000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719532757	app.normandy.recipe-runner	ERROR	Error checking filter for "Heartbeat: Daily Viewpoint Survey (es)". Filter: [(normandy.channel in ["release"]) && (normandy.locale in ["es","es-MX"]) && (['rolling-viewpoint', normandy.userId]|bucketSample(19468 + normandy.request_time / (24*60*60*1000) + 7, 7, 7000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719532773	app.normandy.recipe-runner	ERROR	Error checking filter for "Heartbeat: Daily Viewpoint Survey (es-ES)". Filter: [(normandy.channel in ["release"]) && (normandy.locale in ["es-ES"]) && (['rolling-viewpoint', normandy.userId]|bucketSample(19468 + normandy.request_time / (24*60*60*1000) + 7, 7, 7000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719532791	app.normandy.recipe-runner	ERROR	Error checking filter for "Heartbeat: Daily Viewpoint Survey (pl)". Filter: [(normandy.channel in ["release"]) && (normandy.locale in ["pl"]) && (['rolling-viewpoint', normandy.userId]|bucketSample(19468 + normandy.request_time / (24*60*60*1000) + 7, 7, 7000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719532808	app.normandy.recipe-runner	ERROR	Error checking filter for "Heartbeat: Daily Viewpoint Survey (pt-PT)". Filter: [(normandy.channel in ["release"]) && (normandy.locale in ["pt-PT"]) && (['rolling-viewpoint', normandy.userId]|bucketSample(19468 + normandy.request_time / (24*60*60*1000) + 7, 7, 7000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719532822	app.normandy.recipe-runner	ERROR	Error checking filter for "Heartbeat: Daily Viewpoint Survey (pt-BR)". Filter: [(normandy.channel in ["release"]) && (normandy.locale in ["pt-BR"]) && (['rolling-viewpoint', normandy.userId]|bucketSample(19468 + normandy.request_time / (24*60*60*1000) + 7, 7, 7000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719532837	app.normandy.recipe-runner	ERROR	Error checking filter for "Heartbeat: Daily Viewpoint Survey (ja)". Filter: [(normandy.channel in ["release"]) && (normandy.locale in ["ja","ja-JP-mac"]) && (['rolling-viewpoint', normandy.userId]|bucketSample(19468 + normandy.request_time / (24*60*60*1000) + 7, 7, 7000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719532851	app.normandy.recipe-runner	ERROR	Error checking filter for "Heartbeat: Daily Viewpoint Survey (zh-CN)". Filter: [(normandy.channel in ["release"]) && (normandy.locale in ["zh-CN"]) && (['rolling-viewpoint', normandy.userId]|bucketSample(19468 + normandy.request_time / (24*60*60*1000) + 7, 7, 7000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719532865	app.normandy.recipe-runner	ERROR	Error checking filter for "Heartbeat: Daily Viewpoint Survey (zh-TW)". Filter: [(normandy.channel in ["release"]) && (normandy.locale in ["zh-TW"]) && (['rolling-viewpoint', normandy.userId]|bucketSample(19468 + normandy.request_time / (24*60*60*1000) + 7, 7, 7000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719532878	app.normandy.recipe-runner	ERROR	Error checking filter for "Heartbeat: Daily Viewpoint Survey (en)". Filter: [(normandy.channel in ["release"]) && (normandy.locale in ["en-AU","en-GB","en-CA","en-NZ","en-ZA","en-US"]) && (['rolling-viewpoint', normandy.userId]|bucketSample(19468 + normandy.request_time / (24*60*60*1000) + 7, 7, 7000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
1723719532919	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe Disable background task on macOS because PreferenceExperimentAction was disabled during preExecution.
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719532934	app.normandy.recipe-runner	ERROR	Error checking filter for "Heartbeat: Daily Viewpoint Survey (it)". Filter: [(normandy.channel in ["release"]) && (normandy.locale in ["it"]) && (['rolling-viewpoint', normandy.userId]|bucketSample(19468 + normandy.request_time / (24*60*60*1000) + 7, 7, 7000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
1723719532947	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe Page load time patch beta because PreferenceExperimentAction was disabled during preExecution.
1723719532960	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe Page load time patch because PreferenceExperimentAction was disabled during preExecution.
1723719532974	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe Page load time patch ESR because PreferenceExperimentAction was disabled during preExecution.
1723719532986	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe HTTP download configuration because PreferenceExperimentAction was disabled during preExecution.
1723719532996	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe Normandy Diagnostic v128 because PreferenceExperimentAction was disabled during preExecution.
1723719533011	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe Normandy Diagnostic v129 Beta because PreferenceExperimentAction was disabled during preExecution.
attribute_error: normandy.country [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719533567	app.normandy.recipe-runner	ERROR	Error checking filter for "pref-rollout-activity-stream-pkt-new-tab-release69-layout-1577008". Filter: [(normandy.locale in ["en-US"]) && (normandy.country in ["US"]) && (normandy.channel in ["release"]) && ((env.version|versionCompare("69.!")>=0)&&(env.version|versionCompare("69.*")<0)) && ([729,normandy.userId]|bucketSample(639,940,1000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
1723719533581	app.normandy.action.BranchedAddonStudyAction	WARN	Skipping recipe DoH US Engagement Study V2 - Add-on helper because BranchedAddonStudyAction was disabled during preExecution.
attribute_error: normandy.country [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719533598	app.normandy.recipe-runner	ERROR	Error checking filter for "DoH US Staged Rollout to All US Desktop Users". Filter: [(normandy.country in ["US"]) && (normandy.channel in ["release"]) && (["doh-rollout",normandy.userId]|bucketSample(0,9900,10000)) && ((env.version|versionCompare("76.!")>=0)&&(env.version|versionCompare("91.*")<0))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” [browser.xhtml](chrome://browser/content/browser.xhtml)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://logs.netflix.com/log/wwwsw/cl/2. (Reason: CORS request did not succeed). Status code: (null).

Could not start Browser Toolbox, you need to enable it. [Launcher.sys.mjs:64:15](resource://devtools/client/framework/browser-toolbox/Launcher.sys.mjs)
AboutHomeStartupCache: requestCache called with no _procManager! [BrowserGlue.sys.mjs:6347:16](resource:///modules/BrowserGlue.sys.mjs)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://logs.netflix.com/log/wwwsw/cl/2. (Reason: CORS request did not succeed). Status code: (null).

Could not start Browser Toolbox, you need to enable it. [Launcher.sys.mjs:64:15](resource://devtools/client/framework/browser-toolbox/Launcher.sys.mjs)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://logs.netflix.com/log/wwwsw/cl/2. (Reason: CORS request did not succeed). Status code: (null).
2
NotFoundError: No such JSProcessActor 'DevToolsProcess' 3
attribute_error: normandy.country [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719560642	app.normandy.recipe-runner	ERROR	Error checking filter for "Initial rollout of TCP". Filter: [(normandy.country in ["RU","UA"]) && (((normandy.channel in ["release"]&&["tcp-east-eu-rollout",normandy.userId]|bucketSample(0,10000,10000)&&(env.version|versionCompare("91.!")>=0)&&(env.version|versionCompare("120.*")<0))||(normandy.channel in ["beta"]&&["tcp-east-eu-rollout",normandy.userId]|bucketSample(0,10000,10000)&&(env.version|versionCompare("99.!")>=0)&&(env.version|versionCompare("120.*")<0))))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719560656	app.normandy.recipe-runner	ERROR	Error checking filter for "Heartbeat: Daily Viewpoint Survey (de)". Filter: [(normandy.channel in ["release"]) && (normandy.locale in ["de"]) && (['rolling-viewpoint', normandy.userId]|bucketSample(19468 + normandy.request_time / (24*60*60*1000) + 7, 7, 7000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)
1723719560670	app.normandy.recipe-runner	ERROR	Error checking filter for "Heartbeat: Daily Viewpoint Survey (fr)". Filter: [(normandy.channel in ["release"]) && (normandy.locale in ["fr"]) && (['rolling-viewpoint', normandy.userId]|bucketSample(19468 + normandy.request_time / (24*60*60*1000) + 7, 7, 7000))]. Error: "TypeError: NetworkError when attempting to fetch resource." [Log.sys.mjs:722](resource://gre/modules/Log.sys.mjs)
attribute_error: normandy.request_time [Targeting.sys.mjs:128:15](resource://messaging-system/targeting/Targeting.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [Targeting.sys.mjs:152:21](resource://messaging-system/targeting/Targeting.sys.mjs)

**Comment by filips123** [comment]
Errors in the runtime log look unrelated to this problem...

Please enable debug logging for the native program (with `DEBUG` file), update web apps and also provide the native logs (`firefoxpwa.log`, `firefoxpwa-stdout.log` and `firefoxpwa-stderr.log`). Maybe the icons weren't downloaded properly for some reason.

**Comment by hardwareadictos** [comment]
Same issue here. How can i enable debug mode?

**Comment by filips123** [comment]
You can check instructions for enabling debug mode [here](https://pwasforfirefox.filips.si/help/troubleshooting/#obtaining-native-logs).

**Comment by hardwareadictos** [comment]
Here you have the error:

```
Caused by:
    0: Failed to load raster icon
    1: The image format could not be determined
09:54:03 [WARN] Falling back to the next available icon
09:54:03 [WARN] No compatible or working icon was found
09:54:03 [WARN] Falling back to the generated icon from the name
```

**Comment by filips123** [comment]
Can you please also show the full log, or at least the URL of website and icons?

**Comment by hardwareadictos** [comment]
Hey! Seems it's fixed by it's own! No more issues here with icons

**Comment by Rexadev** [comment]
In the latest version yes

**Comment by filips123** [comment]
Maybe there was just some problem with the website or icons were corrupted for some reason. I'll close the issue as it seems it has been resolved.
