### ISSUE TITLE
Old PWA is not removed from Control Panel\Programs\Programs and Features

### ISSUE THREAD

**Issue by Rexadev** [filips123/PWAsForFirefox#534]
### Description

![image](https://github.com/user-attachments/assets/9a23754f-1a13-4207-ad00-776da90a49fc)

### Environment

* Operating system: Windows 11
* System architecture: x64
* Desktop environment: 
* Installation method: 
* PWAsForFirefox extension version:
* PWAsForFirefox native version:
* PWAsForFirefox runtime version:
* Firefox version:

**Comment by filips123** [comment]
How did you uninstall the old PWA the first time?

**Comment by Rexadev** [comment]
Uninstalling it from control panel does nothing and yes I may have deleted and again added PWA from the addon

**Comment by filips123** [comment]
If you deleted the config file without uninstalling PWAs first, then they cannot be uninstalled from the program anymore, as the program doesn't know they still exist. You can manually remove it by deleting the correct registry key in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall` with registry editor (regedit). The key should be named `FFPWA-some-id`, but you will need to manually check which ID is your PWA.

**Comment by filips123** [comment]
I will close this issues because it seems to have happened because you deleted the config file without uninstalling PWAs first.
