### ISSUE TITLE
WaterFox support

### ISSUE THREAD

**Issue by evincedbenyaakobi** [filips123/PWAsForFirefox#536]
### Problem Description
Hi,
So some of us use forks of FireFox like WaterFox. Are there any plans to support any of them?

### Proposed Solution
I assume that the native part is looking for the FireFox process so I guess looking for the WaterFox process would solve this. 
WaterFox is also regularly updated with the FireFox base code so I don't think there should be any problems.

### Additional Information
I already tried using it on WaterFox out of the box and it seems to not work so I can only assume the native part is looking for the FireFox process.

btw, I use Ubuntu Cinnamon 24.04. 
Tried it with native 2.12.1 and extension 2.12.1

**Comment by evincedbenyaakobi** [comment]
nvm, it seems that it doesn't work because waterfox is flatpak based

**Comment by filips123** [comment]
Yeah, Flatpak-based browsers won't work. But if you download normal Waterfox directly from their website, it should work out-of-the-box.
