### ISSUE TITLE
Open all external links in new browser window

### ISSUE THREAD

**Issue by jdt1** [filips123/PWAsForFirefox#537]
### Problem Description

I am using PWAsForFirefox to use Gmail and Outlook. Every time I click a link in an email, it opens inside the same window. Inside this window, I am not logged in on any website (because the PWAs use a different profile), and to return to my mailbox I have to either go back (often multiple pages), or close and re-open the app.

### Proposed Solution

Add an option to open all external links (links that are not on the domain where the PWA is hosted) with the default system browser.

**Comment by filips123** [comment]
This is already possible with [open out-of-scope URLs in a default browser](https://pwasforfirefox.filips.si/user-guide/browser/#open-out-of-scope-urls-in-a-default-browser) option. To make Gmail and Outlook work, you will also need to specify [a few domains](https://pwasforfirefox.filips.si/resources/specific-website-tips/#websites-with-multiple-domains).

**Comment by jdt1** [comment]
That's exactly what I was looking for, thanks!
