### ISSUE TITLE
Install Button not seen in extension menu at 125% zoom

### ISSUE THREAD

**Issue by deekshithanand** [filips123/PWAsForFirefox#540]
### Description

The install button isnt seen on extension menu when trying to install PWA, when the display configuration is set to have a 125% zoom on wayland. (Not to be confused with browser zoom)

### Steps to Reproduce

1. Go to any site with pwa support
3. Click on install this site
4. Scroll down to install this site button on extension pop up
5. Unable to see install button 

### Additional Information

- Make the extension menu scrollable

### Affected Websites

* ...
* ...

### Environment

* Operating system: fedora 40
* System architecture: x64
* Desktop environment: KDE
* Installation method: RPM
* PWAsForFirefox extension version: 2.12.1
* PWAsForFirefox native version: 2.12.1
* PWAsForFirefox runtime version: 2.12.1
* Firefox version: 129.0

Screen-shot for reference:
![bug_report](https://github.com/user-attachments/assets/3c9c8730-0258-4f6f-9336-3a585803b039)

**Comment by filips123** [comment]
This is a known problem with fractional scaling on Linux, but unfortunately I don't know why it happens and how to fix it. See #230. I'll probably add this to FAQ at some point.
