### ISSUE TITLE
Despite updating to latest native, extension doesn't recognize the update

### ISSUE THREAD

**Issue by user9713** [filips123/PWAsForFirefox#541]
### Description

The extension says the Native version is outdated despite installing the update. After you go to the download page, download the MSI file, and restart fire, the extension still says (and shows) that the Native version is outdated.

### Steps to Reproduce

1. Go to the download page for the Native file ("Update Progressive Web Apps for Firefox")
2. Click on the link for "PWAsForFirefox MSI installer"
3. Install the program, selecting "All Users On This Computer"
4. Close and Restart Firefox after installation is finished
5. Go inside the Firefox Extension Page and you will see that it still says the Native version is outdated

* Operating system: Windows 10
* System architecture: x64
* Installation method: MSI
* PWAsForFirefox extension version: 2.12.1
* PWAsForFirefox native version: 2.11.1 (it should be 2.12.1)
* PWAsForFirefox runtime version: Not sure where to find this info
* Firefox version: 129.0.1 (64-bit)

**Comment by filips123** [comment]
Have you previously installed PWAsForFirefox per user? If so, that version has priority over the machine wide installation. If you go to settings or control panel, you should see two PWAsForFirefox installations, and you should remove the old one.

**Comment by user9713** [comment]
> Have you previously installed PWAsForFirefox per user? If so, that version has priority over the machine wide installation. If you go to settings or control panel, you should see two PWAsForFirefox installations, and you should remove the old one.

This fixed, it, thanks!

Apologies if this has been addressed before; I looked through troubleshooting guide and did a search here before creating a bug report, but I couldn't find anything about it.

**Comment by filips123** [comment]
There are already existing bug reports about this (you can see most of them linked from #268), but yeah, it's quite hard to find them unless you know exactly what you're looking for. I will add this to the FAQ page to make it more visible.
