### ISSUE TITLE
%1 is not a valid Win32 application

### ISSUE THREAD

**Issue by MicrosoftwareStudios** [filips123/PWAsForFirefox#546]
### Description
I followed the proper procedure for installation and I installed outlook as a PWA. I go to open it, and CMD opens for 0.5 seconds and closes again with what looked like 2 lines of info. I then followed the troubleshooting instructions and ran the command at the bottom. I got the error that is the title.
I am running x32 windows 8.1 on an asus t100ta
### Steps to Reproduce

1. Install the extension/runtime
2. Install outlook.com as a PWA
3. Open it

### Additional Information

Windows 8.1 32-bit operating system with current version of Firefox installed
Could this be x86 architecture related?
C:\Users\******>firefoxpwa site launch 01J6D1B2WCWDTE5EBFPQD3KRW6 -- --js
console
18:14:26 [INFO] Launching the web app
18:14:26 [ERROR] %1 is not a valid Win32 application. (os error 193)

01J6D1B2WCWDTE5EBFPQD3KRW6 being the ID of https://outlook.live.com/mail/0

### Affected Websites

all sites:
i tried
youtube
office
outlook

### Environment

Firefox

* Operating system: Windows 8.1
* System architecture: x86
* Desktop environment: 
* Installation method:  MSI
* PWAsForFirefox extension version: 2.12.1
* PWAsForFirefox native version: ?
* PWAsForFirefox runtime version: ?
* Firefox version: 115.14.0esr (32-bit)

**Comment by filips123** [comment]
This is because Windows 8 is no longer supported by Firefox. You can check a temporary workaround [here](https://github.com/filips123/PWAsForFirefox/issues/522#issuecomment-2232614697), but you should soon update to a supported system.
