### ISSUE TITLE
Status / Availability Indicators Broken (Teams, SLACK, etc)

### ISSUE THREAD

**Issue by influential-eliot** [filips123/PWAsForFirefox#551]
### Description

When running Teams or SLACK (_or I'd imagine any other PWA which ostensibly manages your status_) the PWA seems unable to detect activity outside of the window itself.

### Steps to Reproduce

1. Create a Teams or SLACK PWA
2. Watch it make you either offline or away

### Additional Information

Not really sure what else to add here, as I don't really know what I don't know, sorry.

Have tried with and without customised userAgent strings to mimick chromium.

### Affected Websites

So far I can only see this here
* teams
* slack

### Environment

Debian 12 Wayland Gnome3
Firefox 130.0 ESR (I believe ... can't remember)
firefoxpwa 2.12.1

### Further Investigation
I wonder if this is down to 'device use' and the fact that there appears to be a chromium flag for this type of site permission, but on a (_very casual_) search I could not find a similar setting or `about:config` setting for FF.

**Comment by filips123** [comment]
Do you mean status like "online/offline/idle" or activity status like "Playing ...", "Viewing ..."?

Can you check if this status works if you just open Slack/Teams in normal Firefox, without installing it as a PWA, and in Chrome/Edge, also without installing it as a PWA?

**Comment by influential-eliot** [comment]
I can check with Firefox Nightly (latest) and Ungoogled Chromium latest.

To confirm for anyone that may not be clear (_not suggesting that has just happened_): This is where the PWA monitors the system for activity, and decides whether or not the user is active or not. This is not where a user changes their own status.

**Comment by influential-eliot** [comment]
OK, yeah, it's still happening in the windows, so it's probably a browser based thing. Apologies for bothering you on that.
 
Also, I see the issue in Ungoogled Chromium, too (_with Teams_).
 
I imagine that if/when Firefox looks at this device activity setting this might be something to be aware of, mind. Apologies again!
