### ISSUE TITLE
Change Display Name for Runtime

### ISSUE THREAD

**Issue by Rexadev** [filips123/PWAsForFirefox#554]
Change Display name to `Mozilla Firefox PWA Runtime` like in Registry `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Mozilla Firefox 128.0.3 (x64 en-US)`

**Comment by filips123** [comment]
Do you mean the name that is displayed in the Task Manager?

**Comment by Rexadev** [comment]
> Do you mean the name that is displayed in the Task Manager?

That too if possible, everywhere I meant in registry no it appears different in control panel>apps and features and Settings apps

**Comment by filips123** [comment]
But the runtime is not added to the registry anywhere and should not appear in settings... The only way anything gets written to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Mozilla Firefox ...` is with the normal Firefox installer, and that installer is not executed when extracting the runtime for PWAsForFirefox.

That registry key is probably just from your normal Firefox installation.

**Comment by filips123** [comment]
Unfortunately, changing the name that is displayed in the Task Manager is not possible, as it's embedded in the Firefox EXE. For issues related to incorrect shortcuts (and registry keys?) and onboarding process, see #210.
