### ISSUE TITLE
Extension has been temporarily disabled / Only old versions are available

### ISSUE THREAD

**Issue by filips123** [filips123/PWAsForFirefox#556]
**Update:**

Version 2.12.3 has been approved and is now available, so the issue has been resolved.

---

**TLDR:**

If you already have the extension version 2.12.1 or later installed, you can continue using it. Once newer versions are released, you can normally update to them.

If you do not have the extension installed yet, **do not** install old versions (1.3.2 and 1.4.2), as they may not work properly and contain security vulnerabilities. Please wait until the issue is resolved and new versions are released.

---

All existing versions of the extension (except 1.3.2 and 1.4.2 for some reason) have been disabled by the Add-ons Review Team, because apparently the extension violates [Add-on Policies](https://extensionworkshop.com/documentation/publish/add-on-policies/#data-disclosure-collection-and-management). The problem is that the extension does provide users the choice to uninstall the extension if they do not agree to collecting the tab URLs and sending them to the native program, which is required by the Add-on Policies for extensions that use the Native Messaging API.

To comply with the Add-On Policies, I've released [v2.12.3](https://github.com/filips123/PWAsForFirefox/releases/tag/v2.12.3), which adds a "Decline and Uninstall" button to the license and privacy agreement screen on the extension setup page. If the user declines the agreement, the extension will be automatically uninstalled.

The new version has already been submitted to AMO, but is currently waiting to be reviewed by the Add-ons Review Team. Once it is reviewed and approved, it should become available.

You can also read more details [here](https://github.com/filips123/PWAsForFirefox/discussions/550#discussioncomment-10592162).

---

For reference, this is the extension's privacy policy:

> The extension exchanges personal data (current website and manifest URLs, as well as other PWA details) with the native program when the user initiates the web app installation. This is necessary in order to correctly obtain and parse the Web Application Manifest and install the web app. Data are stored on the computer as long as that web app is installed. No personal data leave the computer or are sent to third parties.

The policy hasn't changed. The only thing that has changed is that now you can uninstall the extension directly through the setup page if you do not agree to the policy, while previously, you had to manually uninstall it through Firefox settings.

**Comment by kimjongbing** [comment]
If for some reason the addons review team does not accept your appeal, would it be possible to manually download the latest version of the extension?

**Comment by filips123** [comment]
I think I can still download XPI file for 2.12.1, but I'm not sure if users can actually install it or is it blocked. But I will wait for now, as maybe providing the XPI file could be considered circumventing the policies.

I've added an uninstall button like requested in the policies, so it's unlikely that they will reject it. But it might take a few days until it's reviewed.
