### ISSUE TITLE
Installing extensions not working

### ISSUE THREAD

**Issue by Dajova** [filips123/PWAsForFirefox#557]
### Description

Installing extension via PWA is not working correctly. Installing on the native browser works fine, just not via PWA.

### Steps to Reproduce

1. Go to the addons section for firefox
2. Go to any extension you want to install
3. Click on "Add to Firefox"
4. Nothing happens, not even the popup saying if i want to install the addon or not

### Additional Information

Not much else is happening, it just endlessly shows the "installing" animation. I know you can sync your account to install them that way, but i dont wanna use that method to just install a single extension then remove the rest of them.

### Affected Websites

https://addons.mozilla.org/en-US/firefox/extensions/

**Comment by filips123** [comment]
I can reproduce this, but only on one profile, while it works fine on others. I'm not sure why it happens though and how to fix it.

Please create a new PWA profile and check if it works there for you.

**Comment by Dajova** [comment]
A fresh profile seem to work fine, just not either of my older ones.

**Comment by filips123** [comment]
Somehow, it started working for me in that profile. I'm not sure what I did. The problem now is that I cannot reproduce it anymore, so it's now even harder to fix...

I though it might be because something broke when updating the profile to 130, but I tried to create the profile in 128.0.2 and update it to 130, and extension installation still worked fine. So I still don't know why this happens.

**Comment by konekoangel** [comment]
The workaround I found is manually copying the .xpi and adding the corresponding entry in the extension.json file.

**Comment by filips123** [comment]
Can you check if there are any errors in [runtime logs](https://pwasforfirefox.filips.si/help/troubleshooting/#obtaining-runtime-logs) when you try to install the extension? Please enable Multiprocess mode in the Browser Toolbox.

Also, please try to install the extension from `about:addons`, both from file and one of the recommended extensions, and also provide logs from there.

**Comment by konekoangel** [comment]
This error shows up everytime I try to install an extension from the add-ons store or from about:addons (both from recommended extensions and from a local file).

![Capture d'écran 2024-09-15 193004](https://github.com/user-attachments/assets/41dcf3dc-369f-468a-a523-a14fe5daee12)

**Comment by AthreyaV** [comment]
Can confirm, all my existing PWAs are broken and can no longer install extensions. Recreated them individually in new profiles and it works just fine on the new profiles. Another thing to add, the "broken profiles" also cannot remove already installed extensions, as the delete button just seems to do nothing at all.

**Comment by filips123** [comment]
Can you try the steps mentioned [here](https://github.com/filips123/PWAsForFirefox/issues/559#issuecomment-2349091166)? That should fix the error, but I'm not sure if that error is actually related to this issue.

**Comment by konekoangel** [comment]
Setting browser.sessionstore.idleDelay to 180 works for me. The value was -1 before. Thank you !

**Comment by peldas** [comment]
Changing that setting from -1 to 180 worked for me too, and now my previously installed extensions also work properly too! Thank you @filips123 😊

**Comment by filips123** [comment]
Nice to see that. The fix is available in 2.12.4, so it should now be enough to update the native program to that version.
