### ISSUE TITLE
[Regression] Touchpad Swipe Gestures (Back and Forward) don't work

### ISSUE THREAD

**Issue by LSeelig** [filips123/PWAsForFirefox#558]
### Description

The two-finger swipes left and right that trigger forward and back respectively do not work in any PWA. They do not show the visual cue (blue arrow pulled from the side of the screen), and there is no indication that the gesture was recognized or that any error occurred.

### Steps to Reproduce

1. Go to '....'

### Additional Information
This does not occur in the browser (either my existing install (130) or the Firefox Linux binary package (130)), and it worked prior to the 130 update. I can use two finger horizontal scrolling, so Firefox is able to read touchpad gestures. I verified that the problem wasn't with back/forward navigation itself, as I could use it in the browser if I followed the same steps, and I could still use alt+left/right arrow to go back and forward in the PWA.

I am running Fedora 40 Workstation on Linux, and I verified both the PWAs and the browser(s) were running the exact same version (130.0). I did not test in a VM, as touchpad gestures don't actually work in my session, so there may be something related to my configuration, but the fact the browser still works doesn't seem to suggest that. I guess the only way to know is if other Fedora-GNOME-Wayland-FracScaling(?) users have the same issue.
 
There were no errors in the logs.

### Environment

* Operating system: Fedora Linux 40 (Workstation Edition)
* System architecture: x86_64
* Desktop environment: GNOME 46
* Installation method: RPM
* PWAsForFirefox extension version: 2.12.3
* PWAsForFirefox native version: 2.12.3
* PWAsForFirefox runtime version: 130.0
* Firefox version: 130.0

**Comment by filips123** [comment]
Can you check if it works if you install PWA into a new profile please?

**Comment by LSeelig** [comment]
> Can you check if it works if you install PWA into a new profile please?

Still doesn't work :/.

**Comment by LSeelig** [comment]
Can confirm I'm no longer affected...and it does say my native connector is on 2.12.4 (though extension still .3 because Firefox addons take forever to be approved, I assume).

**Comment by botkero** [comment]
On the latest version, it doesn't work anymore :/ (v.2.12.5)

**Comment by filips123** [comment]
Please also try it in a fresh profile, and check if there are any errors in the [runtime logs](https://pwasforfirefox.filips.si/help/troubleshooting/#obtaining-runtime-logs).

**Comment by botkero** [comment]
> Please also try it in a fresh profile, and check if there are any errors in the [runtime logs](https://pwasforfirefox.filips.si/help/troubleshooting/#obtaining-runtime-logs).

in a fresh profile it seems to be fine.
