### ISSUE TITLE
Arch Linux - Firefox PWA process hangs then crashes when closed

### ISSUE THREAD

**Issue by AndreaLeidi** [filips123/PWAsForFirefox#560]
### Description

On my endeavourOS (Arch linux ), Firefox PWA process hangs for something like 30 seconds then crashes (with a crash report window) every time I close a PWA.

![Istantanea_2024-09-15_21-02-23](https://github.com/user-attachments/assets/09d5456a-2d3e-431e-bbf6-aa6c49573bb8)

### Steps to Reproduce

On Arch Linux x64 bleeding-edge up to date:

1. Install latest Firefox release from Arch repo with pacman 

sudo pacman -S firefox

2. Install firefox-pwa-bin or firefox-pwa package from AUR repo

3. Install firefox pwa browser extension directly from Mozilla add-ons. Follow step-by-stem installation process and get no errors.

4. Open any website and install it as a PWA using the app. Use a separate-app profile as suggested. I tried Google keep, Google Earth, Whatsapp web,

5. Run the PWA.

6. Close the PWA. A Firefox process hangs in process list, then crashes after about 30 seconds showing a crash notice and a crash log to be sent to Mozilla.

### Additional Information

Enable/disable graphic acceleration makes no differences.
Permisisons on ~/.local/share/firefoxpwa... are 755 on folders and 644 on files.

Crash log:

AbortMessage: xpcom_runtime_abort(###!!! ABORT: file resource://gre/modules/CrashMonitor.sys.mjs:165)
AdapterDeviceID: 0x699f
AdapterDriverVendor: mesa/radeonsi
AdapterDriverVersion: 24.2.2.0
AdapterVendorID: 0x1002
Add-ons: formautofill%40mozilla.org:1.0.1,pictureinpicture%40mozilla.org:1.0.0,webcompat%40mozilla.org:130.2.0,default-theme%40mozilla.org:1.3,addons-search-detection%40mozilla.com:2.0.0
AsyncShutdownTimeout: {"phase":"IOUtils: waiting for profileBeforeChange IO to complete","conditions":[{"name":"CrashMonitor: Writing notifications to file after receiving profile-before-change and awaiting all checkpoints written","state":{"profile-after-change":true,"final-ui-startup":true,"sessionstore-windows-restored":true,"quit-application-granted":true,"quit-application":true,"profile-change-net-teardown":true,"profile-change-teardown":true,"profile-before-change":true},"filename":"resource://gre/modules/CrashMonitor.sys.mjs","lineNumber":165,"stack":["resource://gre/modules/CrashMonitor.sys.mjs:init:165","resource://gre/modules/nsCrashMonitor.sys.mjs:observe:20"]}]}
AvailablePageFile: 15360430080
AvailablePhysicalMemory: 11914706944
AvailableSwapMemory: 12884897792
AvailableVirtualMemory: 14611890176
BackgroundTaskMode: 0
BuildID: 20240829075237
ContentSandboxCapabilities: 119
ContentSandboxCapable: 1
ContentSandboxLevel: 4
CrashTime: 1726424211
DOMFissionEnabled: 1
DOMIPCEnabled: 1
DesktopEnvironment: xfce
EMCheckCompatibility: true
GpuSandboxLevel: 0
GraphicsNumActiveRenderers: 1
GraphicsNumRenderers: 0
HeadlessMode: 0
InstallTime: 1726400066
IsWayland: 0
LastInteractionDuration: 52
LastStartupWasCrash: 0
LinuxUnderMemoryPressure: 0
MozCrashReason: [Parent 470298, Main Thread] ###!!! ABORT: file resource://gre/modules/CrashMonitor.sys.mjs:165
Notes: EndeavourOSFP(D00-L1000-W0000000-T01) WR? WR+ EGL? EGL- GL Context? GL Context+ xpcom_runtime_abort(###!!! ABORT: file resource://gre/modules/CrashMonitor.sys.mjs:165)
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: release
SafeMode: 0
SecondsSinceLastCrash: 68
ShutdownProgress: profile-before-change
ShutdownReason: AppClose
StartupCacheValid: 1
StartupCrash: 0
StartupTime: 1726424146
SubmittedFrom: Client
TelemetryClientId: 46b5c914-ae85-4d36-bbf7-599ad7e3dba8
TelemetryEnvironment: {"build":{"applicationId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","applicationName":"Firefox","architecture":"x86-64","buildId":"20240829075237","version":"130.0","vendor":"Mozilla","displayVersion":"130.0","platformVersion":"130.0","xpcomAbi":"x86_64-gcc3","updaterAvailable":true},"partner":{"distributionId":"firefoxpwa","distributionVersion":"2.12.3","partnerId":null,"distributor":null,"distributorChannel":null,"partnerNames":[]},"system":{"memoryMB":15916,"virtualMaxMB":null,"cpu":{"count":8,"cores":4,"vendor":"GenuineIntel","name":"Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz","family":6,"model":60,"stepping":3,"l2cacheKB":256,"l3cacheKB":8192,"speedMHz":4000,"extensions":["hasMMX","hasSSE","hasSSE2","hasSSE3","hasSSSE3","hasSSE4_1","hasSSE4_2","hasAVX","hasAVX2","hasAES"]},"os":{"name":"Linux","version":"6.10.10-zen1-1-zen","locale":"it-IT","distro":"EndeavourOS","distroVersion":"2023.08.05"},"hdd":{"profile":{"model":null,"revision":null,"type":null},"binary":{"model":null,"revision":null,"type":null},"system":{"model":null,"revision":null,"type":null}},"gfx":{"D2DEnabled":null,"DWriteEnabled":null,"ContentBackend":"Skia","Headless":false,"EmbeddedInFirefoxReality":null,"TargetFrameRate":60,"textScaleFactor":1,"adapters":[{"description":"AMD Radeon RX 550 / 550 Series (radeonsi, polaris12, LLVM 18.1.8, DRM 3.57, 6.10.10-zen1-1-zen)","vendorID":"0x1002","deviceID":"0x699f","subsysID":null,"RAM":0,"driver":null,"driverVendor":"mesa/radeonsi","driverVersion":"24.2.2.0","driverDate":null,"GPUActive":true}],"monitors":[{"screenWidth":1920,"screenHeight":1080,"defaultCSSScaleFactor":1,"contentsScaleFactor":1}],"features":{"compositor":"webrender","hwCompositing":{"status":"available"},"gpuProcess":{"status":"unused"},"webrender":{"status":"available"},"wrCompositor":{"status":"blocked:FEATURE_FAILURE_DISABLE_RELEASE_OR_BETA"},"openglCompositing":{"status":"available"},"omtp":{"status":"unused"}}},"appleModelId":null,"hasWinPackageId":null},"settings":{"blocklistEnabled":true,"e10sEnabled":true,"e10sMultiProcesses":8,"fissionEnabled":true,"telemetryEnabled":false,"locale":"en-US","intl":{"requestedLocales":["en-US"],"availableLocales":["en-US"],"appLocales":["en-US"],"systemLocales":["it-IT"],"regionalPrefsLocales":["it-IT"],"acceptLanguages":["en-US","en"]},"update":{"channel":"release","enabled":true,"autoDownload":true,"background":true},"userPrefs":{"browser.search.region":"IT","browser.urlbar.autoFill":true,"browser.urlbar.autoFill.adaptiveHistory.enabled":false,"browser.urlbar.dnsResolveSingleWordsAfterSearch":0,"browser.urlbar.quicksuggest.dataCollection.enabled":false,"browser.urlbar.suggest.quicksuggest.nonsponsored":false,"browser.urlbar.suggest.quicksuggest.sponsored":false,"general.config.filename":"<set>","media.gmp-gmpopenh264.enabled":false,"media.gmp-gmpopenh264.lastInstallStart":1726424073,"media.gmp-gmpopenh264.lastDownload":1726424075,"media.gmp-gmpopenh264.lastUpdate":1726424075,"network.trr.strict_native_fallback":false,"widget.content.gtk-high-contrast.enabled":true},"sandbox":{"effectiveContentProcessLevel":4,"contentWin32kLockdownState":3},"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":false,"defaultSearchEngine":"google-b-d","defaultSearchEngineData":{"loadPath":"[app]google@search.mozilla.org","name":"Google","origin":"default","submissionURL":"https://www.google.com/search?client=firefox-b-d&q="}},"profile":{"creationDate":19981,"firstUseDate":19981},"addons":{"activeAddons":{"formautofill@mozilla.org":{"version":"1.0.1","scope":1,"type":"extension","updateDay":19981,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Form Autofill","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19981,"quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false},"pictureinpicture@mozilla.org":{"version":"1.0.0","scope":1,"type":"extension","updateDay":19981,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Fixes for web compatibility with Picture-in-Picture","name":"Picture-In-Picture","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19981,"quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false},"webcompat@mozilla.org":{"version":"130.2.0","scope":1,"type":"extension","updateDay":19981,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Urgent post-release fixes for web compatibility.","name":"Web Compatibility Interventions","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19981,"quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false}},"theme":{"id":"default-theme@mozilla.org","blocklisted":false,"description":"Follow the operating system setting for buttons, menus, and windows.","name":"System theme — auto","userDisabled":false,"appDisabled":false,"version":"1.3","scope":4,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19981,"updateDay":19981},"activeGMPlugins":{}},"experiments":{"long-term-holdback-2024-h2-velocity-desktop":{"branch":"delivery","type":"nimbus-nimbus"},"csv-import-release-rollout":{"branch":"enable-csv-import","type":"nimbus-rollout"},"upgrade-spotlight-rollout":{"branch":"treatment","type":"nimbus-rollout"},"phc-rollout":{"branch":"rollout","type":"nimbus-rollout"},"highlighting-in-pdfs-rollout":{"branch":"treatment","type":"nimbus-rollout"},"consolidated-search-configuration-row-desktop-relaunch":{"branch":"rollout","type":"nimbus-rollout"},"disable-redirects-for-authretries":{"branch":"control","type":"nimbus-rollout"},"tab-hover-preview-release-rollout":{"branch":"control","type":"nimbus-rollout"},"encrypted-client-hello-fallback-mechanism":{"branch":"control","type":"nimbus-rollout"},"fx-accounts-ping-release-rollout-2":{"branch":"control","type":"nimbus-rollout"},"newtab-recommendations-merino-migration-global":{"branch":"control","type":"nimbus-rollout"}}}
TelemetryProfileGroupId: 086a8715-8eaf-4882-a7eb-ce35d93fa099
TelemetryServerURL: https://incoming.telemetry.mozilla.org
TelemetrySessionId: 7984cea8-11f3-4f14-89ab-ec72387296bb
Throttleable: 1
TotalPageFile: 29574496256
TotalPhysicalMemory: 16689598464
UptimeTS: 65.10972795
UtilityProcessStatus: Running
Vendor: Mozilla
Version: 130.0
XPCOMSpinEventLoopStack: default: AsyncShutdown Spinner for profile-before-change
useragent_locale: en-US
This report also contains technical information about the state of the application when it crashed.

### Affected Websites

Every PWA I launch

### Environment

CPU: Intel Core i7-4790
RAM: 16 GiB
GPU: AMD Radeon rx 550 series (4 GiB)

Other Firefox versions installed: TOR browser 13.5.3 (based on Mozilla Firefox 115.15.0esr)
("torbrowser-launcher" package via pacman)

"Firefox-multi-account-containers" extension installed on Firefox. Enabled or disabled makes no differences, same bug.

* Operating system:
Arch Linux - EnveavourOS 
* System architecture:
x64 - kernel 6.10.10-zen-1-1-zen
* Desktop environment: 
XFCE 4.18
* Installation method: 
AUR, I tried both "firefox-pwa" and "firefox-pwa-bin"  packages, same bug. 
* PWAsForFirefox extension version:
2.12.3
* PWAsForFirefox runtime version:
2.12.3-1
* Firefox version:
130.0 (64 bit) (via pacman from Arch repo)

**Comment by filips123** [comment]
This is a known issue. You can check #559 for a workaround. A proper fix will be released soon.
