### ISSUE TITLE
2.12.4 extension missing?

### ISSUE THREAD

**Issue by si458** [filips123/PWAsForFirefox#563]
### Description

extension keeps saying 'the extension is outdated',

### Steps to Reproduce

1. install extensions from firefox installs, shows as 2.12.3
2. install native runtime or reinstall native runtime, installs as 2.13.4

### Affected Websites

* ...
* ...

### Environment

* Operating system: OSX
* System architecture: Intel
* Desktop environment: 
* Installation method: 
* PWAsForFirefox extension version: 2.12.3
* PWAsForFirefox native version: 2.12.4
* PWAsForFirefox runtime version:
* Firefox version: 103.0.1

**Comment by filips123** [comment]
It still hasn't been approved by the review team. It should probably be available in a few days.

**Comment by filips123** [comment]
Version 2.12.4 is now available on AMO.

**Comment by si458** [comment]
Yep thanks! Firefox auto updated itself!
