### ISSUE TITLE
Apps openin to a blank page with no option to do anything.

### ISSUE THREAD

**Issue by fatmonk8** [filips123/PWAsForFirefox#571]
Not sure what is needed here, but this is the log I got when running the "firefoxpwa site launch ID -- --jsconsole" command in the console. 

1727825209774	addons.xpi	WARN	Checking C:\Users\Paul Einsig\AppData\Roaming\FirefoxPWA\runtime\distribution\extensions for addons
TypeError: currentPlacements is undefined CustomizableUI.sys.mjs:3726:11
TypeError: currentPlacements is undefined CustomizableUI.sys.mjs:3726:11
Error: Could not find function openContextMenu hookFunction.jsm:26:11
TypeError: this.editor is null
    UrlbarInput resource:///modules/UrlbarInput.sys.mjs:276
    <anonymous> chrome://browser/content/browser.js:363
    shouldSuppress chrome://browser/content/browser.js:447
    PopupNotifications resource://gre/modules/PopupNotifications.sys.mjs:236
    <anonymous> chrome://browser/content/browser.js:474
    onCreated file:///C:/Users/Paul Einsig/AppData/Roaming/FirefoxPWA/profiles/01J956DN73BC2G811P8PSRWZ1Y/chrome/pwa/content/browser.jsm:1660
    aEventName resource:///modules/CustomizableUI.sys.mjs:3212
    buildWidget resource:///modules/CustomizableUI.sys.mjs:2102
    getWidgetNode resource:///modules/CustomizableUI.sys.mjs:1401
    buildArea resource:///modules/CustomizableUI.sys.mjs:1195
    registerToolbarNode resource:///modules/CustomizableUI.sys.mjs:1109
    registerToolbarNode resource:///modules/CustomizableUI.sys.mjs:4068
    onDOMContentLoaded chrome://browser/content/browser-init.js:150
browser.js:481:13
TypeError: functionContext is null
    hookFunction resource://pwa/utils/hookFunction.jsm:23
    onCreated file:///C:/Users/Paul Einsig/AppData/Roaming/FirefoxPWA/profiles/01J956DN73BC2G811P8PSRWZ1Y/chrome/pwa/content/browser.jsm:1660
    aEventName resource:///modules/CustomizableUI.sys.mjs:3212
    buildWidget resource:///modules/CustomizableUI.sys.mjs:2102
    getWidgetNode resource:///modules/CustomizableUI.sys.mjs:1401
    buildArea resource:///modules/CustomizableUI.sys.mjs:1195
    registerToolbarNode resource:///modules/CustomizableUI.sys.mjs:1109
    registerToolbarNode resource:///modules/CustomizableUI.sys.mjs:4068
    onDOMContentLoaded chrome://browser/content/browser-init.js:150
CustomizableUI.sys.mjs:3217:17
Uncaught TypeError: gURLBar is undefined
    _setInitialFocus chrome://browser/content/browser-init.js:681
browser-init.js:681:11
Uncaught TypeError: gDefaultTheme is undefined
    _resetUIState resource:///modules/CustomizableUI.sys.mjs:3364
    reset resource:///modules/CustomizableUI.sys.mjs:3323
    reset resource:///modules/CustomizableUI.sys.mjs:4545
    configureLayout file:///C:/Users/Paul Einsig/AppData/Roaming/FirefoxPWA/profiles/01J956DN73BC2G811P8PSRWZ1Y/chrome/pwa/content/browser.jsm:1820
CustomizableUI.sys.mjs:3364:5
Uncaught TypeError: window.gFFPWABrowser is undefined
    onCreated file:///C:/Users/Paul Einsig/AppData/Roaming/FirefoxPWA/profiles/01J956DN73BC2G811P8PSRWZ1Y/chrome/pwa/content/browser.jsm:1204
browser.jsm:1204:37
Uncaught TypeError: gURLBar is undefined
    update chrome://browser/content/browser.js:4799
    init chrome://browser/content/browser.js:4726
    onLoad chrome://browser/content/browser-init.js:236
browser.js:4799:5

**Comment by Vitorrecoaro** [comment]
The same problem here, any PWA App, opens a blank page without any option to do any more.

**Comment by fatmonk8** [comment]
> The same problem here, any PWA App, opens a blank page without any option to do any more.

This is probably unrelated, but is your system by chance a newer Intel platform?

**Comment by max-photon** [comment]
I got the same problem 1 hour age. But I solved it after I installed the new version (firefoxpwa-2.12.5-x86_64.msi). FYI.

**Comment by fatmonk8** [comment]
> I got the same problem 1 hour age. But I solved it after I installed the new version (firefoxpwa-2.12.5-x86_64.msi). FYI.

THIS WAS IT! Thank you!

**Comment by fatmonk8** [comment]
> I got the same problem 1 hour age. But I solved it after I installed the new version (firefoxpwa-2.12.5-x86_64.msi). FYI.

THIS WAS IT! Thank you!

**Comment by renaatdemuynck** [comment]
There's a mention of this when you go to 'Manage extension':

> Important: Please make sure to update the native program to v2.12.5 before Firefox 131 is released on 2024-10-01 to fix compatibility issues. You can ignore the outdated extension warning until the new extension version is approved.

**Comment by fatmonk8** [comment]
> There's a mention of this when you go to 'Manage extension':
> 
> > Important: Please make sure to update the native program to v2.12.5 before Firefox 131 is released on 2024-10-01 to fix compatibility issues. You can ignore the outdated extension warning until the new extension version is approved.

Thanks!
