### ISSUE TITLE
PWAs refuse to load. I get an empty white window.

### ISSUE THREAD

**Issue by markusjevringflowers** [filips123/PWAsForFirefox#573]
### Description

Starting on 2024-10-04, PWAs no longer load. They worked fine on 2024-10-02. No matter which PWA I launch, all I get is a white page. The name and the icon load in the taskbar, but they be cached.
![image](https://github.com/user-attachments/assets/e78296ec-7452-4cfb-a6fa-7b0dd8e27790)

### Steps to Reproduce

1. Launch any PWA, existing or new
2. 
### Additional Information

* I tried launching my two existing ones, Gmail and Google Calendar, and they both behaved the same way. 
* I opened the extension. It told me I needed to update the runtime, so I did. Same issue.
* I removed the PWAs and recreated them. Same issue.
* I added a new PWA, slashdot.org, same issue

### Affected Websites

At least:
* gmail
* google calendar
* slashdot.org

### Environment

* Operating system: Windows 11
* System architecture: x86-64
* Installation method: MSI
* PWAsForFirefox extension version: 2.12.4
* PWAsForFirefox native version: firefoxpwa-2.12.4-x86_64.msi
* PWAsForFirefox runtime version: firefoxpwa 2.12.4
* Firefox version: 131.0

### Logs
[firefoxpwa.log](https://github.com/user-attachments/files/17255848/firefoxpwa.log)
[firefoxpwa-stderr.log](https://github.com/user-attachments/files/17255849/firefoxpwa-stderr.log)
[firefoxpwa-stdout.log](https://github.com/user-attachments/files/17255850/firefoxpwa-stdout.log)

This is a screenshot of the console. It looks identical for any PWA I launch: `firefoxpwa site launch $id-- -jsconsole`

![image](https://github.com/user-attachments/assets/eeb1c6e7-2f50-43d4-824a-c03e400a794e)

**Comment by ikigai-ivy** [comment]
Same here with all my websites including YouTube Music, Google Docs and Google Calendar :(

**Comment by awalvie** [comment]
Can confirm, same issue here with Microsoft Teams on Linux

**Comment by jdtaormi** [comment]
Working for me now, thanks!

**Comment by nicolas-oliveira** [comment]
Confirm in all pwa I use: figma, miro, whatsapp etc..

**Comment by markusjevringflowers** [comment]
Confirm: fixed in 2.12.5

**Comment by samrands** [comment]
I ran into this issue even on 2.12.5 and Firefox version 131.0-1. I tried upgrading Firefox to 133.0a1 (the edge version) and that fixed it.

**Comment by filips123** [comment]
2.12.5 has now been fully released.

If you have problems, make sure to update both the extension and the native program to 2.12.5. Also make sure that the extension uses 2.12.5 native version (you can check this in "About the project" in the extension settings). If you still have problems abter updating both to 2.12.5, please run "Patch profiles and runtime" from the extension settings.
