### ISSUE TITLE
Broken GPG signature

### ISSUE THREAD

**Issue by sctech-tr** [filips123/PWAsForFirefox#574]
### Steps to Reproduce

1. Try to update PWAsForFirefox via KDE's app store
2. It says: (typo: "instead" should be "instead of")
![image](https://github.com/user-attachments/assets/5bc6761e-f969-460a-abd5-56f5767eadce)

### Additional Information

It couldn't update for a few days now, but now it can't load the PWAs. It just remains in a blank screen

### Affected Websites

https://music.youtube.com
https://chat.google.com
.
.
etc

### Environment

* Operating system: Fedora Linux 40
* System architecture: x86_64
* Desktop environment: KDE Plasma 6
* Installation method: RPM
* PWAsForFirefox extension version: 2.12.4
* PWAsForFirefox native version: 2.12.4
* PWAsForFirefox runtime version: 
* Firefox version: 130.0.1

**Comment by sctech-tr** [comment]
Duplicate of #571 
but it also has a broken signature

**Comment by sctech-tr** [comment]
It was written in the add-on description

**Comment by filips123** [comment]
Please try [these steps](https://packagecloud.io/filips/FirefoxPWA) to re-add the repository. Maybe this will fix the GPG signature error.
