### ISSUE TITLE
Hulu opens to a blank page

### ISSUE THREAD

**Issue by tdr1995** [filips123/PWAsForFirefox#576]
### Description

I updated to 2.12.5 (runtime and extension) and every site I have installed works except Hulu. It'll load to a blank page. Opening the URL in main Firefox installation works. I've tried running through the troubleshooting steps but couldn't identify the problem.

### Steps to Reproduce

1. Go to https://www.hulu.com/app/
2. Install PWA App
3. Open Hulu's PWA App
4. See blank page

### Additional Information
I've tried clearing all cookies/browser data in the Firefox that loads the app specifically (through the options in the window for the app). I've also tried with all extensions disabled in case their was something weird happening (I had a password manager and an ad-blocker)

![Screenshot 2024-10-04 235631](https://github.com/user-attachments/assets/4979c8f3-56bd-4983-a83a-6d96c76c40f2)
[firefoxpwa.log](https://github.com/user-attachments/files/17265090/firefoxpwa.log)

Above is a screenshot of the console, and the only log I could find. I couldn't find firefoxpwa-stdout.log and firefoxpwa-stderr.log.

### Affected Websites

* https://www.hulu.com/app/

### Environment

* Operating system: Windows 11 23H2
* System architecture: AMD
* Installation method: MSI
* PWAsForFirefox extension version: 2.12.5
* PWAsForFirefox native version:2.12.5
* PWAsForFirefox runtime version: 131.0
* Firefox version: 131.0

**Comment by filips123** [comment]
Can you please try to install it into a new profile?

**Comment by tdr1995** [comment]
> Can you please try to install it into a new profile?

You mean a new profile in the extension settings, right? I did that, and it still opens to a blank page.

**Comment by Saltkringel2** [comment]
I'm experiencing the same thing with Youtube music and Soundcloud. Tried adding a new profile, but get a blank page either way

**Comment by filips123** [comment]
Please obtain and provide the runtime logs as described [here](https://pwasforfirefox.filips.si/help/troubleshooting/#obtaining-runtime-logs).

**Comment by tdr1995** [comment]
I'm not sure why or how this helped but after a crashing issue, Refreshing my copy of Firefox (it was suggested after restarting Firefox resulted in a crash every time) and reinstalling the extension fixed whatever issue I had. Now Hulu opens just fine. I did this in the main Firefox installation, not the PWA version of Firefox.
