### ISSUE TITLE
Copied runtime doesn't display anything

### ISSUE THREAD

**Issue by blacklightpy** [filips123/PWAsForFirefox#584]
### Description

Following this [comment](https://github.com/filips123/PWAsForFirefox/issues/507#issuecomment-2143762644), I tried the alternate method of copying over the runtime as mentioned [here](https://github.com/filips123/PWAsForFirefox/issues/505#issuecomment-2131125850). Then I got this.

It does solve #507 though. Also, I can click the extensions button and open it, but not the main PWA content. I had set the runtime to be patched, and patched it manually too.

![image](https://github.com/user-attachments/assets/38447dc6-51b3-4f1a-82de-e951496ea246)

### Steps to Reproduce

1. Install PWA
2. Open it

### Affected Websites

* Pinterest
* GitHub

### Environment

- Operating system: Void Linux GNU/Linux (musl libc)
- System architecture: x86_64
- Desktop environment: Hyprland
- Installation method: Source
- PWAsForFirefox extension version: 2.12.5
- PWAsForFirefox native version: 2.12.5
- PWAsForFirefox runtime version: 2.12.5
- Firefox version: 132.0

**Comment by blacklightpy** [comment]
No relevant error logs.

**Comment by filips123** [comment]
Please check if there are any [runtime logs](https://pwasforfirefox.filips.si/help/troubleshooting/#obtaining-runtime-logs).

**Comment by blacklightpy** [comment]
It got fixed after a while.

**Comment by blacklightpy** [comment]
Looks like it initially got the Zen browser runtime even though I copied vanilla Firefox runtime over, for some reason.. But now it works fine.
