### ISSUE TITLE
TLS 1.0 compatibility in pwa window

### ISSUE THREAD

**Issue by mjakubowskilkr** [filips123/PWAsForFirefox#591]
I've set minimal tls version to 1 on my Firefox and it works. But pwa version of page (the same Firefox) shows error: Error code: SSL_ERROR_UNSUPPORTED_VERSION

Can you fix it? I need these pages, there are local old printers which use TLS 1.0

**Comment by filips123** [comment]
PWAs run in a separate Firefox version, so you also need to additionally enable TLS 1.0 there. In the PWA, press `F6`, enter `about:config`, and then you can enable it.

**Comment by mjakubowskilkr** [comment]
Thanx a lot, I didn’t know how to get about:config at pwa window.

 

--

pozdrawiam 
Mariusz Jakubowski
