### ISSUE TITLE
No easy way to copy current window/tab as a link - Please add way to do this

### ISSUE THREAD

**Issue by schmilly** [filips123/PWAsForFirefox#596]
### Problem Description
The only way to copy a tab usually on Firefox requires the address bar. As PWA removes this there is no way to copy a link to currently open tab or web page. 

Instead have to try and go out of current page on to page with link to it and copy the hyperlink for that, which is a bit un-intuitive. 

### Proposed Solution
If you guys could add a button, shorcut or feature when in PWA's to copy current page link would help a lot with sharing info from generated PWA's that aren't restricted to a singular web page.

**Comment by filips123** [comment]
There is a "copy link" widget available. You can go to the Customize Toolbar page in the PWA and drag it to the toolbar.

**Comment by schmilly** [comment]
Perfect! Thank you!
