### ISSUE TITLE
New windows become disconnected from the original PWA

### ISSUE THREAD

**Issue by filips123** [filips123/PWAsForFirefox#79]
### Description

*New windows become disconnected from the original PWA.*

This only applies to windows opened by PWAs (for example, using `target="_blank"` links or `window.open`), but *not* windows opened by a user with app/context menus, keyboard shortcuts or shift-clicking on links.

On Windows, this means new windows will use the normal Firefox icon and probably merge with the normal Firefox shortcut in the taskbar. On Linux and macOS, this won't be so noticeable due to other issues. It will also cause them to lose functionality of changing window colors and will always have an address bar displayed.

### Steps to Reproduce

1. Change PWA settings to force links into a new window.
2. Open any PWA with `target="_blank"` links.
3. Shift-click on any link.
4. See that new window is "disconnected" from the original PWA.

### Possible Solution

This could be fixed if there is an easy way to intercept the opening of every new window, and pass it `window.gFFPWASiteConfig` from the original window just after it is created. I implemented this for some windows, but don't know how to do it for all windows.

**Comment by jamesharr** [comment]
I'm having a similar problem, but probably distinct.

I'm running Google Chat (chat.google.com) in Firefox PWA. When I click a link, say to a news website, I'd like to have it open in the system web browser (Firefox, default profile), but it loads in the PWA's window, replacing the PWA. If I use the context menu to open it in a new tab, similar results. Opening in a new window seems to use the same profile as the PWA, but at least doesn't replace the PWA.

Is this the same or separate issue?

**Comment by filips123** [comment]
If you want external links to open in a default browser, you can enable "Open out-of-scope URLs in a default browser" in the settings and add `accounts.google.com` to the "Domains always allowed to be opened in the PWA browser" input.

**Comment by jamesharr** [comment]
This is probably what I want, but I'm struggling to find these settings.

I've looked under the PWAsForFirefox settings (1), the individual App settings (2), and the Profile settings (3). I even took a peek at the Add-On page for PWAsForFirefox, the general firefox settings page, and even about:config to see if I could find these and I can't seem to locate it. Do I need to be running an alpha/beta build of this extensions to see these settings?

Image 1:
![image](https://user-images.githubusercontent.com/772818/209234775-e2331145-60fb-4253-aa60-8ed6bb9dc836.png)

Image 2:
![image](https://user-images.githubusercontent.com/772818/209234931-fc27c773-010f-402f-ab30-09f5ca46deee.png)
![image](https://user-images.githubusercontent.com/772818/209234905-b7ac968b-15c1-475a-b9e2-d94e98ffb025.png)

Image 3:
![image](https://user-images.githubusercontent.com/772818/209234981-02c0b3ba-ec2b-417a-bb96-af63aa45be58.png)

**Comment by filips123** [comment]
You need to open your PWA, open its browser menu and go to settings.

![menu](https://user-images.githubusercontent.com/16626308/209437038-fb772e3a-be43-45ba-ae4b-8f94ade0b651.png)

![settings](https://user-images.githubusercontent.com/16626308/209437066-b439778f-62d5-4e53-bf98-9d4bb3bbf352.png)

**Comment by jamesharr** [comment]
Ahh! Thank you!

**Comment by filips123** [comment]
This issue has mostly been fixed by 5586d7e9d5972fc1376f171d54517365a4090f52.
