### ISSUE TITLE
How to avoid using separate firefox for progressive apps?

### ISSUE THREAD

**Issue by Kreyren** [filips123/PWAsForFirefox#90]
>  This extension also needs a separate Mozilla Firefox runtime where all your Progressive Web App sites will run. Pressing the button below will automatically download the unmodified Mozilla Firefox from the Mozilla servers and locally modify it with the required modifications. 

I have hardened IceCat that i want to use for the webapps -> How can i do that?

CC @filips123

**Comment by filips123** [comment]
You can manually download/copy your IceCat installation to the required location (`$XDG_DATA_HOME/firefoxpwa/runtime/` or `$HOME/.local/share/firefoxpwa/runtime/` on Linux). See [FAQ #5](https://github.com/filips123/FirefoxPWA/wiki/Frequently-Asked-Questions) in the wiki. Alternatively, you can try to do something like #67 to "sync" your main IceCat installation.

I plan to add better/more detailed installation steps in the next release that will also explain how to do those things. However, there is no guarantee that IceCat will work correctly, as FirefoxPWA does some UI modifications that may conflict with it.

**Comment by Kreyren** [comment]
```console
kreyren@leonid ~/.local/share/firefoxpwa/runtime$ ls -la
total 8
drwxr-xr-x 1 kreyren users  36 Dec  2 00:33 ./
drwxr-xr-x 1 kreyren users 174 Dec  1 11:42 ../
lrwxrwxrwx 1 kreyren users  38 Dec  2 00:33 firefox -> /home/kreyren/.guix-profile/bin/icecat
lrwxrwxrwx 1 kreyren users  38 Dec  2 00:33 firefox-bin -> /home/kreyren/.guix-profile/bin/icecat
```

Missed it in the wiki, sorry!

It doesn't seem to be happy with that location as i keep getting prompt to install the runtime in the extension.

FWIW it installs the firefox in that directory when `firefoxpwa runtime install` is invoked so it should be the correct directory in nix's userland.

> Alternatively, you can try to do something like #67 to "sync" your main IceCat installation. -- @filips123 (https://github.com/filips123/FirefoxPWA/issues/90#issuecomment-983757123)

I want to avoid fuse overlays on this system atm so that is not a solution.

**Comment by filips123** [comment]
You will also need to symlink `application.ini` because [it is used](https://github.com/filips123/FirefoxPWA/blob/981a00b4444d2783d47557bd7456d0849e68a503/native/src/components/runtime.rs#L101-L122) to determine Firefox/runtime version.

**Comment by Kreyren** [comment]
Added the application.ini and now getting:

```console
kreyren@leonid ~/.local/share/firefoxpwa$ less firefoxpwa.log 
...
12:37:58 [INFO] Connection established: ["/usr/libexec/firefoxpwa-connector", "/usr/lib/mozilla/native-messaging-hosts/firefoxpwa.json", "firefoxpwa@filips.si"]
12:37:58 [INFO] Received a request: GetSystemVersions
12:37:58 [INFO] Processed the request: SystemVersions { firefoxpwa: Some("1.2.1"), firefox: None, _7zip: None }
kreyren@leonid ~/.local/share/firefoxpwa$ less firefoxpwa-stderr.log 
...
12:37:58 [INFO] Sent a response
10:42:39 [INFO] Profile patched!
10:42:39 [INFO] Launching the site
kreyren@leonid ~/.local/share/firefoxpwa$ less firefoxpwa-stdout.log 
<blank>
```

Seems that it's unable to determine the firefox version?

```console
kreyren@leonid ~/.local/share/firefoxpwa$ cat application.ini 
; This file is not used. If you modify it and want the application to use
; your modifications, move it under the browser/ subdirectory and start with
; the "-app /path/to/browser/application.ini" argument.
[App]
Vendor=GNU
Name=IceCat
RemotingName=icecat
Version=91.3.0
Profile=mozilla/icecat
BuildID=20211102000000
SourceStamp=8802d620459d50ea648821a15497d06efd15732b
ID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}

[Gecko]
MinVersion=91.3.0
MaxVersion=91.3.0

[XRE]
EnableProfileMigrator=1

kreyren@leonid ~/.local/share/firefoxpwa$ ls -la
total 748
drwxr-xr-x 1 kreyren users    240 Dec  4 13:37 ./
drwxr-xr-x 1 kreyren users    354 Dec  4 06:01 ../
lrwxrwxrwx 1 kreyren users     99 Dec  4 13:33 application.ini -> /gnu/store/1hsdn93kfmk418wcvpygq7fgsag1rms1-icecat-91.3.0-guix0-preview1/lib/icecat/application.ini
-rw-r--r-- 1 kreyren users   2651 Dec  1 11:33 config.json
-rw-r--r-- 1 kreyren users      0 Dec  1 11:37 DEBUG
lrwxrwxrwx 1 kreyren users     38 Dec  4 13:37 firefox -> /home/kreyren/.guix-profile/bin/icecat
lrwxrwxrwx 1 kreyren users     38 Dec  4 13:37 firefox-bin -> /home/kreyren/.guix-profile/bin/icecat
-rw-r--r-- 1 kreyren users 742278 Dec  4 13:40 firefoxpwa.log
-rw-r--r-- 1 kreyren users    175 Dec  1 11:42 firefoxpwa-stderr.log
-rw-r--r-- 1 kreyren users      0 Dec  1 11:42 firefoxpwa-stdout.log
drwxr-xr-x 1 kreyren users    104 Dec  1 11:17 profiles/
drwxr-xr-x 1 kreyren users     36 Dec  2 00:33 runtime/
```

**Comment by filips123** [comment]
You have those symlinks in `~/.local/share/firefoxpwa/`, but they should be in `~/.local/share/firefoxpwa/runtime/`.

**Comment by Kreyren** [comment]
Yep my fault it passes the extension setup and allows me to install apps now.

Closing as the issue is now more related to https://github.com/filips123/FirefoxPWA/issues/91

**Comment by Kreyren** [comment]
Now the issue seems to be that installing the PWA just opens a bare minimum icecat without it being borderless.

Where i expect to use the native icecat (native as the one that the system is using) as i want to preserve my hardening.

**Comment by filips123** [comment]
Do you mean it openes just a normal Icecat without any "PWA styling"? If so, it's probably because Guix isolates Icecat installation (and only public interface are those symlinks for binaries), so FirefoxPWA cannot apply [its patches](https://github.com/filips123/FirefoxPWA/tree/main/native/userchrome/runtime).

I think you could solve this by manually patching your main Icecat installation (which *shouldn't* actually affect your normal profiles) to load modifications from the PWA profile. You can do this by copying/symlinking files from `/usr/share/firefoxpwa/userchrome/runtime` to where your Icecat installation is.
