### ISSUE TITLE
Cannot expand Profile dropdown when installing a new app (Wayland)

### ISSUE THREAD

**Issue by 1player** [filips123/PWAsForFirefox#93]
### Description

When trying to install the current site from the extension window, the Profile dropdown doesn't expand by clicking on the caret. It does switch to the other options when using the arrows. Might be a Wayland-only issue.

### Steps to Reproduce

1. Create another profile so there's more than one.
2. Open the "Install current site" window
3. The Profile dropdown at the bottom of the screen shows Default. Press the caret on the right to expand the dropdown and pick another Profile. Nothing happens.

### Environment

* Operating system: Fedora 35
* System architecture: x64_64
* Desktop environment: GNOME/Wayland
* Installation method: RPM
* FirefoxPWA extension version: 1.2.1
* FirefoxPWA native version: 1.2.1
* Firefox version: 94.0

**Comment by filips123** [comment]
I was able to reroduce this issue on Ubuntu with Wayland, but Xorg it works fine.

I'm not sure why this hapens. Profile dropdown is just a normal Bootstrap select ([code](https://github.com/filips123/FirefoxPWA/blob/main/extension/src/sites/install.html#L44-L48), [docs](https://getbootstrap.com/docs/5.1/forms/select/)). Even if I remove all CSS from the popup, dropdown still doesn't work. Maybe its a bug with Firefox.

**Comment by 1player** [comment]
Perhaps related to https://bugzilla.mozilla.org/show_bug.cgi?id=1700340 ? There's more upstream bug reports about popups not appearing correctly on Wayland.

**Comment by 1player** [comment]
Well, I can't reproduce anymore today. Perhaps it has been fixed in Firefox 95? If it works for you as well @filips123 feel free to close it.

**Comment by filips123** [comment]
Ok, I'll close it. If anyone else still has this problem on Firefox 95 or newer, please let me know and I'll reopen the issue.
