### ISSUE TITLE
<meta> theme-color & background-color changes when updated in the page

### ISSUE THREAD

**Issue by thepra** [filips123/PWAsForFirefox#96]
### Problem Description

On Chromium based browsers and Safari che top UI of the window/app does reflect the changes to the meta elements behind `theme-color` and `background-color`.
On FirefoxPWA it doesn't work.
Working example:
![example](https://user-images.githubusercontent.com/7032509/144771156-1a4a3de2-4529-4bbc-bcdc-29b592337d3f.gif)
(sorry for the bright start, it's an HDR enabled screen)

### Proposed Solution

Have FirefoxPWA update the top window UI color based on such meta properties.

**Comment by xorik** [comment]
Hi. I also have an PWA, that changes header color, according to style.

Here's video from chrome:
https://www.youtube.com/watch?v=nqgqPnKaAqY

When primary color is changed, header color is also changed dynamically.
Would be nice to have in your addon.

**Comment by filips123** [comment]
Until I implement this, you can use an addon such as [VivaldiFox](https://addons.mozilla.org/firefox/addon/vivaldifox/) (and I think there are also some other similar addons) to do this. Just make sure you disable "Allow web apps to override a theme color" in Firefox settings and enable "Apply theme color" for Frame in VivaldiFox.
